const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const JournalService = require('../services/journalService');
const AccountBalance = require('../models/AccountBalance');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri, { useNewUrlParser: true });
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongoServer) await mongoServer.stop();
});

afterEach(async () => {
  const collections = Object.keys(mongoose.connection.collections);
  for (const name of collections) {
    await mongoose.connection.collections[name].deleteMany({});
  }
});

test('AccountBalance adjusts when journal entries are created', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  const lines = [
    JournalService.createDebitLine('1300', 200, 'Inventory debit'),
    JournalService.createCreditLine('2100', 200, 'AP credit')
  ];

  const entry = await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'Test balance update',
    sourceType: 'purchase',
    sourceId: new mongoose.Types.ObjectId(),
    lines,
    isAutoGenerated: true
  });

  expect(entry).toBeDefined();

  const invBal = await AccountBalance.findOne({ company: companyId, accountCode: '1300' }).lean();
  const apBal = await AccountBalance.findOne({ company: companyId, accountCode: '2100' }).lean();

  expect(invBal).toBeDefined();
  expect(apBal).toBeDefined();
  expect(invBal.debit).toBeCloseTo(200);
  expect(invBal.credit).toBeCloseTo(0);
  expect(apBal.credit).toBeCloseTo(200);
  expect(apBal.debit).toBeCloseTo(0);
});
