const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const JournalService = require('../services/journalService');
const accountingController = require('../controllers/accountingController');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri, { useNewUrlParser: true });
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongoServer) await mongoServer.stop();
});

afterEach(async () => {
  const collections = Object.keys(mongoose.connection.collections);
  for (const name of collections) {
    await mongoose.connection.collections[name].deleteMany({});
  }
});

test('healthCheck reports balanced totals as healthy', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  // Create two entries that net to equal totals
  await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'Entry A',
    sourceType: 'manual',
    sourceId: new mongoose.Types.ObjectId(),
    lines: [
      JournalService.createDebitLine('1300', 200, 'Debit A'),
      JournalService.createCreditLine('4100', 200, 'Credit A')
    ],
    isAutoGenerated: true
  });

  await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'Entry B',
    sourceType: 'manual',
    sourceId: new mongoose.Types.ObjectId(),
    lines: [
      JournalService.createDebitLine('1300', 50, 'Debit B'),
      JournalService.createCreditLine('4100', 50, 'Credit B')
    ],
    isAutoGenerated: true
  });

  // Mock req/res
  const req = { user: { company: { _id: companyId } } };
  let jsonOutput = null;
  const res = { json: (obj) => { jsonOutput = obj; } };

  await accountingController.healthCheck(req, res, () => {});

  expect(jsonOutput).toBeDefined();
  expect(jsonOutput.healthy).toBe(true);
  expect(jsonOutput.totalDebit).toBeCloseTo(jsonOutput.totalCredit, 2);
});
