const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const JournalService = require('../services/journalService');
const JournalEntry = require('../models/JournalEntry');
const journalController = require('../controllers/journalController');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri, { useNewUrlParser: true });
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongoServer) await mongoServer.stop();
});

afterEach(async () => {
  const collections = Object.keys(mongoose.connection.collections);
  for (const name of collections) {
    await mongoose.connection.collections[name].deleteMany({});
  }
});

test('reverse a posted journal entry creates a reversal and marks original reversed', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  const lines = [
    JournalService.createDebitLine('1300', 250, 'Debit line'),
    JournalService.createCreditLine('2100', 250, 'Credit line')
  ];

  // Create original posted entry (idempotent createEntry posts immediately)
  const orig = await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'Original entry for reversal test',
    sourceType: 'manual',
    sourceId: new mongoose.Types.ObjectId(),
    sourceReference: 'TST-1',
    lines,
    isAutoGenerated: false
  });

  expect(orig).toBeDefined();
  expect(orig.status).toBe('posted');

  // Mock request/response for controller
  const req = {
    params: { id: orig._id.toString() },
    body: { reason: 'Test reversal' },
    user: { company: { _id: companyId }, _id: userId }
  };

  const res = {
    json: jest.fn(),
    status: jest.fn().mockReturnThis()
  };

  const next = jest.fn();

  // Call controller
  await journalController.reverseJournalEntry(req, res, next);
  // If controller called next with an error, fail and show the error
  if (next.mock.calls && next.mock.calls.length > 0) {
    // next called with (err)
    throw next.mock.calls[0][0];
  }

  // Verify response was sent
  expect(res.json).toHaveBeenCalled();
  const arg = res.json.mock.calls[0][0];
  expect(arg.success).toBe(true);
  expect(arg.data).toBeDefined();

  // Verify database state
  const origReloaded = await JournalEntry.findById(orig._id).lean();
  expect(origReloaded.status).toBe('reversed');
  expect(origReloaded.reversed).toBe(true);
  expect(origReloaded.reversalEntryId).toBeDefined();

  const reversal = await JournalEntry.findOne({ sourceType: 'reversal', sourceId: orig._id });
  expect(reversal).toBeDefined();
  expect(reversal.totalDebit).toBeCloseTo(orig.totalCredit, 2);
  expect(reversal.totalCredit).toBeCloseTo(orig.totalDebit, 2);
});
