const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const JournalService = require('../services/journalService');
const JournalEntry = require('../models/JournalEntry');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri, { useNewUrlParser: true });
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongoServer) await mongoServer.stop();
});

afterEach(async () => {
  // Clear collections
  const collections = Object.keys(mongoose.connection.collections);
  for (const name of collections) {
    await mongoose.connection.collections[name].deleteMany({});
  }
});

test('createEntry creates a posted journal entry and is idempotent for same source', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();
  const sourceId = new mongoose.Types.ObjectId();

  const lines = [
    JournalService.createDebitLine('1300', 100, 'Inventory debit'),
    JournalService.createCreditLine('2100', 100, 'AP credit')
  ];

  const entry1 = await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'Test purchase',
    sourceType: 'purchase',
    sourceId,
    sourceReference: 'PO-1',
    lines,
    isAutoGenerated: true
  });

  expect(entry1).toBeDefined();
  expect(entry1.company.toString()).toBe(companyId.toString());
  expect(entry1.status).toBe('posted');

  // Call again with same source, should return existing entry (idempotent)
  const entry2 = await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'Test purchase duplicate',
    sourceType: 'purchase',
    sourceId,
    sourceReference: 'PO-1',
    lines,
    isAutoGenerated: true
  });

  expect(entry2._id.toString()).toBe(entry1._id.toString());
});

test('createEntry rejects unbalanced entries', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  const lines = [
    JournalService.createDebitLine('1300', 100, 'Inventory debit'),
    JournalService.createCreditLine('2100', 90, 'AP credit')
  ];

  await expect(
    JournalService.createEntry(companyId, userId, {
      date: new Date(),
      description: 'Unbalanced',
      sourceType: 'manual',
      lines,
      isAutoGenerated: false
    })
  ).rejects.toThrow(/not balanced/i);
});
