const JournalEntry = require('../models/JournalEntry');
const FixedAsset = require('../models/FixedAsset');
const { CHART_OF_ACCOUNTS, getAccount, getAccountsByType, DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');
const ChartOfAccount = require('../models/ChartOfAccount');
const JournalService = require('../services/journalService');
const AccountBalance = require('../models/AccountBalance');
const cacheService = require('../services/cacheService');
const { runInTransaction } = require('../services/transactionService');

// @desc    Get all journal entries
// @route   GET /api/journal-entries
// @access  Private
exports.getJournalEntries = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const { startDate, endDate, sourceType, status, search, page = 1, limit = 50 } = req.query;
    
    const query = { company: companyId };
    
    if (startDate || endDate) {
      query.date = {};
      if (startDate) query.date.$gte = new Date(startDate);
      if (endDate) query.date.$lte = new Date(endDate);
    }
    
    if (sourceType) query.sourceType = sourceType;
    if (status) query.status = status;
    
    // Search by entry number, description, or source reference
    if (search) {
      query.$or = [
        { entryNumber: { $regex: search, $options: 'i' } },
        { description: { $regex: search, $options: 'i' } },
        { sourceReference: { $regex: search, $options: 'i' } }
      ];
    }
    
    const entries = await JournalEntry.find(query)
      .populate('createdBy', 'name email')
      .populate('postedBy', 'name email')
      .sort({ date: -1, entryNumber: -1 })
      .skip((page - 1) * limit)
      .limit(parseInt(limit));
    
    const total = await JournalEntry.countDocuments(query);
    
    res.json({
      success: true,
      count: entries.length,
      total,
      pages: Math.ceil(total / limit),
      currentPage: parseInt(page),
      data: entries
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get single journal entry
// @route   GET /api/journal-entries/:id
// @access  Private
exports.getJournalEntry = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    
    const entry = await JournalEntry.findOne({ 
      _id: req.params.id, 
      company: companyId 
    })
      .populate('createdBy', 'name email')
      .populate('postedBy', 'name email');
    
    if (!entry) {
      return res.status(404).json({ success: false, message: 'Journal entry not found' });
    }
    
    res.json({ success: true, data: entry });
  } catch (error) {
    next(error);
  }
};

// @desc    Create manual journal entry
// @route   POST /api/journal-entries
// @access  Private
exports.createJournalEntry = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const userId = req.user._id;
    
    const { date, description, lines, notes, sourceType, sourceReference } = req.body;
    
    // Validate required fields
    if (!date || !description || !lines || lines.length < 2) {
      return res.status(400).json({ 
        success: false, 
        message: 'Please provide date, description, and at least 2 lines' 
      });
    }
    
    // Validate lines have valid account codes
    for (const line of lines) {
      if (!line.accountCode || !CHART_OF_ACCOUNTS[line.accountCode]) {
        return res.status(400).json({
          success: false,
          message: `Invalid account code: ${line.accountCode}`
        });
      }
    }
    
    // Calculate totals
    const totalDebit = lines.reduce((sum, line) => sum + (line.debit || 0), 0);
    const totalCredit = lines.reduce((sum, line) => sum + (line.credit || 0), 0);
    
    // Validate balance
    if (Math.abs(totalDebit - totalCredit) > 0.01) {
      return res.status(400).json({
        success: false,
        message: `Entry is not balanced. Debits: ${totalDebit.toFixed(2)}, Credits: ${totalCredit.toFixed(2)}`
      });
    }
    
    // Generate entry number
    const entryNumber = await JournalEntry.generateEntryNumber(companyId);
    
    // Enrich lines with account names
    const enrichedLines = lines.map(line => {
      const account = getAccount(line.accountCode);
      return {
        accountCode: line.accountCode,
        accountName: account?.name || 'Unknown Account',
        description: line.description || '',
        debit: line.debit || 0,
        credit: line.credit || 0,
        reference: line.reference || ''
      };
    });
    
    // Create entry
    const entry = await JournalEntry.create({
      company: companyId,
      entryNumber,
      date,
      description,
      lines: enrichedLines,
      totalDebit,
      totalCredit,
      // created entries are drafts by default; posting is a separate action
      status: 'draft',
      sourceType: sourceType || 'manual',
      sourceReference: sourceReference || null,
      isAutoGenerated: false,
      createdBy: userId,
      postedBy: null,
      notes: notes || ''
    });
    
    res.status(201).json({
      success: true,
      data: entry
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Post (finalize) a journal entry
// @route   PUT /api/journal-entries/:id/post
// Update a journal entry (only if not posted)
exports.updateJournalEntry = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const journalEntry = await JournalEntry.findOne({ _id: req.params.id, company: companyId });
    
    if (!journalEntry) {
      return res.status(404).json({ success: false, message: 'Journal entry not found' });
    }
    
    if (journalEntry.status === 'posted') {
      return res.status(400).json({ success: false, message: 'Cannot update a posted journal entry' });
    }
    
    const { date, description, lines } = req.body;
    
    if (date) journalEntry.date = new Date(date);
    if (description) journalEntry.description = description;
    if (lines) {
      journalEntry.lines = lines;
      // Recalculate totals
      let totalDebit = 0;
      let totalCredit = 0;
      lines.forEach(line => {
        if (line.debit) totalDebit += line.debit;
        if (line.credit) totalCredit += line.credit;
      });
      journalEntry.totalDebit = totalDebit;
      journalEntry.totalCredit = totalCredit;
    }
    
    await journalEntry.save();
    
    res.json({ success: true, data: journalEntry });
  } catch (err) {
    next(err);
  }
};

// @access  Private
exports.postJournalEntry = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const userId = req.user._id;
    const result = await runInTransaction(async (trx) => {
      const useSession = !!trx;
      const opts = useSession ? { session: trx } : {};

      const entry = useSession
        ? await JournalEntry.findOne({ _id: req.params.id, company: companyId }).session(trx)
        : await JournalEntry.findOne({ _id: req.params.id, company: companyId });

      if (!entry) throw Object.assign(new Error('Journal entry not found'), { statusCode: 404 });
      if (entry.status === 'posted') throw Object.assign(new Error('Entry is already posted'), { statusCode: 400 });
      if (entry.status === 'voided') throw Object.assign(new Error('Cannot post a voided entry'), { statusCode: 400 });
      if (!entry.isBalanced()) throw Object.assign(new Error('Cannot post unbalanced entry'), { statusCode: 400 });

      const periodService = require('../services/periodService');
      if (await periodService.isDateInClosedPeriod(companyId, entry.date)) {
        throw Object.assign(new Error('Accounting period is closed'), { statusCode: 400, code: 'PERIOD_CLOSED' });
      }

      entry.status = 'posted';
      entry.postedBy = userId;
      const postedEntry = await entry.save(opts);

      for (const line of entry.lines) {
        const deltaDebit = line.debit || 0;
        const deltaCredit = line.credit || 0;
        await AccountBalance.adjust(companyId, line.accountCode, deltaDebit, deltaCredit, opts);
      }

      try {
        await cacheService.bumpCompanyFinancialCaches(companyId);
      } catch (cacheErr) {
        console.error('Failed to invalidate report cache after posting entry', cacheErr);
      }

      return postedEntry;
    });

    return res.json({ success: true, data: result });
  } catch (error) {
    if (error && error.statusCode) return res.status(error.statusCode).json({ success: false, message: error.message });
    console.error('reverseJournalEntry error:', error && error.stack ? error.stack : error);
    next(error);
  }
};

// @desc    Reverse a posted journal entry
// @route   POST /api/journal-entries/:id/reverse
// @access  Private (accountant/admin)
exports.reverseJournalEntry = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const userId = req.user._id;
    const reason = req.body.reason || null;

    

    const mongoose = require('mongoose');
    const result = await runInTransaction(async (trx) => {
      const useSession = !!trx;
      const opts = useSession ? { session: trx } : {};

      const orig = useSession
        ? await JournalEntry.findOne({ _id: req.params.id, company: companyId }).session(trx)
        : await JournalEntry.findOne({ _id: req.params.id, company: companyId });

      if (!orig) throw Object.assign(new Error('Journal entry not found'), { statusCode: 404 });

      // If already reversed, return existing reversal (idempotent)
      if (orig.reversed && orig.reversalEntryId) {
        const existingRev = useSession
          ? await JournalEntry.findById(orig.reversalEntryId).session(trx)
          : await JournalEntry.findById(orig.reversalEntryId);
        if (existingRev) return existingRev;
      }

      if (orig.status !== 'posted') throw Object.assign(new Error('Only posted entries can be reversed'), { statusCode: 400 });

      const periodService = require('../services/periodService');
      if (await periodService.isDateInClosedPeriod(companyId, orig.date)) {
        throw Object.assign(new Error('Accounting period is closed; cannot reverse entries in a closed period'), { statusCode: 400, code: 'PERIOD_CLOSED' });
      }

      const toNum = (v) => {
        if (v == null) return 0;
        if (typeof v === 'number') return v;
        if (typeof v === 'string') return Number(v);
        if (v && typeof v === 'object') {
          if (v.$numberDecimal) return Number(v.$numberDecimal);
          try { return Number(v.toString()); } catch (e) { return 0; }
        }
        return Number(v) || 0;
      };

      const revLines = orig.lines.map(line => ({
        accountCode: line.accountCode,
        accountName: line.accountName,
        description: `Reversal: ${line.description || orig.description}`,
        debit: toNum(line.credit),
        credit: toNum(line.debit),
        reference: line.reference || orig.sourceReference || ''
      }));

      // debug logs removed
      const reversalEntry = await JournalService.createEntry(companyId, userId, {
        date: new Date(),
        description: `Reversal of ${orig.entryNumber}` + (reason ? ` - ${reason}` : ''),
        sourceType: 'reversal',
        sourceId: orig._id,
        sourceReference: orig.entryNumber,
        lines: revLines,
        isAutoGenerated: true
      }, Object.assign({}, { session: useSession ? trx : null }));

      // Set reversalOf on the reversal entry to point back to the original
      reversalEntry.reversalOf = orig._id;
      await reversalEntry.save(opts);

      orig.status = 'reversed';
      orig.reversed = true;
      orig.reversedAt = new Date();
      orig.reversedBy = userId;
      orig.reversalEntryId = reversalEntry._id;
      orig.notes = (orig.notes || '') + `\nReversed by ${userId} on ${new Date().toISOString()} - reversal entry ${reversalEntry.entryNumber}`;
      await orig.save(opts);

      try {
        await cacheService.bumpCompanyFinancialCaches(companyId);
      } catch (cacheErr) {
        console.error('Failed to invalidate report cache after reversal', cacheErr);
      }

      return reversalEntry;
    });

    return res.json({ success: true, data: result });
  } catch (error) {
    if (error && error.statusCode) return res.status(error.statusCode).json({ success: false, message: error.message });
    next(error);
  }
};

// @desc    Void journal entry
// @route   DELETE /api/journal-entries/:id
// @access  Private
exports.voidJournalEntry = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    
    const entry = await JournalEntry.findOne({ 
      _id: req.params.id, 
      company: companyId 
    });
    
    if (!entry) {
      return res.status(404).json({ success: false, message: 'Journal entry not found' });
    }
    
    if (entry.status === 'voided') {
      return res.status(400).json({ 
        success: false, 
        message: 'Entry is already voided' 
      });
    }

    if (entry.status === 'reversed') {
      return res.status(400).json({
        success: false,
        message: 'Cannot void a reversed entry'
      });
    }
    
    // Reverse AccountBalance adjustments if entry was posted
    if (entry.status === 'posted') {
      const toNum = (v) => {
        if (v == null) return 0;
        if (typeof v === 'number') return v;
        if (typeof v === 'string') return parseFloat(v) || 0;
        if (v && typeof v.toString === 'function') return parseFloat(v.toString()) || 0;
        return 0;
      };

      for (const line of entry.lines) {
        const debit = toNum(line.debit);
        const credit = toNum(line.credit);
        if (debit !== 0 || credit !== 0) {
          try {
            await AccountBalance.adjust(companyId, line.accountCode, -debit, -credit);
          } catch (balanceErr) {
            console.error(`Failed to reverse balance for account ${line.accountCode}:`, balanceErr);
          }
        }
      }
    }
    
    // Mark as voided instead of deleting
    entry.status = 'voided';
    entry.notes = (entry.notes || '') + '\nVoided on ' + new Date().toISOString();
    await entry.save();
    
    // Invalidate caches
    try {
      await cacheService.bumpCompanyFinancialCaches(companyId);
    } catch (e) {
      console.error('Cache invalidation after void failed:', e);
    }
    
    res.json({ success: true, message: 'Journal entry voided' });
  } catch (error) {
    next(error);
  }
};

// @desc    Get chart of accounts
// @route   GET /api/journal-entries/accounts
// @access  Private
exports.getAccounts = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const { type, subtype } = req.query;
    
    // Query database for actual accounts
    // Include inactive accounts if explicitly requested (for settings/liabilities)
    let query = { company: companyId };
    const includeInactive = req.query.includeInactive === 'true';
    if (!includeInactive) {
      query.isActive = true;
    }
    if (type) query.type = type;
    if (subtype) query.subtype = subtype;
    
    let accounts = await ChartOfAccount.find(query).sort({ code: 1 });
    
    // If no accounts in database, return default Chart of Accounts
    if (accounts.length === 0) {
      // Convert default CHART_OF_ACCOUNTS to array format
      const defaultAccounts = Object.entries(CHART_OF_ACCOUNTS).map(([code, details]) => ({
        _id: code, // Use code as ID for default accounts
        code,
        name: details.name,
        type: details.type,
        subtype: details.subtype,
        normalBalance: details.normalBalance,
        allowDirectPosting: details.allowDirectPosting,
        isActive: true,
        isDefault: true
      }));
      
      // Filter by type/subtype if specified
      let filtered = defaultAccounts;
      if (type) {
        filtered = filtered.filter(a => a.type === type);
      }
      if (subtype) {
        filtered = filtered.filter(a => a.subtype === subtype);
      }
      
      return res.json({ success: true, data: filtered });
    }
    
    res.json({ success: true, data: accounts });
  } catch (error) {
    next(error);
  }
};

// @desc    Get trial balance
// @route   GET /api/journal-entries/trial-balance
// @access  Private
exports.getTrialBalance = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const { startDate, endDate } = req.query;
    
    // Default to all dates (no filter) if not provided
    let query = { company: companyId, status: 'posted' };
    
    if (startDate || endDate) {
      query.date = {};
      if (startDate) query.date.$gte = new Date(startDate);
      if (endDate) query.date.$lte = new Date(endDate);
    }
    
    // If no date range is provided, prefer precomputed AccountBalance collection (fast)
    let accountBalances = {};
    if (!startDate && !endDate) {
      const AccountBalance = require('../models/AccountBalance');
      const balances = await AccountBalance.find({ company: companyId }).lean();
      balances.forEach(b => {
        const account = getAccount(b.accountCode) || {};
        accountBalances[b.accountCode] = {
          accountCode: b.accountCode,
          accountName: account.name || b.accountCode,
          accountType: account.type || 'unknown',
          normalBalance: account.normalBalance || 'debit',
          debit: b.debit || 0,
          credit: b.credit || 0,
          balance: 0
        };
      });
    } else {
      const entries = await JournalEntry.find(query);

      // Initialize account balances
      accountBalances = {};

      // Process each entry
      entries.forEach(entry => {
        entry.lines.forEach(line => {
          const code = line.accountCode;

          if (!accountBalances[code]) {
            const account = getAccount(code);
            accountBalances[code] = {
              accountCode: code,
              accountName: line.accountName,
              accountType: account?.type || 'unknown',
              normalBalance: account?.normalBalance || 'debit',
              debit: 0,
              credit: 0,
              balance: 0
            };
          }

          accountBalances[code].debit += line.debit || 0;
          accountBalances[code].credit += line.credit || 0;
        });
      });
    }
    
    // Calculate balances based on normal balance
    const report = Object.values(accountBalances).map(account => {
      // For assets and expenses (debit normal): balance = debit - credit
      // For liabilities, equity, and revenue (credit normal): balance = credit - debit
      if (account.normalBalance === 'debit') {
        account.balance = account.debit - account.credit;
      } else {
        account.balance = account.credit - account.debit;
      }

      // Map fields to frontend expected names and format numbers
      const mapped = {
        accountCode: account.accountCode,
        accountName: account.accountName,
        accountType: account.accountType,
        debit: parseFloat(account.debit.toFixed(2)),
        credit: parseFloat(account.credit.toFixed(2)),
        balance: parseFloat(account.balance.toFixed(2))
      };

      return mapped;
    });
    
    // Sort by account code
    report.sort((a, b) => (a.accountCode || '').localeCompare(b.accountCode || ''));
    
    // Calculate totals
    const totals = {
      totalDebit: parseFloat(report.reduce((sum, a) => sum + a.debit, 0).toFixed(2)),
      totalCredit: parseFloat(report.reduce((sum, a) => sum + a.credit, 0).toFixed(2)),
      totalBalance: parseFloat(report.reduce((sum, a) => sum + Math.abs(a.balance), 0).toFixed(2))
    };
    
    // Group by account type
    const byType = {};
    report.forEach(account => {
      const t = account.accountType || 'unknown';
      if (!byType[t]) {
        byType[t] = {
          type: t,
          accounts: [],
          totalDebit: 0,
          totalCredit: 0
        };
      }
      byType[t].accounts.push(account);
      byType[t].totalDebit += account.debit;
      byType[t].totalCredit += account.credit;
    });
    
    res.json({
      success: true,
      data: report,
      totals,
      byType,
      period: (startDate || endDate)
        ? { start: startDate || null, end: endDate || null }
        : { start: null, end: null }
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Get general ledger
// @route   GET /api/journal-entries/general-ledger
// @access  Private
exports.getGeneralLedger = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const { startDate, endDate, accountCode } = req.query;
    
    // Build aggregation pipeline for efficient ledger computation
    const matchStage = {
      company: new (require('mongoose').Types.ObjectId)(companyId),
      status: 'posted',
      reversed: { $ne: true }
    };
    
    if (startDate || endDate) {
      matchStage.date = {};
      if (startDate) matchStage.date.$gte = new Date(startDate);
      if (endDate) matchStage.date.$lte = new Date(endDate);
    }

    const pipeline = [
      { $match: matchStage },
      { $unwind: '$lines' },
      { $match: accountCode ? { 'lines.accountCode': accountCode } : {} },
      { $sort: { date: 1, entryNumber: 1 } },
      {
        $group: {
          _id: '$lines.accountCode',
          name: { $first: '$lines.accountName' },
          transactions: {
            $push: {
              date: '$date',
              entryNumber: '$entryNumber',
              description: '$description',
              reference: { $ifNull: ['$lines.reference', '$sourceReference'] },
              debit: '$lines.debit',
              credit: '$lines.credit'
            }
          },
          totalDebit: { $sum: '$lines.debit' },
          totalCredit: { $sum: '$lines.credit' }
        }
      },
      { $sort: { _id: 1 } }
    ];

    const results = await JournalEntry.aggregate(pipeline).exec();

    // Build ledger with account info and running balance
    const ledger = results.map(group => {
      const code = group._id;
      const account = getAccount(code);
      const normalBalance = account?.normalBalance || 'debit';

      // Convert Decimal128 to numbers
      const transactions = group.transactions.map(t => ({
        date: t.date,
        entryNumber: t.entryNumber,
        description: t.description,
        reference: t.reference,
        debit: parseFloat(t.debit?.toString() || '0'),
        credit: parseFloat(t.credit?.toString() || '0')
      }));

      const totalDebit = parseFloat(group.totalDebit?.toString() || '0');
      const totalCredit = parseFloat(group.totalCredit?.toString() || '0');

      const closingBalance = normalBalance === 'debit'
        ? totalDebit - totalCredit
        : totalCredit - totalDebit;

      return {
        code,
        name: group.name,
        type: account?.type || 'unknown',
        normalBalance,
        openingBalance: 0,
        transactions,
        closingBalance: parseFloat(closingBalance.toFixed(2))
      };
    });

    res.json({
      success: true,
      count: ledger.length,
      data: ledger
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Run depreciation for all fixed assets and create journal entries
// @route   POST /api/journal-entries/run-depreciation
// @access  Private
exports.runDepreciation = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const userId = req.user._id;
    const { period } = req.body; // e.g., '2026-01', '2026-02', etc. or 'all' for all periods from purchase
    
    // Get all active fixed assets for the company
    const assets = await FixedAsset.find({ 
      company: companyId,
      status: { $in: ['active', 'in_use'] }
    });
    
    if (!assets || assets.length === 0) {
      return res.status(404).json({ 
        success: false, 
        message: 'No active fixed assets found' 
      });
    }
    
    const results = {
      totalAssets: assets.length,
      processed: 0,
      skipped: 0,
      errors: [],
      journalEntries: []
    };
    
    const now = new Date();
    
    // Determine if we should process all periods or a specific period
    const processAllPeriods = !period || period === 'all';
    
    // If not processing all periods, calculate depreciation for the specified period
    const periodDate = processAllPeriods 
      ? null 
      : (period ? new Date(period + '-01') : new Date(now.getFullYear(), now.getMonth(), 1));
    
    const periodLabel = processAllPeriods 
      ? null 
      : (period || `${periodDate.getFullYear()}-${String(periodDate.getMonth() + 1).padStart(2, '0')}`);
    
    // Process each asset
    for (const asset of assets) {
      try {
        // Check if asset has depreciation settings
        if (!asset.usefulLifeYears || asset.usefulLifeYears <= 0) {
          results.skipped++;
          continue;
        }
        
        // Check if asset is fully depreciated
        if (asset.isFullyDepreciated) {
          results.skipped++;
          continue;
        }
        
        // Get the monthly depreciation amount
        const annualDepreciation = asset.annualDepreciation || 0;
        const monthlyDepreciation = annualDepreciation / 12;
        
        if (monthlyDepreciation <= 0) {
          results.skipped++;
          continue;
        }
        
        // Calculate depreciation start and end dates
        const purchaseDate = new Date(asset.purchaseDate);
        const depStartDate = new Date(Date.UTC(purchaseDate.getUTCFullYear(), purchaseDate.getUTCMonth(), 1));
        const depEndDate = new Date(Date.UTC(
          depStartDate.getUTCFullYear(),
          depStartDate.getUTCMonth() + (asset.usefulLifeYears * 12),
          1
        ));
        
        // Determine which months to process
        let monthsToProcess = [];
        
        if (processAllPeriods) {
          // Process all months from purchase date to now
          let currentMonth = new Date(depStartDate);
          const currentDate = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1));
          
          while (currentMonth < depEndDate && currentMonth <= currentDate) {
            const monthLabel = `${currentMonth.getUTCFullYear()}-${String(currentMonth.getUTCMonth() + 1).padStart(2, '0')}`;
            monthsToProcess.push({
              date: new Date(currentMonth),
              label: monthLabel
            });
            // Move to next month
            currentMonth = new Date(Date.UTC(
              currentMonth.getUTCFullYear(),
              currentMonth.getUTCMonth() + 1,
              1
            ));
          }
        } else {
          // Process just the specified period
          monthsToProcess.push({
            date: periodDate,
            label: periodLabel
          });
        }
        
        // Process each month
        for (const monthInfo of monthsToProcess) {
          // Check if depreciation entry already exists for this period
          const existingEntry = await JournalEntry.findOne({
            company: companyId,
            sourceType: 'depreciation',
            sourceId: asset._id,
            description: { $regex: new RegExp(monthInfo.label, 'i') }
          });
          
          if (existingEntry) {
            // Entry already exists for this period, skip
            continue;
          }
          
          // Create depreciation journal entry
          // Debit: Depreciation Expense (5900)
          // Credit: Accumulated Depreciation (1800)
          const entry = await JournalService.createEntry(companyId, userId, {
            date: monthInfo.date,
            description: `Depreciation - ${asset.name} - ${monthInfo.label}`,
            sourceType: 'depreciation',
            sourceId: asset._id,
            sourceReference: asset.assetCode,
            lines: [
              JournalService.createDebitLine(
                DEFAULT_ACCOUNTS.depreciation,
                monthlyDepreciation,
                `Depreciation: ${asset.name}`
              ),
              JournalService.createCreditLine(
                DEFAULT_ACCOUNTS.accumulatedDepreciation,
                monthlyDepreciation,
                `Accumulated depreciation: ${asset.name}`
              )
            ],
            isAutoGenerated: true
          });
          
          // Update asset's accumulated depreciation
          asset.accumulatedDepreciation = (asset.accumulatedDepreciation || 0) + monthlyDepreciation;
          
          results.processed++;
          results.journalEntries.push({
            assetCode: asset.assetCode,
            assetName: asset.name,
            amount: monthlyDepreciation,
            period: monthInfo.label,
            entryNumber: entry.entryNumber
          });
        }
        
        // Save the asset with updated accumulated depreciation
        await asset.save();
        
      } catch (assetError) {
        results.errors.push({
          assetCode: asset.assetCode,
          error: assetError.message
        });
      }
    }
    
    res.json({
      success: true,
      message: `Depreciation processed: ${results.processed} entries created, ${results.skipped} skipped`,
      data: results
    });
  } catch (error) {
    next(error);
  }
};

// @desc    Export journal entries as CSV
// @route   GET /api/journal-entries/export
// @access  Private
exports.exportJournalEntries = async (req, res, next) => {
  try {
    const companyId = req.user.company._id;
    const { startDate, endDate, sourceType, status } = req.query;

    const query = { company: companyId };
    if (startDate || endDate) {
      query.date = {};
      if (startDate) query.date.$gte = new Date(startDate);
      if (endDate) query.date.$lte = new Date(endDate);
    }
    if (sourceType) query.sourceType = sourceType;
    if (status) query.status = status;

    const entries = await JournalEntry.find(query)
      .sort({ date: 1, entryNumber: 1 })
      .lean();

    // Build CSV
    const csvRows = ['Entry Number,Date,Description,Source Type,Status,Account Code,Account Name,Debit,Credit'];
    for (const entry of entries) {
      for (const line of entry.lines) {
        const debit = parseFloat(line.debit?.toString() || '0');
        const credit = parseFloat(line.credit?.toString() || '0');
        csvRows.push([
          entry.entryNumber,
          new Date(entry.date).toISOString().split('T')[0],
          `"${(entry.description || '').replace(/"/g, '""')}"`,
          entry.sourceType || 'manual',
          entry.status,
          line.accountCode,
          `"${(line.accountName || '').replace(/"/g, '""')}"`,
          debit,
          credit
        ].join(','));
      }
    }

    const csv = csvRows.join('\n');
    res.setHeader('Content-Type', 'text/csv');
    res.setHeader('Content-Disposition', `attachment; filename=journal-entries-${Date.now()}.csv`);
    res.send(csv);
  } catch (error) {
    next(error);
  }
};
