const mongoose = require('mongoose');
const Expense = require('../models/Expense');
const JournalEntry = require('../models/JournalEntry');
const ChartOfAccount = require('../models/ChartOfAccount');
const { BankAccount } = require('../models/BankAccount');
const { nextSequence } = require('./sequenceService');
const PeriodService = require('./periodService');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');
const TaxAutomationService = require('./taxAutomationService');

class ExpenseService {

  // ── POST EXPENSE ─────────────────────────────────────────────────────
  static async post(companyId, data, userId) {
    // Validate expense account belongs to this company
    // Find expense account by id then verify company ownership to avoid tenant-plugin interference
    console.log('ExpenseService.post - looking up expense_account_id', data.expense_account_id && data.expense_account_id.toString());
    // Try a query with explicit skipTenant option (preferred over raw collection)
    let expenseAccount = null;
    try {
      expenseAccount = await ChartOfAccount.findOne({ _id: data.expense_account_id }).setOptions({ skipTenant: true }).exec();
    } catch (e) {
      expenseAccount = null;
    }

    if (!expenseAccount || String(expenseAccount.company) !== String(companyId)) {
      console.error('ExpenseService.post - ownership mismatch', {
        expenseAccount: expenseAccount || null,
        expenseAccountCompany: expenseAccount && expenseAccount.company && String(expenseAccount.company),
        passedCompanyId: companyId && String(companyId)
      });
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    // Validate payment method has required source account
    await ExpenseService._validatePaymentSource(companyId, data);

    // Validate tax account if tax provided
    let taxAccount = null;
    if (data.tax_amount > 0 && data.tax_account_id) {
      try {
        taxAccount = await ChartOfAccount.findOne({ _id: data.tax_account_id }).setOptions({ skipTenant: true }).exec();
      } catch (e) {
        taxAccount = null;
      }
      if (!taxAccount || String(taxAccount.company) !== String(companyId)) {
        const error = new Error('NOT_FOUND');
        error.statusCode = 404;
        throw error;
      }
    }

    const periodId = await PeriodService.getOpenPeriodId(
      companyId,
      data.expense_date
    );

    try {
      const refNo = await nextSequence(companyId, 'EXP');
      // Use separate JE sequence for journal entry numbers to avoid collisions
      const jeEntryNumber = await nextSequence(companyId, 'journal_entry');

      // Build journal lines based on payment method
      const lines = await ExpenseService._buildJournalLines(
        companyId,
        data,
        expenseAccount,
        taxAccount
      );

      // Create journal entry
      const journalEntry = await JournalEntry.create({
        company: companyId,
        entryNumber: jeEntryNumber,
        date: data.expense_date,
        description: `Expense - ${data.description} - EXP#${refNo}`,
        sourceType: 'expense',
        sourceId: `expense_${companyId}_${refNo}`,
        reference: refNo,
        status: 'posted',
        lines,
        totalDebit: data.total_amount,
        totalCredit: data.total_amount,
        debitTotal: data.total_amount,
        creditTotal: data.total_amount,
        postedBy: userId,
        period: periodId,
        isAutoGenerated: false
      });

      // Calculate total
      const totalAmount = data.amount + (data.tax_amount || 0);

      // Create expense record
      const expense = await Expense.create({
        company: companyId,
        reference_no: refNo,
        expense_date: data.expense_date,
        description: data.description,
        expense_account_id: data.expense_account_id,
        amount: data.amount,
        tax_amount: data.tax_amount || 0,
        total_amount: totalAmount,
        tax_account_id: data.tax_account_id || null,
        payment_method: data.payment_method,
        bank_account_id: data.bank_account_id || null,
        petty_cash_fund_id: data.petty_cash_fund_id || null,
        supplier_id: data.supplier_id || null,
        receipt_ref: data.receipt_ref || null,
        status: 'posted',
        journal_entry_id: journalEntry._id,
        posted_by: userId,
        type: data.type || 'other_expense',
        notes: data.notes || null
      });

      // If payment method is bank, update bank account balance
      if (data.payment_method === 'bank' && data.bank_account_id) {
        const bankAccount = await BankAccount.findOne({
          _id: data.bank_account_id,
          company: companyId
        });
        if (bankAccount) {
          bankAccount.currentBalance = (bankAccount.currentBalance || 0) - totalAmount;
          await bankAccount.save();
        }
      }

      return expense;

    } catch (err) {
      throw err;
    }
  }

  // ── VALIDATE PAYMENT SOURCE ───────────────────────────────────────────
  static async _validatePaymentSource(companyId, data) {
    if (data.payment_method === 'bank') {
      if (!data.bank_account_id) {
        const error = new Error('BANK_ACCOUNT_REQUIRED');
        error.statusCode = 400;
        throw error;
      }
      const bankAccount = await BankAccount.findOne({ 
        _id: data.bank_account_id, 
        company: companyId 
      });
      if (!bankAccount) {
        const error = new Error('NOT_FOUND');
        error.statusCode = 404;
        throw error;
      }
    }

    if (data.payment_method === 'petty_cash') {
      if (!data.petty_cash_fund_id) {
        const error = new Error('PETTY_CASH_FUND_REQUIRED');
        error.statusCode = 400;
        throw error;
      }
      // Validate petty cash fund belongs to this company and has sufficient balance
      const { PettyCashFloat } = require('../models/PettyCash');
      try {
        const sample = await PettyCashFloat.find({}).limit(5).lean();
        console.log('ExpenseService._validatePaymentSource - PettyCash sample', sample.map(s => ({ id: s._id && s._id.toString(), company: s.company && s.company.toString(), currentBalance: s.currentBalance })));
      } catch (e) {
        // ignore
      }
      // Query explicitly by company to avoid relying on tenant-plugin opt-out
      let pettyCashFund = null;
      try {
        pettyCashFund = await PettyCashFloat.findOne({ _id: data.petty_cash_fund_id, company: companyId }).exec();
      } catch (e) {
        pettyCashFund = null;
      }
      if (!pettyCashFund) {
        console.error('ExpenseService._validatePaymentSource - pettyCash lookup', { pettyCashFund: pettyCashFund || null, passedCompanyId: companyId && String(companyId) });
        const error = new Error('NOT_FOUND');
        error.statusCode = 404;
        throw error;
      }
      const totalAmount = data.amount + (data.tax_amount || 0);
      if (pettyCashFund.currentBalance < totalAmount) {
        const error = new Error('INSUFFICIENT_PETTY_CASH');
        error.statusCode = 400;
        throw error;
      }
    }
  }

  // ── BUILD JOURNAL LINES ───────────────────────────────────────────────
  static async _buildJournalLines(companyId, data, expenseAccount, taxAccount) {
    const lines = [];

    // Use TaxAutomationService for centralized tax computation
    const expenseTax = await TaxAutomationService.computeExpenseTax(companyId, {
      expenseAccountCode: expenseAccount.code,
      netAmount: data.amount,
      taxRatePct: data.tax_amount > 0 ? ((data.tax_amount / data.amount) * 100) : 0
    });

    // Debit: Expense Account (net amount)
    lines.push({
      accountCode: expenseAccount.code,
      accountName: expenseAccount.name,
      description: data.description,
      debit: expenseTax.netAmount,
      credit: 0
    });

    // VAT input tax line (if applicable) — uses new 2210 account
    if (data.tax_amount > 0) {
      const vatInputCode = (taxAccount && taxAccount.code) || DEFAULT_ACCOUNTS.vatInput || '2210';
      const vatInputName = (taxAccount && taxAccount.name) || 'VAT Input';
      lines.push({
        accountCode: vatInputCode,
        accountName: vatInputName,
        description: 'Input VAT on expense',
        debit: expenseTax.taxAmount,
        credit: 0
      });
    }

    const totalDr = expenseTax.netAmount + expenseTax.taxAmount;

    // Credit line — depends on payment method
    if (data.payment_method === 'bank') {
      let bankAccount = null;
      try {
        bankAccount = await BankAccount.findOne({ _id: data.bank_account_id }).setOptions({ skipTenant: true }).exec();
      } catch (e) {
        bankAccount = null;
      }
      if (bankAccount && String(bankAccount.company) === String(companyId)) {
        lines.push({
          accountCode: bankAccount.accountCode || '1100',
          accountName: bankAccount.name || 'Cash at Bank',
          description: 'Bank payment for expense',
          debit: 0,
          credit: totalDr
        });
      }
    }

    if (data.payment_method === 'petty_cash') {
      // Petty cash ledger account
      lines.push({
        accountCode: '1050',
        accountName: 'Petty Cash',
        description: 'Petty cash payment for expense',
        debit: 0,
        credit: totalDr
      });
    }

    if (data.payment_method === 'payable') {
      // Post to accrued liabilities — no cash yet
      let accrualAccount = null;
      try {
        accrualAccount = await ChartOfAccount.findOne({ company: companyId, subtype: 'accrual', isActive: true }).setOptions({ skipTenant: true }).exec();
      } catch (e) {
        accrualAccount = null;
      }
      if (!accrualAccount) {
        // Use default accrued expenses account
        lines.push({
          accountCode: '2600',
          accountName: 'Accrued Expenses',
          description: 'Accrued liability for expense',
          debit: 0,
          credit: totalDr
        });
      } else {
        lines.push({
          accountCode: accrualAccount.code,
          accountName: accrualAccount.name,
          description: 'Accrued liability for expense',
          debit: 0,
          credit: totalDr
        });
      }
    }

    if (data.payment_method === 'credit_card') {
      // Post to accrued expenses payable
      lines.push({
        accountCode: DEFAULT_ACCOUNTS.accruedExpenses || '2600',
        accountName: 'Credit Card Payable',
        description: 'Credit card payment for expense',
        debit: 0,
        credit: totalDr
      });
    }

    return lines;
  }

  // ── REVERSE EXPENSE ──────────────────────────────────────────────────
  static async reverse(companyId, expenseId, data, userId) {
    const expense = await Expense.findOne({ 
      _id: expenseId, 
      company: companyId 
    });

    if (!expense) {
      const error = new Error('NOT_FOUND');
      error.statusCode = 404;
      throw error;
    }

    if (expense.status === 'reversed') {
      const error = new Error('EXPENSE_ALREADY_REVERSED');
      error.statusCode = 400;
      throw error;
    }

    if (!expense.journal_entry_id) {
      const error = new Error('NO_JOURNAL_ENTRY');
      error.statusCode = 400;
      throw error;
    }

    try {
      const originalEntry = await JournalEntry.findById(expense.journal_entry_id);
      if (!originalEntry) {
        const error = new Error('JOURNAL_ENTRY_NOT_FOUND');
        error.statusCode = 404;
        throw error;
      }

      // Create reversal journal entry
      const periodId = await PeriodService.getOpenPeriodId(
        companyId,
        data.reversal_date || new Date()
      );

      const reversalEntryNumber = await nextSequence(companyId, 'journal_entry');
      
      // Reverse the lines (DR becomes CR, CR becomes DR)
      const reversalLines = originalEntry.lines.map(line => ({
        accountCode: line.accountCode,
        accountName: line.accountName,
        description: `REVERSAL: ${line.description}`,
        debit: line.credit || 0,
        credit: line.debit || 0
      }));

      const reversalEntry = await JournalEntry.create({
        company: companyId,
        entryNumber: reversalEntryNumber,
        date: data.reversal_date || new Date(),
        description: `Expense Reversal - ${expense.description} - EXP#${expense.reference_no}`,
        sourceType: 'reversal',
        sourceId: `expense_reversal_${companyId}_${expenseId}`,
        reference: expense.reference_no,
        status: 'posted',
        lines: reversalLines,
        totalDebit: expense.total_amount,
        totalCredit: expense.total_amount,
        debitTotal: expense.total_amount,
        creditTotal: expense.total_amount,
        postedBy: userId,
        period: periodId,
        isAutoGenerated: false
      });

      // Update expense status
      expense.status = 'reversed';
      expense.reversal_journal_entry_id = reversalEntry._id;
      await expense.save();

      // Restore bank account balance if applicable
      if (expense.payment_method === 'bank' && expense.bank_account_id) {
        const bankAccount = await BankAccount.findOne({
          _id: expense.bank_account_id,
          company: companyId
        });
        if (bankAccount) {
          bankAccount.currentBalance = (bankAccount.currentBalance || 0) + expense.total_amount;
          await bankAccount.save();
        }
      }

      return expense;

    } catch (err) {
      throw err;
    }
  }
}

module.exports = ExpenseService;
