/**
 * MODULE 7 - Opening Balance Service
 * 
 * Handles importing opening balances when a company goes live on the system.
 * Posts a single balanced journal entry to establish starting positions.
 */

const JournalEntry = require('../models/JournalEntry');
const ChartOfAccount = require('../models/ChartOfAccount');
const CompanyService = require('./CompanyService');
const AuditLogService = require('./AuditLogService');
const periodService = require('./periodService');

class OpeningBalanceService {

  /**
   * Bulk import opening balances for all accounts
   * @param {string} companyId - Company ID
   * @param {object} options - { asOfDate, balances }
   * @param {string} userId - User ID performing the action
   */
  static async import(companyId, { asOfDate, balances }, userId) {
    // Validate asOfDate
    if (!asOfDate) {
      const error = new Error('AS_OF_DATE_REQUIRED');
      error.code = 'AS_OF_DATE_REQUIRED';
      throw error;
    }

    // Validate balances
    if (!balances || !Array.isArray(balances) || balances.length === 0) {
      const error = new Error('BALANCES_REQUIRED');
      error.code = 'BALANCES_REQUIRED';
      throw error;
    }

    // Validate no transactions exist yet (except opening_balance)
    const existingCount = await JournalEntry.countDocuments({
      company: companyId,
      sourceType: { $ne: 'opening_balance' }
    });

    if (existingCount > 0) {
      const error = new Error(
        'TRANSACTIONS_EXIST: Opening balances can only be imported before any transactions. ' +
        'Use manual journal entries to correct specific account balances instead.'
      );
      error.code = 'TRANSACTIONS_EXIST';
      throw error;
    }

    // Validate all accounts belong to this company
    for (const bal of balances) {
      const account = await ChartOfAccount.findOne({
        _id: bal.account_id,
        company: companyId
      });

      if (!account) {
        const error = new Error(`ACCOUNT_NOT_FOUND: Account ${bal.account_id} not found or does not belong to company`);
        error.code = 'ACCOUNT_NOT_FOUND';
        throw error;
      }
    }

    // Validate the submitted balances are themselves balanced
    const totalDr = balances
      .filter(b => b.entry_type === 'debit')
      .reduce((s, b) => s + parseFloat(b.amount || 0), 0);

    const totalCr = balances
      .filter(b => b.entry_type === 'credit')
      .reduce((s, b) => s + parseFloat(b.amount || 0), 0);

    if (Math.abs(totalDr - totalCr) > 0.01) {
      const error = new Error(
        `OPENING_BALANCES_UNBALANCED: Total debits (${totalDr}) must equal ` +
        `total credits (${totalCr}). Difference: ${Math.abs(totalDr - totalCr)}`
      );
      error.code = 'OPENING_BALANCES_UNBALANCED';
      error.totalDr = totalDr;
      error.totalCr = totalCr;
      error.difference = Math.abs(totalDr - totalCr);
      throw error;
    }

    // Check if opening balance already exists (idempotency)
    const existingOpeningBalance = await JournalEntry.findOne({
      company: companyId,
      sourceType: 'opening_balance'
    });

    if (existingOpeningBalance) {
      const error = new Error('OPENING_BALANCE_ALREADY_EXISTS: Opening balances have already been imported. Import is idempotent.');
      error.code = 'OPENING_BALANCE_ALREADY_EXISTS';
      throw error;
    }

    // Get or create a period for the opening balance date
    const periodId = await periodService.getOpenPeriodId(companyId, asOfDate);

    // Build journal entry lines from balances
    const lines = await Promise.all(balances.map(async (bal) => {
      const account = await ChartOfAccount.findById(bal.account_id);
      return {
        accountCode: account.code,
        accountName: account.name,
        description: bal.description || `Opening balance - ${account.code}`,
        debit: bal.entry_type === 'debit' ? parseFloat(bal.amount || 0) : 0,
        credit: bal.entry_type === 'credit' ? parseFloat(bal.amount || 0) : 0
      };
    }));

    // Post the opening balance journal entry
    const JournalService = require('./journalService');
    const asOfDateObj = new Date(asOfDate);
    
    const journalEntry = await JournalService.createEntry(companyId, userId, {
      date: asOfDateObj,
      description: `Opening Balances as at ${asOfDate}`,
      sourceType: 'opening_balance',
      sourceId: `opening_${companyId}_${asOfDate}`,
      lines: lines,
      isAutoGenerated: true
    });

    // Mark setup step as complete
    await CompanyService.markSetupStepComplete(companyId, 'opening_balances');

    // Log to audit trail
    await AuditLogService.log({
      companyId,
      userId,
      action: 'opening_balances.import',
      entityType: 'journal_entry',
      entityId: journalEntry._id,
      changes: {
        as_of_date: asOfDate,
        account_count: balances.length,
        total_dr: totalDr,
        total_cr: totalCr
      }
    });

    return {
      journal_entry_id: journalEntry._id,
      entry_number: journalEntry.entryNumber,
      as_of_date: asOfDate,
      accounts_imported: balances.length,
      total_dr: totalDr,
      total_cr: totalCr
    };
  }

  /**
   * Preview what the opening balance entry will look like before committing
   * @param {string} companyId - Company ID
   * @param {object} options - { asOfDate, balances }
   */
  static async preview(companyId, { asOfDate, balances }) {
    const totalDr = balances
      .filter(b => b.entry_type === 'debit')
      .reduce((s, b) => s + parseFloat(b.amount || 0), 0);

    const totalCr = balances
      .filter(b => b.entry_type === 'credit')
      .reduce((s, b) => s + parseFloat(b.amount || 0), 0);

    const isBalanced = Math.abs(totalDr - totalCr) < 0.01;

    // Enrich with account info
    const enrichedLines = await Promise.all(balances.map(async (bal) => {
      let accountName = 'Unknown';
      try {
        const account = await ChartOfAccount.findById(bal.account_id).lean();
        if (account) {
          accountName = account.name;
        }
      } catch (e) {
        // Account might not exist
      }
      return {
        account_id: bal.account_id,
        account_name: accountName,
        entry_type: bal.entry_type,
        amount: parseFloat(bal.amount || 0),
        description: bal.description || ''
      };
    }));

    return {
      as_of_date: asOfDate,
      total_dr: Math.round(totalDr * 100) / 100,
      total_cr: Math.round(totalCr * 100) / 100,
      difference: Math.round(Math.abs(totalDr - totalCr) * 100) / 100,
      is_balanced: isBalanced,
      line_count: balances.length,
      lines: enrichedLines
    };
  }

  /**
   * Get the posted opening balance entry
   * @param {string} companyId - Company ID
   */
  static async get(companyId) {
    const journalEntry = await JournalEntry.findOne({
      company: companyId,
      sourceType: 'opening_balance'
    }).lean();

    if (!journalEntry) {
      return null;
    }

    return {
      journal_entry_id: journalEntry._id,
      entry_number: journalEntry.entryNumber,
      date: journalEntry.date,
      description: journalEntry.description,
      total_debit: journalEntry.totalDebit,
      total_credit: journalEntry.totalCredit,
      lines: journalEntry.lines,
      created_at: journalEntry.createdAt
    };
  }

  /**
   * Import opening balances from CSV data
   * @param {string} companyId - Company ID
   * @param {Array} csvData - Array of { account_code, account_name, entry_type, amount, description }
   * @param {string} userId - User ID
   * @param {string} asOfDate - As of date
   */
  static async importFromCSV(companyId, csvData, userId, asOfDate) {
    // Convert account codes to IDs
    const balances = await Promise.all(csvData.map(async (row) => {
      const account = await ChartOfAccount.findOne({
        company: companyId,
        code: row.account_code
      });

      if (!account) {
        const error = new Error(`ACCOUNT_NOT_FOUND: Account code ${row.account_code} not found`);
        error.code = 'ACCOUNT_NOT_FOUND';
        throw error;
      }

      return {
        account_id: account._id,
        account_code: row.account_code,
        entry_type: row.entry_type.toLowerCase(),
        amount: parseFloat(row.amount),
        description: row.description || ''
      };
    }));

    return this.import(companyId, { asOfDate, balances }, userId);
  }
}

module.exports = OpeningBalanceService;
