const DEFAULT_ACCOUNTS = require('../constants/chartOfAccounts').DEFAULT_ACCOUNTS;
const TaxAutomationService = require('./taxAutomationService');

// default dependencies
let JournalService = require('./journalService');
let InventoryService = require('./inventoryService');
let GoodsReceivedNote = require('../models/GoodsReceivedNote');

function __setDependencies(deps = {}) {
  if (deps.JournalService) JournalService = deps.JournalService;
  if (deps.InventoryService) InventoryService = deps.InventoryService;
  if (deps.GoodsReceivedNote) GoodsReceivedNote = deps.GoodsReceivedNote;
}

async function createPurchaseReturn(pr, opts = {}) {
  // pr: { _id, company, grnId, lines: [{ grnLine, product, qtyReturned, unitCost, originalTaxAmount }] }
  if (!pr || !pr.lines) throw new Error('invalid payload');

  // Validation: ensure not returning more than available if grn provided in opts
  if (opts.grn) {
    for (const line of pr.lines) {
      const gline = (opts.grn.lines || []).find(l => String(l._id) === String(line.grnLine));
      if (gline) {
        const available = (gline.qtyReceived || 0) - (gline.qtyReturned || 0);
        if (Number(line.qtyReturned) > available) throw new Error('returned qty exceeds available');
      }
    }
  }

  // Apply stock adjustments
  const adjusted = [];
  for (const l of pr.lines) {
    if (InventoryService && InventoryService.adjustLot) {
      const res = await InventoryService.adjustLot(l.grnLine || l.lotId || l.grnLine, { quantity: -Math.abs(l.qtyReturned) }, opts.session || null);
      adjusted.push(res);
    }
  }

  // Build reversal lines for TaxAutomationService
  // Each line: { netAmount, originalTaxAmount }
  const reversalLines = pr.lines.map(l => {
    const netAmount = Number(l.unitCost || 0) * Number(l.qtyReturned || 0);
    const originalTaxAmount = Number(l.originalTaxAmount || 0);
    return { netAmount, originalTaxAmount };
  });

  // Use TaxAutomationService for centralized tax reversal
  const companyId = pr.company || (opts.company || null);
  const purchaseReturnTax = await TaxAutomationService.reversePurchaseTax(companyId, reversalLines);

  // Build journal lines from TaxAutomationService output
  const userId = (opts.user && opts.user.id) || null;

  const atomicEntry = {
    date: new Date(),
    description: `Purchase Return ${pr._id}`,
    sourceType: 'purchase_return',
    sourceId: pr._id,
    sourceReference: pr._id,
    lines: purchaseReturnTax.journalLines
  };

  let je;
  if (JournalService.createEntriesAtomic) {
    const created = await JournalService.createEntriesAtomic(companyId, userId, [atomicEntry], { session: opts.session || null });
    je = created && created.length ? created[0] : null;
  } else {
    // Legacy callers/tests
    je = await JournalService.createEntry(companyId, userId, {
      date: new Date(),
      description: `Purchase Return ${pr._id}`,
      sourceType: 'purchase_return',
      sourceId: pr._id,
      sourceReference: pr._id,
      lines: purchaseReturnTax.journalLines,
      isAutoGenerated: true
    });
  }

  // mark pr confirmed
  pr.journalEntryId = je && (je._id || je.id) ? (je._id || je.id) : null;
  pr.status = 'confirmed';
  return pr;
}

module.exports = { createPurchaseReturn, __setDependencies };
