/**
 * Database Cleanup Script - Remove Duplicate Reversal Journal Entries v2
 * 
 * This script identifies duplicate reversals by extracting payment/receipt
 * references from entry descriptions, even when sourceIds differ.
 * 
 * Usage:
 *   node cleanup_duplicate_reversals_v2.js [--dry-run] [--company=COMPANY_ID]
 */

const mongoose = require('mongoose');
const args = process.argv.slice(2);

const isDryRun = args.includes('--dry-run');
const companyArg = args.find(arg => arg.startsWith('--company='));
const targetCompanyId = companyArg ? companyArg.split('=')[1] : null;

// Extract payment/receipt reference from description
function extractReference(description) {
  if (!description) return null;
  
  // Match patterns like:
  // "AP Payment PAY-2026-00003 Reversal..."
  // "Reversal: Supplier Payment - PAY#PAY-2026-00003"
  // "AR Receipt RCP-2026-00001 Reversal..."
  // "Reversal of JE-B63D-2026-00061" (journal entry reference)
  
  const patterns = [
    /PAY-202\d+-\d+/g,      // Payment references
    /RCP[A-Z]?-202\d+-\d+/g, // Receipt references  
    /INV-202\d+-\d+/g,      // Invoice references
    /JE-[A-Z0-9]+-202\d+-\d+/g, // Journal entry references
  ];
  
  for (const pattern of patterns) {
    const matches = description.match(pattern);
    if (matches && matches.length > 0) {
      return matches[0]; // Return first match
    }
  }
  
  return null;
}

// Connect to MongoDB
async function connectDB() {
  // Use Atlas connection from environment or default to Atlas
  const mongoUri = process.env.MONGODB_URI || 'mongodb+srv://DBuser:dbuserlily@stock.korqjvo.mongodb.net/stock-management';
  console.log(`Connecting to MongoDB Atlas...`);
  await mongoose.connect(mongoUri);
  console.log(`Connected to: ${mongoose.connection.host}\n`);
}

// Get JournalEntry model
function getJournalEntryModel() {
  const journalEntrySchema = new mongoose.Schema({
    entryNumber: String,
    date: Date,
    description: String,
    sourceType: String,
    sourceId: mongoose.Schema.Types.ObjectId,
    sourceReference: String,
    status: String,
    company: mongoose.Schema.Types.ObjectId,
    lines: [{
      accountCode: String,
      accountName: String,
      debit: mongoose.Schema.Types.Decimal128,
      credit: mongoose.Schema.Types.Decimal128,
      description: String
    }],
    isAutoGenerated: Boolean,
    createdAt: Date,
    createdBy: mongoose.Schema.Types.ObjectId
  }, { collection: 'journalentries' });
  
  return mongoose.model('JournalEntry', journalEntrySchema);
}

// Main analysis function
async function analyzeReversals() {
  try {
    await connectDB();
    const JournalEntry = getJournalEntryModel();
    
    console.log('='.repeat(80));
    console.log('ANALYZING REVERSAL ENTRIES');
    console.log('='.repeat(80));
    console.log(`Mode: ${isDryRun ? 'DRY RUN' : 'LIVE - WILL DELETE'}`);
    console.log('');
    
    // Find all reversal entries - case insensitive
    const query = {
      $and: [
        {
          $or: [
            { status: { $regex: /^posted$/i } },
            { status: 'Posted' },
            { status: 'posted' }
          ]
        },
        {
          $or: [
            { sourceType: 'ap_payment_reversal' },
            { sourceType: 'ar_receipt_reversal' },
            { sourceType: 'reversal' },
            { sourceType: { $regex: /reversal/i } },
            { description: { $regex: /reversal|reversed/i } }
          ]
        }
      ]
    };
    
    if (targetCompanyId) {
      query.company = new mongoose.Types.ObjectId(targetCompanyId);
    }
    
    const entries = await JournalEntry.find(query).sort({ createdAt: 1 });
    
    console.log(`Found ${entries.length} reversal entries\n`);
    
    // Debug: Show connection info
    console.log('Debug Info:');
    console.log(`  Database: ${mongoose.connection.name}`);
    console.log(`  Host: ${mongoose.connection.host}`);
    
    // List all collections
    const collections = await mongoose.connection.db.listCollections().toArray();
    console.log(`  Collections: ${collections.map(c => c.name).join(', ')}`);
    console.log('');
    
    // Debug: check what entries exist with just description filter
    const allByDesc = await JournalEntry.find({
      description: { $regex: /reversal|reversed/i }
    }).limit(10);
    
    console.log(`Debug: Found ${allByDesc.length} entries with 'reversal' in description`);
    
    if (allByDesc.length > 0) {
      console.log('\nSample entries:');
      for (const e of allByDesc.slice(0, 5)) {
        console.log(`  ${e.entryNumber}`);
        console.log(`    Status: "${e.status}"`);
        console.log(`    SourceType: "${e.sourceType}"`);
        console.log(`    Desc: ${e.description?.substring(0, 50)}`);
        console.log('');
      }
    } else {
      // Check if any journal entries exist at all
      const totalCount = await JournalEntry.countDocuments();
      console.log(`Total journal entries in DB: ${totalCount}`);
      
      if (totalCount > 0) {
        const sample = await JournalEntry.findOne();
        console.log(`Sample entry: ${sample.entryNumber}, status: ${sample.status}, sourceType: ${sample.sourceType}`);
      }
    }
    console.log('');
    
    // Group by extracted reference
    const groups = {};
    
    for (const entry of entries) {
      const ref = extractReference(entry.description);
      if (!ref) {
        console.log(`  ⚠ No reference found: ${entry.entryNumber} | ${entry.description}`);
        continue;
      }
      
      const key = `${entry.company}_${ref}`;
      if (!groups[key]) {
        groups[key] = [];
      }
      groups[key].push(entry);
    }
    
    // Find groups with more than 1 entry (duplicates)
    const duplicates = [];
    for (const [key, groupEntries] of Object.entries(groups)) {
      if (groupEntries.length > 1) {
        duplicates.push({ key, entries: groupEntries });
      }
    }
    
    if (duplicates.length === 0) {
      console.log('\n✓ No duplicate reversal entries found!');
      await mongoose.disconnect();
      return;
    }
    
    console.log(`\nFound ${duplicates.length} groups with duplicates:\n`);
    
    let totalToDelete = 0;
    const toDeleteIds = [];
    
    for (const { key, entries: groupEntries } of duplicates) {
      console.log('-'.repeat(80));
      console.log(`Reference: ${key.split('_')[1]}`);
      console.log(`Entries: ${groupEntries.length}`);
      console.log('');
      
      // Sort by priority: prefer proper sourceTypes, then earliest
      groupEntries.sort((a, b) => {
        const aIsProper = a.sourceType === 'ap_payment_reversal' || a.sourceType === 'ar_receipt_reversal';
        const bIsProper = b.sourceType === 'ap_payment_reversal' || b.sourceType === 'ar_receipt_reversal';
        
        if (aIsProper && !bIsProper) return -1;
        if (!aIsProper && bIsProper) return 1;
        
        return new Date(a.createdAt) - new Date(b.createdAt);
      });
      
      // Keep first, delete rest
      const keep = groupEntries[0];
      const toDelete = groupEntries.slice(1);
      
      console.log('  KEEP:');
      console.log(`    ${keep.entryNumber} | ${keep.description}`);
      console.log(`    Type: ${keep.sourceType} | Created: ${keep.createdAt.toLocaleString()}`);
      
      // Calculate bank impact
      let bankImpact = 0;
      for (const line of keep.lines) {
        if (line.accountCode === '1100') {
          bankImpact += parseFloat(line.debit?.toString() || 0);
          bankImpact -= parseFloat(line.credit?.toString() || 0);
        }
      }
      console.log(`    Bank Impact: ${bankImpact >= 0 ? '+' : ''}${bankImpact.toLocaleString()}`);
      console.log('');
      
      if (toDelete.length > 0) {
        console.log('  DELETE:');
        for (const entry of toDelete) {
          let entryImpact = 0;
          for (const line of entry.lines) {
            if (line.accountCode === '1100') {
              entryImpact += parseFloat(line.debit?.toString() || 0);
              entryImpact -= parseFloat(line.credit?.toString() || 0);
            }
          }
          
          console.log(`    ${entry.entryNumber} | ${entry.description}`);
          console.log(`    Type: ${entry.sourceType} | Created: ${entry.createdAt.toLocaleString()}`);
          console.log(`    Bank Impact: ${entryImpact >= 0 ? '+' : ''}${entryImpact.toLocaleString()}`);
          console.log('');
          
          toDeleteIds.push(entry._id);
          totalToDelete++;
        }
      }
    }
    
    console.log('='.repeat(80));
    console.log('SUMMARY');
    console.log('='.repeat(80));
    console.log(`Total duplicate groups: ${duplicates.length}`);
    console.log(`Total entries to delete: ${totalToDelete}`);
    console.log('');
    
    if (isDryRun) {
      console.log('✓ DRY RUN - No changes made');
      console.log('');
      console.log('To delete these entries, run without --dry-run');
    } else {
      console.log('⚠ LIVE MODE - Deleting entries...');
      console.log('');
      
      let deleted = 0;
      let failed = 0;
      
      for (const id of toDeleteIds) {
        try {
          const entry = await JournalEntry.findById(id);
          if (entry) {
            console.log(`  Deleting ${entry.entryNumber}...`);
            await JournalEntry.deleteOne({ _id: id });
            deleted++;
          }
        } catch (err) {
          console.error(`  Failed to delete ${id}: ${err.message}`);
          failed++;
        }
      }
      
      console.log('');
      console.log(`Deleted: ${deleted} | Failed: ${failed}`);
      console.log('');
      console.log('✓ Cleanup complete. Refresh your bank account page.');
    }
    
    await mongoose.disconnect();
    console.log('\nDisconnected from MongoDB');
    
  } catch (err) {
    console.error('\n❌ Error:', err.message);
    console.error(err.stack);
    process.exit(1);
  }
}

// Run
analyzeReversals();
