/**
 * Database Cleanup Script - Remove Duplicate Reversal Journal Entries
 * 
 * This script identifies and removes duplicate reversal entries that were
 * created due to the missing loading state protection on reversal buttons.
 * 
 * Usage:
 *   node cleanup_duplicate_reversals.js [--dry-run] [--company=COMPANY_ID]
 * 
 * Options:
 *   --dry-run     : Only show what would be deleted, don't actually delete
 *   --company=ID   : Only process entries for a specific company
 *   --help         : Show this help message
 */

const mongoose = require('mongoose');
const args = process.argv.slice(2);

// Parse command line arguments
const isDryRun = args.includes('--dry-run');
const companyArg = args.find(arg => arg.startsWith('--company='));
const targetCompanyId = companyArg ? companyArg.split('=')[1] : null;
const showHelp = args.includes('--help') || args.includes('-h');

if (showHelp) {
  console.log(`
Database Cleanup Script - Remove Duplicate Reversal Journal Entries

Usage:
  node cleanup_duplicate_reversals.js [--dry-run] [--company=COMPANY_ID]

Options:
  --dry-run      : Only show what would be deleted, don't actually delete
  --company=ID   : Only process entries for a specific company
  --help         : Show this help message

Examples:
  node cleanup_duplicate_reversals.js --dry-run
  node cleanup_duplicate_reversals.js --company=507f1f77bcf86cd799439011
  node cleanup_duplicate_reversals.js --dry-run --company=507f1f77bcf86cd799439011
`);
  process.exit(0);
}

// Connect to MongoDB
async function connectDB() {
  const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock_management';
  console.log(`Connecting to: ${mongoUri.replace(/\/\/[^:]+:/, '//***:***@')}`);
  
  await mongoose.connect(mongoUri, {
    useNewUrlParser: true,
    useUnifiedTopology: true
  });
  
  console.log('Connected to MongoDB\n');
}

// Get JournalEntry model
function getJournalEntryModel() {
  const journalEntrySchema = new mongoose.Schema({
    entryNumber: String,
    date: Date,
    description: String,
    sourceType: String,
    sourceId: mongoose.Schema.Types.ObjectId,
    sourceReference: String,
    status: String,
    company: mongoose.Schema.Types.ObjectId,
    lines: [{
      accountCode: String,
      accountName: String,
      debit: mongoose.Schema.Types.Decimal128,
      credit: mongoose.Schema.Types.Decimal128,
      description: String
    }],
    isAutoGenerated: Boolean,
    createdAt: Date,
    createdBy: mongoose.Schema.Types.ObjectId
  }, { collection: 'journalentries' });
  
  return mongoose.model('JournalEntry', journalEntrySchema);
}

// Find duplicate reversals - group by both sourceId AND sourceReference
async function findDuplicateReversals(JournalEntry, companyId = null) {
  const matchStage = {
    $match: {
      status: 'posted',
      $or: [
        { sourceType: 'ap_payment_reversal' },
        { sourceType: 'ar_receipt_reversal' },
        { sourceType: 'reversal' },
        { description: { $regex: /reversal|reversed/i } }
      ]
    }
  };
  
  if (companyId) {
    matchStage.$match.company = new mongoose.Types.ObjectId(companyId);
  }
  
  // First aggregation: group by sourceId
  const duplicatesBySourceId = await JournalEntry.aggregate([
    matchStage,
    {
      $group: {
        _id: {
          sourceId: '$sourceId',
          company: '$company'
        },
        entries: {
          $push: {
            _id: '$_id',
            entryNumber: '$entryNumber',
            description: '$description',
            sourceType: '$sourceType',
            sourceReference: '$sourceReference',
            date: '$date',
            createdAt: '$createdAt',
            lines: '$lines'
          }
        },
        count: { $sum: 1 }
      }
    },
    {
      $match: {
        count: { $gt: 1 },
        '_id.sourceId': { $ne: null }
      }
    }
  ]);
  
  // Second aggregation: group by sourceReference (for entries that reference same payment/receipt)
  const duplicatesByReference = await JournalEntry.aggregate([
    matchStage,
    {
      $match: { 
        sourceReference: { $ne: null, $ne: '' }
      }
    },
    {
      $group: {
        _id: {
          sourceReference: '$sourceReference',
          company: '$company'
        },
        entries: {
          $push: {
            _id: '$_id',
            entryNumber: '$entryNumber',
            description: '$description',
            sourceType: '$sourceType',
            sourceReference: '$sourceReference',
            sourceId: '$sourceId',
            date: '$date',
            createdAt: '$createdAt',
            lines: '$lines'
          }
        },
        count: { $sum: 1 }
      }
    },
    {
      $match: {
        count: { $gt: 1 }
      }
    }
  ]);
  
  // Combine and deduplicate results
  const allDuplicates = [...duplicatesBySourceId, ...duplicatesByReference];
  
  // Remove duplicate groups (same entries appearing in both aggregations)
  const seenEntryIds = new Set();
  const uniqueGroups = [];
  
  for (const group of allDuplicates) {
    const key = group.entries.map(e => e._id.toString()).sort().join(',');
    if (!seenEntryIds.has(key)) {
      seenEntryIds.add(key);
      uniqueGroups.push(group);
    }
  }
  
  // Sort by sourceReference or sourceId
  uniqueGroups.sort((a, b) => {
    const aRef = a._id.sourceReference || a._id.sourceId || '';
    const bRef = b._id.sourceReference || b._id.sourceId || '';
    return aRef.localeCompare(bRef);
  });
  
  return uniqueGroups;
}

// Calculate bank account impact
function calculateBankImpact(lines) {
  let debitTotal = 0;
  let creditTotal = 0;
  
  for (const line of lines || []) {
    if (line.accountCode === '1100') { // Cash at Bank
      if (line.debit) debitTotal += parseFloat(line.debit.toString());
      if (line.credit) creditTotal += parseFloat(line.credit.toString());
    }
  }
  
  return { debitTotal, creditTotal, netImpact: debitTotal - creditTotal };
}

// Determine which entry to keep
function determineEntryToKeep(entries) {
  // Priority:
  // 1. Keep entries with proper sourceType (ap_payment_reversal, ar_receipt_reversal)
  // 2. Keep the earliest created entry
  // 3. Keep entries with isAutoGenerated = true
  
  const prioritized = entries.map(e => {
    let priority = 0;
    
    // Higher priority for proper source types
    if (e.sourceType === 'ap_payment_reversal' || e.sourceType === 'ar_receipt_reversal') {
      priority += 100;
    }
    
    // Slight priority for auto-generated entries
    if (e.isAutoGenerated) {
      priority += 10;
    }
    
    // Prefer earlier entries (lower priority number for earlier dates)
    const age = new Date() - new Date(e.createdAt);
    priority -= age / (1000 * 60 * 60); // Age in hours as small adjustment
    
    return { ...e, priority };
  });
  
  // Sort by priority (highest first)
  prioritized.sort((a, b) => b.priority - a.priority);
  
  return {
    keep: prioritized[0],
    delete: prioritized.slice(1)
  };
}

// Main cleanup function
async function cleanup() {
  try {
    await connectDB();
    const JournalEntry = getJournalEntryModel();
    
    console.log('='.repeat(80));
    console.log('FINDING DUPLICATE REVERSAL ENTRIES');
    console.log('='.repeat(80));
    console.log(`Mode: ${isDryRun ? 'DRY RUN (no changes will be made)' : 'LIVE (entries will be deleted)'}`);
    if (targetCompanyId) {
      console.log(`Company Filter: ${targetCompanyId}`);
    }
    console.log('');
    
    // Find duplicates
    const duplicates = await findDuplicateReversals(JournalEntry, targetCompanyId);
    
    if (duplicates.length === 0) {
      console.log('✓ No duplicate reversal entries found!');
      process.exit(0);
    }
    
    console.log(`Found ${duplicates.length} groups of duplicate reversals:\n`);
    
    let totalDuplicates = 0;
    let totalImpact = 0;
    const toDelete = [];
    
    for (const group of duplicates) {
      const { _id, entries, count } = group;
      const { keep, delete: deleteEntries } = determineEntryToKeep(entries);
      
      console.log('-'.repeat(80));
      const groupKey = _id.sourceReference || _id.sourceId || 'unknown';
      console.log(`Group: ${groupKey}`);
      console.log(`Total entries: ${count} | Will delete: ${deleteEntries.length}`);
      console.log('');
      
      console.log('  KEEP:');
      const keepImpact = calculateBankImpact(keep.lines);
      console.log(`    ${keep.entryNumber} | ${keep.description}`);
      console.log(`    Created: ${new Date(keep.createdAt).toLocaleString()}`);
      console.log(`    Bank Impact: ${keepImpact.netImpact >= 0 ? '+' : ''}${keepImpact.netImpact.toLocaleString()}`);
      console.log('');
      
      if (deleteEntries.length > 0) {
        console.log('  DELETE:');
        for (const entry of deleteEntries) {
          const impact = calculateBankImpact(entry.lines);
          totalImpact += impact.netImpact;
          
          console.log(`    ${entry.entryNumber} | ${entry.description}`);
          console.log(`    Created: ${new Date(entry.createdAt).toLocaleString()}`);
          console.log(`    Bank Impact: ${impact.netImpact >= 0 ? '+' : ''}${impact.netImpact.toLocaleString()}`);
          
          toDelete.push(entry._id);
          totalDuplicates++;
        }
      }
      console.log('');
    }
    
    console.log('='.repeat(80));
    console.log('SUMMARY');
    console.log('='.repeat(80));
    console.log(`Total duplicate groups: ${duplicates.length}`);
    console.log(`Total entries to delete: ${totalDuplicates}`);
    console.log(`Net bank account correction: ${totalImpact >= 0 ? '+' : ''}${totalImpact.toLocaleString()}`);
    console.log('');
    
    if (isDryRun) {
      console.log('✓ DRY RUN completed. No entries were deleted.');
      console.log('');
      console.log('To actually delete these entries, run without --dry-run:');
      console.log(`  node cleanup_duplicate_reversals.js${targetCompanyId ? ` --company=${targetCompanyId}` : ''}`);
    } else {
      // LIVE MODE - Actually delete
      console.log('⚠ LIVE MODE - Deleting entries...');
      console.log('');
      
      let deletedCount = 0;
      let failedCount = 0;
      
      for (const entryId of toDelete) {
        try {
          const entry = await JournalEntry.findById(entryId);
          if (entry) {
            console.log(`  Deleting ${entry.entryNumber}...`);
            
            // Create a reverse entry to correct the balance
            // Actually, we should just delete - the balance will be corrected
            // when the bank account recalculates from remaining entries
            
            await JournalEntry.deleteOne({ _id: entryId });
            deletedCount++;
          }
        } catch (err) {
          console.error(`  Failed to delete ${entryId}: ${err.message}`);
          failedCount++;
        }
      }
      
      console.log('');
      console.log('='.repeat(80));
      console.log('CLEANUP COMPLETE');
      console.log('='.repeat(80));
      console.log(`Successfully deleted: ${deletedCount}`);
      console.log(`Failed: ${failedCount}`);
      console.log('');
      console.log('✓ Duplicate reversal entries have been removed.');
      console.log('  Refresh your bank account page to see the corrected balance.');
      console.log('');
      console.log('NOTE: The bank account balance will be automatically recalculated');
      console.log('      based on the remaining journal entries.');
    }
    
    await mongoose.disconnect();
    console.log('\nDisconnected from MongoDB');
    
  } catch (err) {
    console.error('\n❌ Error:', err.message);
    console.error(err.stack);
    process.exit(1);
  }
}

// Run the cleanup
cleanup();
