/**
 * Migration Script: Migrate existing Petty Cash and Fixed Assets to Journal Entries
 * This script creates journal entries for existing transactions that weren't recorded
 * 
 * Usage: node scripts/migrateExistingPettyCashAndDepreciation.js
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const JournalEntry = require('../models/JournalEntry');
const { PettyCashFloat, PettyCashExpense, PettyCashReplenishment } = require('../models/PettyCash');
const FixedAsset = require('../models/FixedAsset');
const JournalService = require('../services/journalService');
const { DEFAULT_ACCOUNTS } = require('../constants/chartOfAccounts');

// Load environment
dotenv.config();

// Connect to MongoDB
const connectDB = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock_management';
    await mongoose.connect(mongoUri);
    console.log('MongoDB Connected');
  } catch (error) {
    console.error('MongoDB connection error:', error.message);
    process.exit(1);
  }
};

async function migratePettyCashFloats(companyId, userId) {
  console.log('\n=== Migrating Petty Cash Floats ===');
  
  const floats = await PettyCashFloat.find({ company: companyId });
  
  for (const float of floats) {
    // Check if journal entry already exists for this float opening
    const existingEntry = await JournalEntry.findOne({
      company: companyId,
      sourceType: 'petty_cash',
      sourceId: float._id
    });
    
    if (existingEntry) {
      console.log(`  - Float ${float.name}: Already has journal entry, skipping`);
      continue;
    }
    
    if (float.openingBalance > 0) {
      try {
        await JournalService.createEntry(companyId, userId, {
          date: float.createdAt || new Date(),
          description: `Petty Cash Float Opening: ${float.name}`,
          sourceType: 'petty_cash',
          sourceId: float._id,
          sourceReference: 'Float Opening (Migrated)',
          lines: [
            JournalService.createDebitLine(
              DEFAULT_ACCOUNTS.pettyCash,
              float.openingBalance,
              `Opening petty cash float: ${float.name} (Migrated)`
            ),
            JournalService.createCreditLine(
              DEFAULT_ACCOUNTS.cashInHand,
              float.openingBalance,
              `Opening petty cash float: ${float.name} (Migrated)`
            )
          ],
          isAutoGenerated: true
        });
        console.log(`  - Float ${float.name}: Created opening journal entry`);
      } catch (error) {
        console.error(`  - Float ${float.name}: Error - ${error.message}`);
      }
    }
  }
}

async function migratePettyCashExpenses(companyId, userId) {
  console.log('\n=== Migrating Petty Cash Expenses ===');
  
  const expenses = await PettyCashExpense.find({ 
    company: companyId,
    status: { $in: ['approved', 'reimbursed'] }
  });
  
  for (const expense of expenses) {
    // Check if journal entry already exists
    const existingEntry = await JournalEntry.findOne({
      company: companyId,
      sourceType: 'petty_cash_expense',
      sourceId: expense._id
    });
    
    if (existingEntry) {
      console.log(`  - Expense ${expense.description}: Already has journal entry, skipping`);
      continue;
    }
    
    try {
      const expenseCategory = expense.category || 'otherExpenses';
      const expenseAccount = DEFAULT_ACCOUNTS[expenseCategory] || DEFAULT_ACCOUNTS.otherExpenses;
      
      await JournalService.createEntry(companyId, userId, {
        date: expense.date || expense.createdAt || new Date(),
        description: `Petty Cash Expense: ${expense.description}`,
        sourceType: 'petty_cash_expense',
        sourceId: expense._id,
        sourceReference: expense.description,
        lines: [
          JournalService.createDebitLine(
            expenseAccount,
            expense.amount,
            `Petty cash expense: ${expense.description} (Migrated)`
          ),
          JournalService.createCreditLine(
            DEFAULT_ACCOUNTS.pettyCash,
            expense.amount,
            `Petty cash expense: ${expense.description} (Migrated)`
          )
        ],
        isAutoGenerated: true
      });
      console.log(`  - Expense ${expense.description}: Created journal entry`);
    } catch (error) {
      console.error(`  - Expense ${expense.description}: Error - ${error.message}`);
    }
  }
}

async function migratePettyCashReplenishments(companyId, userId) {
  console.log('\n=== Migrating Petty Cash Replenishments ===');
  
  const replenishments = await PettyCashReplenishment.find({ 
    company: companyId,
    status: 'completed'
  });
  
  for (const repl of replenishments) {
    // Check if journal entry already exists
    const existingEntry = await JournalEntry.findOne({
      company: companyId,
      sourceType: 'petty_cash_replenishment',
      sourceId: repl._id
    });
    
    if (existingEntry) {
      console.log(`  - Replenishment ${repl.reason}: Already has journal entry, skipping`);
      continue;
    }
    
    const amount = repl.actualAmount || repl.amount;
    if (amount > 0) {
      try {
        await JournalService.createEntry(companyId, userId, {
          date: repl.completedAt || repl.createdAt || new Date(),
          description: `Petty Cash Replenishment: ${repl.reason}`,
          sourceType: 'petty_cash_replenishment',
          sourceId: repl._id,
          sourceReference: 'Replenishment (Migrated)',
          lines: [
            JournalService.createDebitLine(
              DEFAULT_ACCOUNTS.pettyCash,
              amount,
              `Petty cash replenishment: ${repl.reason} (Migrated)`
            ),
            JournalService.createCreditLine(
              DEFAULT_ACCOUNTS.cashInHand,
              amount,
              `Petty cash replenishment: ${repl.reason} (Migrated)`
            )
          ],
          isAutoGenerated: true
        });
        console.log(`  - Replenishment ${repl.reason}: Created journal entry`);
      } catch (error) {
        console.error(`  - Replenishment ${repl.reason}: Error - ${error.message}`);
      }
    }
  }
}

async function migrateDepreciation(companyId, userId) {
  console.log('\n=== Migrating Fixed Asset Depreciation ===');
  
  const assets = await FixedAsset.find({ 
    company: companyId,
    status: { $in: ['active', 'in_use'] }
  });
  
  for (const asset of assets) {
    // Skip assets without useful life
    if (!asset.usefulLifeYears || asset.usefulLifeYears <= 0) {
      console.log(`  - Asset ${asset.name}: No useful life, skipping`);
      continue;
    }
    
    // Calculate accumulated depreciation based on purchase date
    const now = new Date();
    const purchaseDate = new Date(asset.purchaseDate);
    const monthsElapsed = (now.getFullYear() - purchaseDate.getFullYear()) * 12 + 
                          (now.getMonth() - purchaseDate.getMonth());
    
    if (monthsElapsed <= 0) {
      console.log(`  - Asset ${asset.name}: Not yet due for depreciation, skipping`);
      continue;
    }
    
    // Get monthly depreciation
    const annualDepreciation = asset.annualDepreciation || 0;
    const monthlyDepreciation = annualDepreciation / 12;
    
    if (monthlyDepreciation <= 0) {
      console.log(`  - Asset ${asset.name}: No depreciation calculated, skipping`);
      continue;
    }
    
    // Create depreciation entries for each month (up to current month or useful life)
    const monthsToDepreciate = Math.min(monthsElapsed, asset.usefulLifeYears * 12);
    const existingEntries = await JournalEntry.countDocuments({
      company: companyId,
      sourceType: 'depreciation',
      sourceId: asset._id
    });
    
    if (existingEntries >= monthsToDepreciate) {
      console.log(`  - Asset ${asset.name}: Depreciation already migrated, skipping`);
      continue;
    }
    
    // Create depreciation entries for missing months
    const currentMonth = new Date(purchaseDate);
    currentMonth.setMonth(currentMonth.getMonth() + existingEntries);
    
    for (let i = existingEntries; i < monthsToDepreciate; i++) {
      const periodLabel = `${currentMonth.getFullYear()}-${String(currentMonth.getMonth() + 1).padStart(2, '0')}`;
      
      try {
        await JournalService.createEntry(companyId, userId, {
          date: currentMonth,
          description: `Depreciation - ${asset.name} - ${periodLabel}`,
          sourceType: 'depreciation',
          sourceId: asset._id,
          sourceReference: asset.assetCode,
          lines: [
            JournalService.createDebitLine(
              DEFAULT_ACCOUNTS.depreciation,
              monthlyDepreciation,
              `Depreciation: ${asset.name} (Migrated)`
            ),
            JournalService.createCreditLine(
              DEFAULT_ACCOUNTS.accumulatedDepreciation,
              monthlyDepreciation,
              `Accumulated depreciation: ${asset.name} (Migrated)`
            )
          ],
          isAutoGenerated: true
        });
        console.log(`  - Asset ${asset.name}: Created depreciation entry for ${periodLabel}`);
      } catch (error) {
        console.error(`  - Asset ${asset.name}: Error - ${error.message}`);
      }
      
      // Move to next month
      currentMonth.setMonth(currentMonth.getMonth() + 1);
    }
  }
}

async function main() {
  try {
    await connectDB();
    
    // Get all companies
    const Company = require('../models/Company');
    const companies = await Company.find({});
    
    if (companies.length === 0) {
      console.log('No companies found');
      process.exit(0);
    }
    
    // Use first company for demo, or loop through all
    for (const company of companies) {
      console.log(`\n===== Processing Company: ${company.name} (${company._id}) =====`);
      
      // Use a system user ID (you may need to create or use an existing admin)
      const userId = company.createdBy || '000000000000000000000000';
      
      await migratePettyCashFloats(company._id, userId);
      await migratePettyCashExpenses(company._id, userId);
      await migratePettyCashReplenishments(company._id, userId);
      await migrateDepreciation(company._id, userId);
    }
    
    console.log('\n=== Migration Complete ===');
    
    // Print summary
    const totalEntries = await JournalEntry.countDocuments({});
    console.log(`Total journal entries in database: ${totalEntries}`);
    
    process.exit(0);
  } catch (error) {
    console.error('Migration failed:', error);
    process.exit(1);
  }
}

main();
