/**
 * Migration Script: Add Tax Liabilities (RSSB, PAYE, Income Tax)
 * User provided amounts:
 * - RSSB Payable: RWF 31,650
 * - PAYE Payable: RWF 300,500
 * 
 * Usage: node scripts/migrateTaxLiabilities.js
 */

const mongoose = require('mongoose');
const dotenv = require('dotenv');
const JournalEntry = require('../models/JournalEntry');
const Company = require('../models/Company');
const JournalService = require('../services/journalService');

dotenv.config();

// Account codes from chart of accounts
const ACCOUNTS = {
  payrollExpenses: '5410',
  rssbPayable: '2300',
  payePayable: '2200',
  incomeTaxPayable: '2400'
};

const connectDB = async () => {
  try {
    const mongoUri = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock_management';
    await mongoose.connect(mongoUri);
    console.log('MongoDB Connected');
  } catch (error) {
    console.error('MongoDB connection error:', error.message);
    process.exit(1);
  }
};

async function migrateTaxLiabilities() {
  console.log('\n=== Migrating Tax Liabilities ===\n');
  
  const companies = await Company.find({});
  
  for (const company of companies) {
    console.log(`Company: ${company.name}`);
    const userId = company.createdBy || '000000000000000000000000';
    
    // RSSB Payable - RWF 31,650
    const rssbAmount = 31650;
    const rssbExists = await JournalEntry.findOne({
      company: company._id,
      sourceReference: 'RSSB Payable Opening'
    });
    
    if (!rssbExists && rssbAmount > 0) {
      try {
        await JournalService.createEntry(company._id, userId, {
          date: new Date(),
          description: 'Opening Balance - RSSB Payable',
          sourceType: 'opening_balance',
          sourceReference: 'RSSB Payable Opening',
          lines: [
            JournalService.createDebitLine(
              ACCOUNTS.payrollExpenses,
              rssbAmount,
              'Opening RSSB liability'
            ),
            JournalService.createCreditLine(
              ACCOUNTS.rssbPayable,
              rssbAmount,
              'Opening RSSB payable'
            )
          ],
          isAutoGenerated: true,
          notes: 'Migration: RSSB liability from payroll'
        });
        console.log(`  ✅ Created: RSSB Payable (RWF ${rssbAmount.toLocaleString()})`);
      } catch (error) {
        console.log(`  ❌ Error: RSSB - ${error.message}`);
      }
    } else {
      console.log(`  ⏭️  Skipped: RSSB (already exists)`);
    }
    
    // PAYE Payable - RWF 300,500
    const payeAmount = 300500;
    const payeExists = await JournalEntry.findOne({
      company: company._id,
      sourceReference: 'PAYE Payable Opening'
    });
    
    if (!payeExists && payeAmount > 0) {
      try {
        await JournalService.createEntry(company._id, userId, {
          date: new Date(),
          description: 'Opening Balance - PAYE Payable',
          sourceType: 'opening_balance',
          sourceReference: 'PAYE Payable Opening',
          lines: [
            JournalService.createDebitLine(
              ACCOUNTS.payrollExpenses,
              payeAmount,
              'Opening PAYE liability'
            ),
            JournalService.createCreditLine(
              ACCOUNTS.payePayable,
              payeAmount,
              'Opening PAYE payable'
            )
          ],
          isAutoGenerated: true,
          notes: 'Migration: PAYE liability from payroll'
        });
        console.log(`  ✅ Created: PAYE Payable (RWF ${payeAmount.toLocaleString()})`);
      } catch (error) {
        console.log(`  ❌ Error: PAYE - ${error.message}`);
      }
    } else {
      console.log(`  ⏭️  Skipped: PAYE (already exists)`);
    }
    
    console.log('');
  }
  
  const total = await JournalEntry.countDocuments({});
  console.log(`Total journal entries: ${total}`);
}

async function main() {
  try {
    await connectDB();
    await migrateTaxLiabilities();
    process.exit(0);
  } catch (error) {
    console.error('Migration failed:', error);
    process.exit(1);
  }
}

main();
