/**
 * Seed Cash Flow Data — IAS 7 Compliant
 *
 * Creates journal entries with cash account lines (1000, 1100, 1200)
 * classified by sourceType to populate all three cash flow sections:
 *
 *   Operating:  ar_receipt, ap_payment, expense, payroll_run, tax_settlement
 *   Investing:  asset_purchase, asset_disposal
 *   Financing:  liability_drawdown, liability_repayment
 *
 * Usage: node scripts/seedCashFlow.js <companyId> <userId>
 */
const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock-management';
const D = (v) => mongoose.Types.Decimal128.fromString(String(v));

async function seed() {
  const args = process.argv.slice(2);
  const companyId = args[0];
  const userId = args[1];

  if (!companyId) {
    console.error('Usage: node scripts/seedCashFlow.js <companyId> <userId>');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const JournalEntry = require('../models/JournalEntry');
  const AccountBalance = require('../models/AccountBalance');

  const deleted = await JournalEntry.deleteMany({
    company: companyId,
    entryNumber: { $regex: /^SEED-CF-/ }
  }).setOptions({ skipTenant: true });
  console.log(`Cleared ${deleted.deletedCount} existing seed CF entries`);

  const entries = [];
  let seq = 0;
  const ref = (prefix) => { seq++; return `SEED-CF-${String(seq).padStart(4, '0')}`; };

  // ═══════════════════════════════════════════════════════════════════
  // OPERATING INFLOWS — Customer receipts (ar_receipt)
  // ═══════════════════════════════════════════════════════════════════
  for (const month of [
    { label: 'Jan', date: '2026-01-20', amount: 800000 },
    { label: 'Feb', date: '2026-02-20', amount: 950000 },
    { label: 'Mar', date: '2026-03-20', amount: 1100000 }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('CF'),
      date: new Date(month.date),
      description: `Customer receipt — ${month.label}`,
      sourceType: 'ar_receipt', sourceId: `seed_cf_ar_${month.label}`, sourceReference: `CF-AR-${month.label}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Customer payment', debit: D(month.amount), credit: D(0) },
        { accountCode: '1300', accountName: 'Accounts Receivable', description: 'AR collection', debit: D(0), credit: D(month.amount) }
      ],
      totalDebit: D(month.amount), totalCredit: D(month.amount), debitTotal: D(month.amount), creditTotal: D(month.amount)
    });
  }

  // ═══════════════════════════════════════════════════════════════════
  // OPERATING OUTFLOWS — Supplier payments (ap_payment)
  // ═══════════════════════════════════════════════════════════════════
  for (const month of [
    { label: 'Jan', date: '2026-01-25', amount: 400000 },
    { label: 'Feb', date: '2026-02-25', amount: 350000 },
    { label: 'Mar', date: '2026-03-25', amount: 500000 }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('CF'),
      date: new Date(month.date),
      description: `Supplier payment — ${month.label}`,
      sourceType: 'ap_payment', sourceId: `seed_cf_ap_${month.label}`, sourceReference: `CF-AP-${month.label}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '2000', accountName: 'Accounts Payable', description: 'Supplier payment', debit: D(month.amount), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Cash paid', debit: D(0), credit: D(month.amount) }
      ],
      totalDebit: D(month.amount), totalCredit: D(month.amount), debitTotal: D(month.amount), creditTotal: D(month.amount)
    });
  }

  // OPERATING OUTFLOWS — Expenses (expense)
  for (const month of [
    { label: 'Jan', date: '2026-01-28', amount: 78000 },
    { label: 'Feb', date: '2026-02-28', amount: 82000 },
    { label: 'Mar', date: '2026-03-28', amount: 75000 }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('CF'),
      date: new Date(month.date),
      description: `Operating expenses — ${month.label}`,
      sourceType: 'expense', sourceId: `seed_cf_exp_${month.label}`, sourceReference: `CF-EXP-${month.label}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5500', accountName: 'Rent', description: 'Office rent', debit: D(month.amount), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Rent payment', debit: D(0), credit: D(month.amount) }
      ],
      totalDebit: D(month.amount), totalCredit: D(month.amount), debitTotal: D(month.amount), creditTotal: D(month.amount)
    });
  }

  // OPERATING OUTFLOWS — Payroll (payroll_run)
  for (const month of [
    { label: 'Jan', date: '2026-01-31', amount: 160000 },
    { label: 'Feb', date: '2026-02-28', amount: 160000 },
    { label: 'Mar', date: '2026-03-31', amount: 160000 }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('CF'),
      date: new Date(month.date),
      description: `Net salary payment — ${month.label}`,
      sourceType: 'payroll_run', sourceId: `seed_cf_pay_${month.label}`, sourceReference: `CF-PAY-${month.label}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Net salary', debit: D(month.amount), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Salary payment', debit: D(0), credit: D(month.amount) }
      ],
      totalDebit: D(month.amount), totalCredit: D(month.amount), debitTotal: D(month.amount), creditTotal: D(month.amount)
    });
  }

  // OPERATING OUTFLOWS — Tax settlement (tax_settlement)
  entries.push({
    company: companyId, entryNumber: ref('CF'),
    date: new Date('2026-03-31'),
    description: 'VAT settlement — Q1',
    sourceType: 'tax_settlement', sourceId: 'seed_cf_tax_001', sourceReference: 'CF-TAX-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2220', accountName: 'VAT Output', description: 'VAT payable', debit: D(60000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'VAT payment', debit: D(0), credit: D(60000) }
    ],
    totalDebit: D(60000), totalCredit: D(60000), debitTotal: D(60000), creditTotal: D(60000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // INVESTING OUTFLOWS — Asset purchase (asset_purchase)
  // ═══════════════════════════════════════════════════════════════════
  entries.push({
    company: companyId, entryNumber: ref('CF'),
    date: new Date('2026-02-01'),
    description: 'Purchase — New delivery van',
    sourceType: 'asset_purchase', sourceId: 'seed_cf_inv_001', sourceReference: 'CF-INV-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1720', accountName: 'Vehicles', description: 'Vehicle purchase', debit: D(1500000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(1500000) }
    ],
    totalDebit: D(1500000), totalCredit: D(1500000), debitTotal: D(1500000), creditTotal: D(1500000)
  });

  // INVESTING INFLOWS — Asset disposal (asset_disposal)
  entries.push({
    company: companyId, entryNumber: ref('CF'),
    date: new Date('2026-03-10'),
    description: 'Sale — Old vehicle',
    sourceType: 'asset_disposal', sourceId: 'seed_cf_inv_002', sourceReference: 'CF-INV-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Sale proceeds', debit: D(400000), credit: D(0) },
      { accountCode: '1720', accountName: 'Vehicles', description: 'Asset removal', debit: D(0), credit: D(250000) },
      { accountCode: '4250', accountName: 'Gain on Asset Disposal', description: 'Gain', debit: D(0), credit: D(150000) }
    ],
    totalDebit: D(400000), totalCredit: D(400000), debitTotal: D(400000), creditTotal: D(400000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // FINANCING INFLOWS — Loan drawdown (liability_drawdown)
  // ═══════════════════════════════════════════════════════════════════
  entries.push({
    company: companyId, entryNumber: ref('CF'),
    date: new Date('2026-01-10'),
    description: 'Short-term loan — Bank overdraft',
    sourceType: 'liability_drawdown', sourceId: 'seed_cf_fin_001', sourceReference: 'CF-FIN-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Loan received', debit: D(500000), credit: D(0) },
      { accountCode: '2700', accountName: 'Short Term Loans', description: 'Loan liability', debit: D(0), credit: D(500000) }
    ],
    totalDebit: D(500000), totalCredit: D(500000), debitTotal: D(500000), creditTotal: D(500000)
  });

  // FINANCING OUTFLOWS — Loan repayment (liability_repayment)
  entries.push({
    company: companyId, entryNumber: ref('CF'),
    date: new Date('2026-03-15'),
    description: 'Loan repayment — Partial',
    sourceType: 'liability_repayment', sourceId: 'seed_cf_fin_002', sourceReference: 'CF-FIN-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2700', accountName: 'Short Term Loans', description: 'Loan repayment', debit: D(200000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Cash paid', debit: D(0), credit: D(200000) }
    ],
    totalDebit: D(200000), totalCredit: D(200000), debitTotal: D(200000), creditTotal: D(200000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // Insert
  // ═══════════════════════════════════════════════════════════════════
  console.log(`\nInserting ${entries.length} cash flow journal entries...`);

  const inserted = await JournalEntry.insertMany(entries, { ordered: false }).catch(err => {
    if (err.insertedDocs && err.insertedDocs.length > 0) {
      console.log(`Inserted ${err.insertedDocs.length} entries (some duplicates skipped)`);
      return err.insertedDocs;
    }
    throw err;
  });

  console.log(`Successfully inserted ${inserted.length} journal entries`);

  // Rebuild AccountBalance
  const affectedCodes = new Set();
  inserted.forEach(e => e.lines.forEach(l => affectedCodes.add(l.accountCode)));

  for (const code of affectedCodes) {
    await AccountBalance.findOneAndUpdate(
      { company: companyId, accountCode: code },
      { $setOnInsert: { company: companyId, accountCode: code, debit: 0, credit: 0 } },
      { upsert: true, setDefaultsOnInsert: true }
    );
  }

  const allEntries = await JournalEntry.find({ company: companyId, status: 'posted' }).setOptions({ skipTenant: true }).lean();
  await AccountBalance.updateMany({ company: companyId }, { $set: { debit: 0, credit: 0 } }).setOptions({ skipTenant: true });
  for (const entry of allEntries) {
    for (const line of entry.lines) {
      const debit = parseFloat(line.debit?.toString() || '0');
      const credit = parseFloat(line.credit?.toString() || '0');
      if (debit > 0 || credit > 0) {
        await AccountBalance.adjust(companyId, line.accountCode, debit, credit);
      }
    }
  }

  // Summary
  const summary = {};
  inserted.forEach(e => { summary[e.sourceType] = (summary[e.sourceType] || 0) + 1; });
  console.log('\n=== Entry Summary ===');
  Object.entries(summary).sort().forEach(([type, count]) => console.log(`  ${type}: ${count}`));

  console.log('\nCash Flow seed complete!');
  process.exit(0);
}

seed().catch(e => { console.error('Error:', e.message, e.stack); process.exit(1); });
