/**
 * Seed Tax Transaction Data
 * Creates realistic journal entries covering all 13 tax sources
 * so the liability report, dashboard, and health check display real data.
 *
 * Usage: node scripts/seedTaxData.js <companyId> <userId> [--clear]
 */
const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock-management';
const D = (v) => mongoose.Types.Decimal128.fromString(String(v));

async function seed() {
  const args = process.argv.slice(2);
  const force = args.includes('--clear');
  const filteredArgs = args.filter(a => a !== '--clear');
  const companyId = filteredArgs[0];
  const userId = filteredArgs[1];

  if (!companyId) {
    console.error('Usage: node seedTaxData.js <companyId> <userId> [--clear]');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const JournalEntry = require('../models/JournalEntry');

  // Clear existing tax-related journal entries if requested
  if (force) {
    const deleted = await JournalEntry.deleteMany({
      company: companyId,
      sourceType: { $in: ['invoice', 'purchase_order', 'expense', 'petty_cash_expense', 'credit_note', 'purchase_return', 'payroll_run', 'vat_settlement', 'paye_settlement', 'rssb_settlement', 'tax_settlement', 'payroll_salary', 'payroll_tax'] }
    }).setOptions({ skipTenant: true });
    console.log('Cleared', deleted.deletedCount, 'existing tax journal entries');
  }

  const entries = [];
  let entryNum = 1000;
  const nextRef = () => { entryNum++; return `JE-2026-${entryNum}`; };

  // ═══════════════════════════════════════════════════════════════════
  // JANUARY 2026 — Full month of transactions
  // ═══════════════════════════════════════════════════════════════════

  // ── SOURCE 1: Purchases (Input VAT on GRN) ──────────────────────
  // GRN #1: 500,000 RWF goods + 18% VAT = 590,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-05'),
    description: 'Purchase - GRN-2026-001 - Supplier ABC Ltd',
    sourceType: 'purchase_order', sourceId: 'grn_001', sourceReference: 'GRN-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1400', accountName: 'Inventory', description: 'Goods received', debit: D(500000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on purchases', debit: D(90000), credit: D(0) },
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Payable for goods received', debit: D(0), credit: D(590000) }
    ],
    totalDebit: D(590000), totalCredit: D(590000), debitTotal: D(590000), creditTotal: D(590000)
  });

  // GRN #2: 300,000 RWF + 18% VAT = 354,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-12'),
    description: 'Purchase - GRN-2026-002 - Supplier XYZ Trading',
    sourceType: 'purchase_order', sourceId: 'grn_002', sourceReference: 'GRN-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1400', accountName: 'Inventory', description: 'Goods received', debit: D(300000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on purchases', debit: D(54000), credit: D(0) },
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Payable for goods received', debit: D(0), credit: D(354000) }
    ],
    totalDebit: D(354000), totalCredit: D(354000), debitTotal: D(354000), creditTotal: D(354000)
  });

  // ── SOURCE 3: Sales Invoices (Output VAT) ───────────────────────
  // Invoice #1: 800,000 RWF revenue + 18% VAT = 944,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-08'),
    description: 'Invoice INV-2026-001 - Customer Alpha Ltd',
    sourceType: 'invoice', sourceId: 'inv_001', sourceReference: 'INV-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice amount due', debit: D(944000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Revenue from sales', debit: D(0), credit: D(800000) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'Output VAT on sales', debit: D(0), credit: D(144000) }
    ],
    totalDebit: D(944000), totalCredit: D(944000), debitTotal: D(944000), creditTotal: D(944000)
  });

  // Invoice #2: 1,200,000 RWF revenue + 18% VAT = 1,416,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-15'),
    description: 'Invoice INV-2026-002 - Customer Beta Corp',
    sourceType: 'invoice', sourceId: 'inv_002', sourceReference: 'INV-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice amount due', debit: D(1416000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Revenue from sales', debit: D(0), credit: D(1200000) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'Output VAT on sales', debit: D(0), credit: D(216000) }
    ],
    totalDebit: D(1416000), totalCredit: D(1416000), debitTotal: D(1416000), creditTotal: D(1416000)
  });

  // Invoice #3: 600,000 RWF revenue + 18% VAT = 708,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-22'),
    description: 'Invoice INV-2026-003 - Customer Gamma Ltd',
    sourceType: 'invoice', sourceId: 'inv_003', sourceReference: 'INV-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice amount due', debit: D(708000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Revenue from sales', debit: D(0), credit: D(600000) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'Output VAT on sales', debit: D(0), credit: D(108000) }
    ],
    totalDebit: D(708000), totalCredit: D(708000), debitTotal: D(708000), creditTotal: D(708000)
  });

  // ── SOURCE 6: Expenses (Input VAT) ──────────────────────────────
  // Expense #1: Rent 100,000 + VAT 18,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-03'),
    description: 'Expense - Rent January - EXP-2026-001',
    sourceType: 'expense', sourceId: 'exp_001', sourceReference: 'EXP-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5500', accountName: 'Rent', description: 'Rent expense', debit: D(100000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on expense', debit: D(18000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank payment for expense', debit: D(0), credit: D(118000) }
    ],
    totalDebit: D(118000), totalCredit: D(118000), debitTotal: D(118000), creditTotal: D(118000)
  });

  // Expense #2: Utilities 50,000 + VAT 9,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-10'),
    description: 'Expense - Utilities January - EXP-2026-002',
    sourceType: 'expense', sourceId: 'exp_002', sourceReference: 'EXP-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5600', accountName: 'Utilities', description: 'Utilities expense', debit: D(50000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on expense', debit: D(9000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank payment for expense', debit: D(0), credit: D(59000) }
    ],
    totalDebit: D(59000), totalCredit: D(59000), debitTotal: D(59000), creditTotal: D(59000)
  });

  // Expense #3: Transport 30,000 + VAT 5,400
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-18'),
    description: 'Expense - Transport January - EXP-2026-003',
    sourceType: 'expense', sourceId: 'exp_003', sourceReference: 'EXP-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5700', accountName: 'Transport & Delivery', description: 'Transport expense', debit: D(30000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on expense', debit: D(5400), credit: D(0) },
      { accountCode: '1050', accountName: 'Petty Cash', description: 'Petty cash payment', debit: D(0), credit: D(35400) }
    ],
    totalDebit: D(35400), totalCredit: D(35400), debitTotal: D(35400), creditTotal: D(35400)
  });

  // ── SOURCE 2: Purchase Return (Input VAT reversed) ──────────────
  // Return of 100,000 + VAT 18,000 from GRN #1
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-20'),
    description: 'Purchase Return PR-2026-001 - Supplier ABC Ltd',
    sourceType: 'purchase_return', sourceId: 'pr_001', sourceReference: 'PR-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Reversal of payable', debit: D(118000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Reversal of inventory', debit: D(0), credit: D(100000) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Reversal of input VAT', debit: D(0), credit: D(18000) }
    ],
    totalDebit: D(118000), totalCredit: D(118000), debitTotal: D(118000), creditTotal: D(118000)
  });

  // ── SOURCE 4: Credit Note (Output VAT reversed) ─────────────────
  // CN for 200,000 + VAT 36,000 against Invoice #1
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-25'),
    description: 'Credit Note CN-2026-001 - Customer Alpha Ltd - Ref INV-2026-001',
    sourceType: 'credit_note', sourceId: 'cn_001', sourceReference: 'CN-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Reversal of revenue', debit: D(200000), credit: D(0) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'Reversal of output VAT', debit: D(36000), credit: D(0) },
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Reduction of receivable', debit: D(0), credit: D(236000) }
    ],
    totalDebit: D(236000), totalCredit: D(236000), debitTotal: D(236000), creditTotal: D(236000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // FEBRUARY 2026 — Second month
  // ═══════════════════════════════════════════════════════════════════

  // More purchases
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-03'),
    description: 'Purchase - GRN-2026-003 - Supplier ABC Ltd',
    sourceType: 'purchase_order', sourceId: 'grn_003', sourceReference: 'GRN-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1400', accountName: 'Inventory', description: 'Goods received', debit: D(450000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on purchases', debit: D(81000), credit: D(0) },
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Payable for goods received', debit: D(0), credit: D(531000) }
    ],
    totalDebit: D(531000), totalCredit: D(531000), debitTotal: D(531000), creditTotal: D(531000)
  });

  // More sales
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-05'),
    description: 'Invoice INV-2026-004 - Customer Delta Corp',
    sourceType: 'invoice', sourceId: 'inv_004', sourceReference: 'INV-2026-004',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice amount due', debit: D(1180000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Revenue from sales', debit: D(0), credit: D(1000000) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'Output VAT on sales', debit: D(0), credit: D(180000) }
    ],
    totalDebit: D(1180000), totalCredit: D(1180000), debitTotal: D(1180000), creditTotal: D(1180000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-12'),
    description: 'Invoice INV-2026-005 - Customer Epsilon Ltd',
    sourceType: 'invoice', sourceId: 'inv_005', sourceReference: 'INV-2026-005',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice amount due', debit: D(885000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Revenue from sales', debit: D(0), credit: D(750000) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'Output VAT on sales', debit: D(0), credit: D(135000) }
    ],
    totalDebit: D(885000), totalCredit: D(885000), debitTotal: D(885000), creditTotal: D(885000)
  });

  // More expenses
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-03'),
    description: 'Expense - Rent February - EXP-2026-004',
    sourceType: 'expense', sourceId: 'exp_004', sourceReference: 'EXP-2026-004',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5500', accountName: 'Rent', description: 'Rent expense', debit: D(100000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on expense', debit: D(18000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank payment', debit: D(0), credit: D(118000) }
    ],
    totalDebit: D(118000), totalCredit: D(118000), debitTotal: D(118000), creditTotal: D(118000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-08'),
    description: 'Expense - Utilities February - EXP-2026-005',
    sourceType: 'expense', sourceId: 'exp_005', sourceReference: 'EXP-2026-005',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5600', accountName: 'Utilities', description: 'Utilities expense', debit: D(45000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on expense', debit: D(8100), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank payment', debit: D(0), credit: D(53100) }
    ],
    totalDebit: D(53100), totalCredit: D(53100), debitTotal: D(53100), creditTotal: D(53100)
  });

  // ── SOURCE 7: Petty Cash Expense ─────────────────────────────────
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-10'),
    description: 'Petty Cash Expense - Office supplies',
    sourceType: 'petty_cash_expense', sourceId: 'pce_001', sourceReference: 'PCE-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6100', accountName: 'Other Expenses', description: 'Office supplies', debit: D(20000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'Input VAT on petty cash expense', debit: D(3600), credit: D(0) },
      { accountCode: '1050', accountName: 'Petty Cash', description: 'Petty cash payment', debit: D(0), credit: D(23600) }
    ],
    totalDebit: D(23600), totalCredit: D(23600), debitTotal: D(23600), creditTotal: D(23600)
  });

  // ═══════════════════════════════════════════════════════════════════
  // SOURCE 8-10: Payroll (PAYE + RSSB) — January & February
  // ═══════════════════════════════════════════════════════════════════

  // Employee 1: Gross 300,000 → PAYE 54,000 + RSSB Employee 18,900 = 72,900 deductions
  // Net pay = 227,100
  // RSSB Employer = 24,900
  // Jan salary
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Salary Payment - Jean Baptiste - January 2026',
    sourceType: 'payroll_salary', sourceId: 'payroll_jan_001', sourceReference: 'PAY-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Gross salary', debit: D(300000), credit: D(0) },
      { accountCode: '2230', accountName: 'PAYE Tax Payable', description: 'PAYE withheld', debit: D(0), credit: D(54000) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'RSSB employee', debit: D(0), credit: D(18900) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Net salary', debit: D(0), credit: D(227100) }
    ],
    totalDebit: D(300000), totalCredit: D(300000), debitTotal: D(300000), creditTotal: D(300000)
  });

  // Jan employer contribution
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Employer Contributions - January 2026',
    sourceType: 'payroll_run', sourceId: 'payroll_jan_001_erc', sourceReference: 'PAY-2026-001-ER',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'Employer RSSB contributions', debit: D(24900), credit: D(0) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'Employer RSSB payable', debit: D(0), credit: D(24900) }
    ],
    totalDebit: D(24900), totalCredit: D(24900), debitTotal: D(24900), creditTotal: D(24900)
  });

  // Employee 2: Gross 200,000 → PAYE 20,000 + RSSB Employee 12,600 = 32,600
  // Net pay = 167,400
  // RSSB Employer = 16,600
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Salary Payment - Marie Claire - January 2026',
    sourceType: 'payroll_salary', sourceId: 'payroll_jan_002', sourceReference: 'PAY-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Gross salary', debit: D(200000), credit: D(0) },
      { accountCode: '2230', accountName: 'PAYE Tax Payable', description: 'PAYE withheld', debit: D(0), credit: D(20000) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'RSSB employee', debit: D(0), credit: D(12600) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Net salary', debit: D(0), credit: D(167400) }
    ],
    totalDebit: D(200000), totalCredit: D(200000), debitTotal: D(200000), creditTotal: D(200000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Employer Contributions - Marie Claire - January 2026',
    sourceType: 'payroll_run', sourceId: 'payroll_jan_002_erc', sourceReference: 'PAY-2026-002-ER',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'Employer RSSB contributions', debit: D(16600), credit: D(0) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'Employer RSSB payable', debit: D(0), credit: D(16600) }
    ],
    totalDebit: D(16600), totalCredit: D(16600), debitTotal: D(16600), creditTotal: D(16600)
  });

  // Feb payroll (same employees)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Salary Payment - Jean Baptiste - February 2026',
    sourceType: 'payroll_salary', sourceId: 'payroll_feb_001', sourceReference: 'PAY-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Gross salary', debit: D(300000), credit: D(0) },
      { accountCode: '2230', accountName: 'PAYE Tax Payable', description: 'PAYE withheld', debit: D(0), credit: D(54000) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'RSSB employee', debit: D(0), credit: D(18900) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Net salary', debit: D(0), credit: D(227100) }
    ],
    totalDebit: D(300000), totalCredit: D(300000), debitTotal: D(300000), creditTotal: D(300000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Employer Contributions - February 2026',
    sourceType: 'payroll_run', sourceId: 'payroll_feb_001_erc', sourceReference: 'PAY-2026-003-ER',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'Employer RSSB contributions', debit: D(24900), credit: D(0) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'Employer RSSB payable', debit: D(0), credit: D(24900) }
    ],
    totalDebit: D(24900), totalCredit: D(24900), debitTotal: D(24900), creditTotal: D(24900)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Salary Payment - Marie Claire - February 2026',
    sourceType: 'payroll_salary', sourceId: 'payroll_feb_002', sourceReference: 'PAY-2026-004',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Gross salary', debit: D(200000), credit: D(0) },
      { accountCode: '2230', accountName: 'PAYE Tax Payable', description: 'PAYE withheld', debit: D(0), credit: D(20000) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'RSSB employee', debit: D(0), credit: D(12600) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Net salary', debit: D(0), credit: D(167400) }
    ],
    totalDebit: D(200000), totalCredit: D(200000), debitTotal: D(200000), creditTotal: D(200000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Employer Contributions - Marie Claire - February 2026',
    sourceType: 'payroll_run', sourceId: 'payroll_feb_002_erc', sourceReference: 'PAY-2026-004-ER',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'Employer RSSB contributions', debit: D(16600), credit: D(0) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'Employer RSSB payable', debit: D(0), credit: D(16600) }
    ],
    totalDebit: D(16600), totalCredit: D(16600), debitTotal: D(16600), creditTotal: D(16600)
  });

  // ═══════════════════════════════════════════════════════════════════
  // MARCH 2026 — Partial month (settlements)
  // ═══════════════════════════════════════════════════════════════════

  // ── SOURCE 11: VAT Settlement ────────────────────────────────────
  // Pay net VAT for Jan+Feb to RRA
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-03-15'),
    description: 'VAT Settlement - January & February 2026 - TXST-001',
    sourceType: 'vat_settlement', sourceId: 'vat_set_001', sourceReference: 'TXST-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2220', accountName: 'VAT Output', description: 'VAT settlement to RRA', debit: D(300000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'VAT payment to RRA', debit: D(0), credit: D(300000) }
    ],
    totalDebit: D(300000), totalCredit: D(300000), debitTotal: D(300000), creditTotal: D(300000)
  });

  // ── SOURCE 12: PAYE Settlement ───────────────────────────────────
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-03-15'),
    description: 'PAYE Settlement - January 2026 - TXST-002',
    sourceType: 'paye_settlement', sourceId: 'paye_set_001', sourceReference: 'TXST-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2230', accountName: 'PAYE Tax Payable', description: 'PAYE settlement to RRA', debit: D(40000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'PAYE payment to RRA', debit: D(0), credit: D(40000) }
    ],
    totalDebit: D(40000), totalCredit: D(40000), debitTotal: D(40000), creditTotal: D(40000)
  });

  // ── SOURCE 13: RSSB Settlement ───────────────────────────────────
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-03-15'),
    description: 'RSSB Settlement - January 2026 - TXST-003',
    sourceType: 'rssb_settlement', sourceId: 'rssb_set_001', sourceReference: 'TXST-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'RSSB settlement', debit: D(50000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'RSSB payment', debit: D(0), credit: D(50000) }
    ],
    totalDebit: D(50000), totalCredit: D(50000), debitTotal: D(50000), creditTotal: D(50000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // Insert all entries
  // ═══════════════════════════════════════════════════════════════════
  console.log(`\nInserting ${entries.length} journal entries...`);

  const inserted = await JournalEntry.insertMany(entries, { ordered: false }).catch(err => {
    if (err.insertedDocs && err.insertedDocs.length > 0) {
      console.log(`Inserted ${err.insertedDocs.length} entries (some duplicates skipped)`);
      return err.insertedDocs;
    }
    throw err;
  });

  console.log(`\nSuccessfully inserted ${inserted.length} journal entries`);

  // Summary
  const summary = {};
  inserted.forEach(e => {
    const type = e.sourceType || 'unknown';
    summary[type] = (summary[type] || 0) + 1;
  });

  console.log('\nSummary by source type:');
  Object.entries(summary).sort().forEach(([type, count]) => {
    console.log(`  ${type}: ${count}`);
  });

  // Compute totals for verification
  let totalVatOutput = 0, totalVatInput = 0, totalPaye = 0, totalRssb = 0, totalEmployerRssb = 0;
  let totalVatSettlement = 0, totalPayeSettlement = 0, totalRssbSettlement = 0;

  inserted.forEach(e => {
    e.lines.forEach(l => {
      const code = l.accountCode;
      const debit = parseFloat(l.debit?.toString() || '0');
      const credit = parseFloat(l.credit?.toString() || '0');

      if (code === '2220') { totalVatOutput += credit; totalVatSettlement += debit; }
      if (code === '2210') { totalVatInput += debit; }
      if (code === '2230') { totalPaye += credit; totalPayeSettlement += debit; }
      if (code === '2240') { totalRssb += credit; totalEmployerRssb += credit; totalRssbSettlement += debit; }
    });
  });

  console.log('\nTax Summary:');
  console.log(`  VAT Output (collected): ${totalVatOutput.toLocaleString()} RWF`);
  console.log(`  VAT Input (claimed):    ${totalVatInput.toLocaleString()} RWF`);
  console.log(`  Net VAT:                ${(totalVatOutput - totalVatInput).toLocaleString()} RWF`);
  console.log(`  VAT Settled:            ${totalVatSettlement.toLocaleString()} RWF`);
  console.log(`  PAYE Withheld:          ${totalPaye.toLocaleString()} RWF`);
  console.log(`  PAYE Settled:           ${totalPayeSettlement.toLocaleString()} RWF`);
  console.log(`  PAYE Outstanding:       ${(totalPaye - totalPayeSettlement).toLocaleString()} RWF`);
  console.log(`  RSSB Contributed:       ${totalRssb.toLocaleString()} RWF`);
  console.log(`  RSSB Settled:           ${totalRssbSettlement.toLocaleString()} RWF`);
  console.log(`  RSSB Outstanding:       ${(totalRssb - totalRssbSettlement).toLocaleString()} RWF`);

  process.exit(0);
}

seed().catch(e => { console.error('Error:', e.message); process.exit(1); });
