/**
 * Seed Balance Sheet Data — IAS 1 Compliant
 *
 * Creates journal entries that populate ALL balance sheet sections:
 *
 *   ASSETS
 *     Non-Current Assets
 *       1700 Equipment, 1710 Computers, 1720 Vehicles, 1740 Buildings, 1750 Land
 *       1810-1890 Accumulated Depreciation (contra-assets)
 *     Current Assets
 *       1000 Cash in Hand, 1100 Cash at Bank, 1200 MTN MoMo
 *       1300 Accounts Receivable, 1350 Other Receivables
 *       1400 Inventory, 1600 Prepaid Expenses
 *
 *   EQUITY
 *     3000 Share Capital, 3100 Retained Earnings, 3300 Dividends Paid
 *
 *   LIABILITIES
 *     Non-Current Liabilities
 *       2900 Long Term Loans
 *     Current Liabilities
 *       2000 Accounts Payable, 2700 Short Term Loans
 *       2210/2220 VAT, 2230 PAYE, 2240 RSSB, 2400 Income Tax, 2500 Withholding Tax
 *       2600 Accrued Expenses, 2800 Accrued Interest
 *
 * Usage: node scripts/seedBalanceSheet.js <companyId> <userId>
 */
const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock-management';
const D = (v) => mongoose.Types.Decimal128.fromString(String(v));

async function seed() {
  const args = process.argv.slice(2);
  const companyId = args[0];
  const userId = args[1];

  if (!companyId) {
    console.error('Usage: node scripts/seedBalanceSheet.js <companyId> <userId>');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const JournalEntry = require('../models/JournalEntry');
  const AccountBalance = require('../models/AccountBalance');

  // Clear existing BS seed entries
  const deleted = await JournalEntry.deleteMany({
    company: companyId,
    entryNumber: { $regex: /^SEED-BS-/ }
  }).setOptions({ skipTenant: true });
  console.log(`Cleared ${deleted.deletedCount} existing seed BS entries`);

  const entries = [];
  let seq = 0;
  const ref = (prefix) => { seq++; return `SEED-BS-${String(seq).padStart(4, '0')}`; };

  // ═══════════════════════════════════════════════════════════════════
  // EQUITY — Share Capital (3000)
  // ═══════════════════════════════════════════════════════════════════
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-01-01'),
    description: 'Share Capital — Initial investment',
    sourceType: 'opening_balance', sourceId: 'seed_bs_001', sourceReference: 'BS-2025-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Capital contribution', debit: D(5000000), credit: D(0) },
      { accountCode: '3000', accountName: 'Share Capital', description: 'Share capital issued', debit: D(0), credit: D(5000000) }
    ],
    totalDebit: D(5000000), totalCredit: D(5000000), debitTotal: D(5000000), creditTotal: D(5000000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // NON-CURRENT ASSETS — Fixed Assets
  // ═══════════════════════════════════════════════════════════════════

  // Equipment (1700)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-02-01'),
    description: 'Purchase — Office equipment',
    sourceType: 'asset_purchase', sourceId: 'seed_bs_010', sourceReference: 'BS-2025-010',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1700', accountName: 'Equipment', description: 'Office equipment', debit: D(800000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(800000) }
    ],
    totalDebit: D(800000), totalCredit: D(800000), debitTotal: D(800000), creditTotal: D(800000)
  });

  // Computers (1710)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-03-01'),
    description: 'Purchase — IT equipment',
    sourceType: 'asset_purchase', sourceId: 'seed_bs_011', sourceReference: 'BS-2025-011',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1710', accountName: 'Computers', description: 'Laptops & servers', debit: D(500000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(500000) }
    ],
    totalDebit: D(500000), totalCredit: D(500000), debitTotal: D(500000), creditTotal: D(500000)
  });

  // Vehicles (1720)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-04-01'),
    description: 'Purchase — Company vehicle',
    sourceType: 'asset_purchase', sourceId: 'seed_bs_012', sourceReference: 'BS-2025-012',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1720', accountName: 'Vehicles', description: 'Delivery van', debit: D(1200000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(1200000) }
    ],
    totalDebit: D(1200000), totalCredit: D(1200000), debitTotal: D(1200000), creditTotal: D(1200000)
  });

  // Land (1750)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-05-01'),
    description: 'Purchase — Land',
    sourceType: 'asset_purchase', sourceId: 'seed_bs_013', sourceReference: 'BS-2025-013',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1750', accountName: 'Land', description: 'Plot purchase', debit: D(2000000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(2000000) }
    ],
    totalDebit: D(2000000), totalCredit: D(2000000), debitTotal: D(2000000), creditTotal: D(2000000)
  });

  // Accumulated Depreciation (contra-assets) — 12 months
  for (let m = 1; m <= 12; m++) {
    const month = String(m).padStart(2, '0');
    // Equipment: 800,000 / 5 years / 12 months = 13,333/month
    entries.push({
      company: companyId, entryNumber: ref('BS'),
      date: new Date(`2025-${month}-28`),
      description: `Depreciation — Equipment ${month}/2025`,
      sourceType: 'depreciation', sourceId: `seed_bs_dep_equip_${m}`, sourceReference: `BS-DEP-E-${m}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5800', accountName: 'Depreciation Expense', description: 'Equipment depreciation', debit: D(13333), credit: D(0) },
        { accountCode: '1810', accountName: 'Accumulated Depreciation - Equipment', description: 'Accum depreciation', debit: D(0), credit: D(13333) }
      ],
      totalDebit: D(13333), totalCredit: D(13333), debitTotal: D(13333), creditTotal: D(13333)
    });

    // Computers: 500,000 / 3 years / 12 months = 13,889/month
    entries.push({
      company: companyId, entryNumber: ref('BS'),
      date: new Date(`2025-${month}-28`),
      description: `Depreciation — Computers ${month}/2025`,
      sourceType: 'depreciation', sourceId: `seed_bs_dep_comp_${m}`, sourceReference: `BS-DEP-C-${m}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5800', accountName: 'Depreciation Expense', description: 'Computer depreciation', debit: D(13889), credit: D(0) },
        { accountCode: '1820', accountName: 'Accumulated Depreciation - Computers', description: 'Accum depreciation', debit: D(0), credit: D(13889) }
      ],
      totalDebit: D(13889), totalCredit: D(13889), debitTotal: D(13889), creditTotal: D(13889)
    });

    // Vehicles: 1,200,000 / 5 years / 12 months = 20,000/month
    entries.push({
      company: companyId, entryNumber: ref('BS'),
      date: new Date(`2025-${month}-28`),
      description: `Depreciation — Vehicles ${month}/2025`,
      sourceType: 'depreciation', sourceId: `seed_bs_dep_veh_${m}`, sourceReference: `BS-DEP-V-${m}`,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5800', accountName: 'Depreciation Expense', description: 'Vehicle depreciation', debit: D(20000), credit: D(0) },
        { accountCode: '1830', accountName: 'Accumulated Depreciation - Vehicles', description: 'Accum depreciation', debit: D(0), credit: D(20000) }
      ],
      totalDebit: D(20000), totalCredit: D(20000), debitTotal: D(20000), creditTotal: D(20000)
    });
  }

  // ═══════════════════════════════════════════════════════════════════
  // CURRENT ASSETS — Inventory
  // ═══════════════════════════════════════════════════════════════════
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-06-01'),
    description: 'Inventory — Opening stock',
    sourceType: 'opening_balance', sourceId: 'seed_bs_020', sourceReference: 'BS-2025-020',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1400', accountName: 'Inventory', description: 'Opening inventory', debit: D(1500000), credit: D(0) },
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Supplier payable', debit: D(0), credit: D(1500000) }
    ],
    totalDebit: D(1500000), totalCredit: D(1500000), debitTotal: D(1500000), creditTotal: D(1500000)
  });

  // Cash in Hand (1000)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-06-15'),
    description: 'Cash in Hand — petty cash top-up',
    sourceType: 'petty_cash', sourceId: 'seed_bs_021', sourceReference: 'BS-2025-021',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1000', accountName: 'Cash in Hand', description: 'Petty cash', debit: D(50000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank withdrawal', debit: D(0), credit: D(50000) }
    ],
    totalDebit: D(50000), totalCredit: D(50000), debitTotal: D(50000), creditTotal: D(50000)
  });

  // MTN MoMo (1200)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-07-01'),
    description: 'MTN MoMo — Mobile money account',
    sourceType: 'opening_balance', sourceId: 'seed_bs_022', sourceReference: 'BS-2025-022',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1200', accountName: 'MTN MoMo', description: 'Mobile money', debit: D(200000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Transfer', debit: D(0), credit: D(200000) }
    ],
    totalDebit: D(200000), totalCredit: D(200000), debitTotal: D(200000), creditTotal: D(200000)
  });

  // Prepaid Expenses (1600)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-07-15'),
    description: 'Prepaid Expenses — Insurance advance',
    sourceType: 'opening_balance', sourceId: 'seed_bs_023', sourceReference: 'BS-2025-023',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1600', accountName: 'Prepaid Expenses', description: 'Insurance prepaid', debit: D(120000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(120000) }
    ],
    totalDebit: D(120000), totalCredit: D(120000), debitTotal: D(120000), creditTotal: D(120000)
  });

  // Other Receivables (1350)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-08-01'),
    description: 'Other Receivables — Staff loan',
    sourceType: 'manual', sourceId: 'seed_bs_024', sourceReference: 'BS-2025-024',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1350', accountName: 'Other Receivables', description: 'Staff loan', debit: D(75000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Loan disbursement', debit: D(0), credit: D(75000) }
    ],
    totalDebit: D(75000), totalCredit: D(75000), debitTotal: D(75000), creditTotal: D(75000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // NON-CURRENT LIABILITIES — Long Term Loan (2900)
  // ═══════════════════════════════════════════════════════════════════
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-03-15'),
    description: 'Long Term Loan — Bank facility',
    sourceType: 'liability_drawdown', sourceId: 'seed_bs_030', sourceReference: 'BS-2025-030',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Loan received', debit: D(3000000), credit: D(0) },
      { accountCode: '2900', accountName: 'Long Term Loans', description: 'Bank loan', debit: D(0), credit: D(3000000) }
    ],
    totalDebit: D(3000000), totalCredit: D(3000000), debitTotal: D(3000000), creditTotal: D(3000000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // CURRENT LIABILITIES
  // ═══════════════════════════════════════════════════════════════════

  // Accounts Payable (2000) — already created by inventory entry above
  // Additional AP
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-09-01'),
    description: 'Accounts Payable — Supplier invoice',
    sourceType: 'purchase', sourceId: 'seed_bs_040', sourceReference: 'BS-2025-040',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1400', accountName: 'Inventory', description: 'Goods received', debit: D(300000), credit: D(0) },
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Supplier payable', debit: D(0), credit: D(300000) }
    ],
    totalDebit: D(300000), totalCredit: D(300000), debitTotal: D(300000), creditTotal: D(300000)
  });

  // Short Term Loan (2700)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-09-15'),
    description: 'Short Term Loan — Overdraft',
    sourceType: 'liability_drawdown', sourceId: 'seed_bs_041', sourceReference: 'BS-2025-041',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Overdraft facility', debit: D(500000), credit: D(0) },
      { accountCode: '2700', accountName: 'Short Term Loans', description: 'Bank overdraft', debit: D(0), credit: D(500000) }
    ],
    totalDebit: D(500000), totalCredit: D(500000), debitTotal: D(500000), creditTotal: D(500000)
  });

  // VAT Output (2220) — Net VAT position (Output - Input)
  // After settlement: VAT Output 180,000 cleared, VAT Input 120,000 cleared, Cash paid 60,000
  // Net position: VAT Output 180,000 remaining (unsettled), VAT Input 120,000 remaining (unsettled)
  // For balance sheet: show both as separate line items
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-10-15'),
    description: 'VAT — Sales VAT collected',
    sourceType: 'manual', sourceId: 'seed_bs_042a', sourceReference: 'BS-2025-042a',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice including VAT', debit: D(212400), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Net sales', debit: D(0), credit: D(180000) },
      { accountCode: '2220', accountName: 'VAT Output', description: 'VAT on sales', debit: D(0), credit: D(32400) }
    ],
    totalDebit: D(212400), totalCredit: D(212400), debitTotal: D(212400), creditTotal: D(212400)
  });

  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-10-20'),
    description: 'VAT — Purchase VAT paid',
    sourceType: 'purchase', sourceId: 'seed_bs_042b', sourceReference: 'BS-2025-042b',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5100', accountName: 'Purchases', description: 'Net purchases', debit: D(100000), credit: D(0) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'VAT on purchases', debit: D(18000), credit: D(0) },
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Supplier payable', debit: D(0), credit: D(118000) }
    ],
    totalDebit: D(118000), totalCredit: D(118000), debitTotal: D(118000), creditTotal: D(118000)
  });

  // PAYE Payable (2230)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-10-31'),
    description: 'PAYE Payable — Employee tax withheld',
    sourceType: 'manual', sourceId: 'seed_bs_043', sourceReference: 'BS-2025-043',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Gross salary', debit: D(200000), credit: D(0) },
      { accountCode: '2230', accountName: 'PAYE Tax Payable', description: 'PAYE withheld', debit: D(0), credit: D(40000) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Net salary', debit: D(0), credit: D(160000) }
    ],
    totalDebit: D(200000), totalCredit: D(200000), debitTotal: D(200000), creditTotal: D(200000)
  });

  // RSSB Payable (2240)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-10-31'),
    description: 'RSSB Payable — Employer & employee contributions',
    sourceType: 'manual', sourceId: 'seed_bs_044', sourceReference: 'BS-2025-044',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'Employer share', debit: D(10000), credit: D(0) },
      { accountCode: '2240', accountName: 'RSSB Payable', description: 'Total RSSB payable', debit: D(0), credit: D(18000) },
      { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Employee share deducted', debit: D(8000), credit: D(0) }
    ],
    totalDebit: D(18000), totalCredit: D(18000), debitTotal: D(18000), creditTotal: D(18000)
  });

  // Income Tax Payable (2400)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-12-31'),
    description: 'Income Tax Payable — Corporate tax provision',
    sourceType: 'tax_accrual', sourceId: 'seed_bs_045', sourceReference: 'BS-2025-045',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6400', accountName: 'Corporate Tax', description: 'Tax provision', debit: D(280000), credit: D(0) },
      { accountCode: '2400', accountName: 'Income Tax Payable', description: 'Tax payable', debit: D(0), credit: D(280000) }
    ],
    totalDebit: D(280000), totalCredit: D(280000), debitTotal: D(280000), creditTotal: D(280000)
  });

  // Withholding Tax Payable (2500)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-12-31'),
    description: 'Withholding Tax Payable — Contractor payments',
    sourceType: 'manual', sourceId: 'seed_bs_046', sourceReference: 'BS-2025-046',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6100', accountName: 'Other Expenses', description: 'Consulting fees', debit: D(100000), credit: D(0) },
      { accountCode: '2500', accountName: 'Withholding Tax Payable', description: 'WHT withheld', debit: D(0), credit: D(15000) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Net payment', debit: D(0), credit: D(85000) }
    ],
    totalDebit: D(100000), totalCredit: D(100000), debitTotal: D(100000), creditTotal: D(100000)
  });

  // Accrued Expenses (2600)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-12-31'),
    description: 'Accrued Expenses — Year-end accruals',
    sourceType: 'adjustment', sourceId: 'seed_bs_047', sourceReference: 'BS-2025-047',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5500', accountName: 'Rent', description: 'Rent accrued', debit: D(60000), credit: D(0) },
      { accountCode: '2600', accountName: 'Accrued Expenses', description: 'Rent payable', debit: D(0), credit: D(60000) }
    ],
    totalDebit: D(60000), totalCredit: D(60000), debitTotal: D(60000), creditTotal: D(60000)
  });

  // Accrued Interest (2800)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-12-31'),
    description: 'Accrued Interest — Loan interest payable',
    sourceType: 'interest_accrual', sourceId: 'seed_bs_048', sourceReference: 'BS-2025-048',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6000', accountName: 'Interest Expense', description: 'Interest accrued', debit: D(75000), credit: D(0) },
      { accountCode: '2800', accountName: 'Accrued Interest', description: 'Interest payable', debit: D(0), credit: D(75000) }
    ],
    totalDebit: D(75000), totalCredit: D(75000), debitTotal: D(75000), creditTotal: D(75000)
  });

  // Dividends Paid (3300)
  entries.push({
    company: companyId, entryNumber: ref('BS'),
    date: new Date('2025-12-15'),
    description: 'Dividends Paid — Interim dividend',
    sourceType: 'manual', sourceId: 'seed_bs_050', sourceReference: 'BS-2025-050',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '3300', accountName: 'Dividends Paid', description: 'Interim dividend', debit: D(200000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Dividend payment', debit: D(0), credit: D(200000) }
    ],
    totalDebit: D(200000), totalCredit: D(200000), debitTotal: D(200000), creditTotal: D(200000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // Insert all entries
  // ═══════════════════════════════════════════════════════════════════
  console.log(`\nInserting ${entries.length} balance sheet journal entries...`);

  const inserted = await JournalEntry.insertMany(entries, { ordered: false }).catch(err => {
    if (err.insertedDocs && err.insertedDocs.length > 0) {
      console.log(`Inserted ${err.insertedDocs.length} entries (some duplicates skipped)`);
      return err.insertedDocs;
    }
    throw err;
  });

  console.log(`Successfully inserted ${inserted.length} journal entries`);

  // Rebuild AccountBalance
  const affectedCodes = new Set();
  inserted.forEach(e => e.lines.forEach(l => affectedCodes.add(l.accountCode)));
  console.log(`\nRebuilding AccountBalance for ${affectedCodes.size} accounts...`);

  for (const code of affectedCodes) {
    await AccountBalance.findOneAndUpdate(
      { company: companyId, accountCode: code },
      { $setOnInsert: { company: companyId, accountCode: code, debit: 0, credit: 0 } },
      { upsert: true, setDefaultsOnInsert: true }
    );
  }

  const allEntries = await JournalEntry.find({
    company: companyId, status: 'posted'
  }).setOptions({ skipTenant: true }).lean();

  await AccountBalance.updateMany(
    { company: companyId },
    { $set: { debit: 0, credit: 0 } }
  ).setOptions({ skipTenant: true });

  for (const entry of allEntries) {
    for (const line of entry.lines) {
      const debit = parseFloat(line.debit?.toString() || '0');
      const credit = parseFloat(line.credit?.toString() || '0');
      if (debit > 0 || credit > 0) {
        await AccountBalance.adjust(companyId, line.accountCode, debit, credit);
      }
    }
  }

  console.log('AccountBalance rebuilt');

  // ── Summary ─────────────────────────────────────────────────────
  const summary = {};
  inserted.forEach(e => {
    const type = e.sourceType || 'unknown';
    summary[type] = (summary[type] || 0) + 1;
  });

  console.log('\n=== Entry Summary ===');
  Object.entries(summary).sort().forEach(([type, count]) => {
    console.log(`  ${type}: ${count}`);
  });

  // ── Verify BS Coverage ─────────────────────────────────────────
  console.log('\n=== Balance Sheet Coverage Check ===');
  const bsAccounts = {
    'Non-Current Assets': ['1700', '1710', '1720', '1750'],
    'Contra Assets': ['1810', '1820', '1830'],
    'Current Assets': ['1000', '1100', '1200', '1350', '1400', '1600'],
    'Equity': ['3000', '3300'],
    'Non-Current Liabilities': ['2900'],
    'Current Liabilities': ['2000', '2210', '2220', '2230', '2240', '2400', '2500', '2600', '2700', '2800']
  };

  for (const [section, codes] of Object.entries(bsAccounts)) {
    const balances = await AccountBalance.find({
      company: companyId,
      accountCode: { $in: codes },
      $or: [{ debit: { $gt: 0 } }, { credit: { $gt: 0 } }]
    }).setOptions({ skipTenant: true }).lean();

    const hasData = balances.length > 0;
    console.log(`  ${hasData ? 'OK' : 'MISSING'} ${section}: ${balances.length}/${codes.length} accounts with data`);
  }

  console.log('\nBalance Sheet seed complete!');
  process.exit(0);
}

seed().catch(e => { console.error('Error:', e.message, e.stack); process.exit(1); });
