/**
 * Seed Full P&L Data — IAS 1 Compliant Income Statement
 *
 * Covers ALL 19 sections of the IAS 1 Statement of Profit or Loss
 * and Other Comprehensive Income:
 *
 *   1.  Revenue (4000 Sales, 4100 Sales Returns contra)
 *   2.  Cost of Sales (5000 COGS, 5100 Purchases, 5110 Freight In, 5200 Purchase Returns, 5300 Direct Labor)
 *   3.  Gross Profit (= Revenue - COGS)
 *   4.  Other Income (4200 Other Income, 4300 Interest Income, 4250 Gain on Disposal)
 *   5.  Distribution Costs (5700 Transport, 5850 Marketing)
 *   6.  Administrative Expenses (5400 Salaries, 5410 Payroll, 5500 Rent, 5600 Utilities, 5800 Depreciation, 6150 RSSB)
 *   7.  Other Expenses (5250 Bad Debt, 6100 Other Expenses)
 *   8.  Operating Profit / EBIT
 *   9.  Finance Costs (6000 Interest Expense, 6200 Bank Charges)
 *  10.  Share of Associates/JV (0 — placeholder)
 *  11.  Profit Before Tax
 *  12.  Tax Expense (6400 Corporate Tax)
 *  13.  Profit After Tax (Continuing Operations)
 *  14.  Discontinued Operations (0 — placeholder)
 *  15.  Profit for the Period
 *  16.  Other Comprehensive Income (6050 Loss on Disposal)
 *  17.  Total Comprehensive Income
 *  18.  Profit Attributable to Owners / NCI
 *  19.  Earnings Per Share
 *
 * Usage: node scripts/seedFullPL.js <companyId> <userId>
 */
const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock-management';
const D = (v) => mongoose.Types.Decimal128.fromString(String(v));

async function seed() {
  const args = process.argv.slice(2);
  const companyId = args[0];
  const userId = args[1];

  if (!companyId) {
    console.error('Usage: node scripts/seedFullPL.js <companyId> <userId>');
    console.error('  companyId — the ObjectId of the company');
    console.error('  userId    — the ObjectId of the user creating the entries');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const JournalEntry = require('../models/JournalEntry');
  const AccountBalance = require('../models/AccountBalance');

  // ── Clear existing seed entries ──────────────────────────────────
  const deleted = await JournalEntry.deleteMany({
    company: companyId,
    entryNumber: { $regex: /^SEED-PL-/ }
  }).setOptions({ skipTenant: true });
  console.log(`Cleared ${deleted.deletedCount} existing seed P&L entries`);

  const entries = [];
  let seq = 0;
  const ref = (prefix) => { seq++; return `SEED-PL-${String(seq).padStart(4, '0')}`; };

  // ─────────────────────────────────────────────────────────────────
  // 1. REVENUE (Section 1)
  // ─────────────────────────────────────────────────────────────────

  // Jan — Sales Revenue 1,200,000
  entries.push({
    company: companyId, entryNumber: ref('REV'),
    date: new Date('2026-01-15'),
    description: 'Sales revenue — January invoices',
    sourceType: 'invoice', sourceId: 'seed_inv_001', sourceReference: 'INV-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice to customers', debit: D(1200000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Sales for January', debit: D(0), credit: D(1200000) }
    ],
    totalDebit: D(1200000), totalCredit: D(1200000), debitTotal: D(1200000), creditTotal: D(1200000)
  });

  // Feb — Sales Revenue 1,500,000
  entries.push({
    company: companyId, entryNumber: ref('REV'),
    date: new Date('2026-02-18'),
    description: 'Sales revenue — February invoices',
    sourceType: 'invoice', sourceId: 'seed_inv_002', sourceReference: 'INV-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice to customers', debit: D(1500000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Sales for February', debit: D(0), credit: D(1500000) }
    ],
    totalDebit: D(1500000), totalCredit: D(1500000), debitTotal: D(1500000), creditTotal: D(1500000)
  });

  // Mar — Sales Revenue 1,800,000
  entries.push({
    company: companyId, entryNumber: ref('REV'),
    date: new Date('2026-03-20'),
    description: 'Sales revenue — March invoices',
    sourceType: 'invoice', sourceId: 'seed_inv_003', sourceReference: 'INV-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Invoice to customers', debit: D(1800000), credit: D(0) },
      { accountCode: '4000', accountName: 'Sales Revenue', description: 'Sales for March', debit: D(0), credit: D(1800000) }
    ],
    totalDebit: D(1800000), totalCredit: D(1800000), debitTotal: D(1800000), creditTotal: D(1800000)
  });

  // Sales Returns (4100) — contra revenue
  entries.push({
    company: companyId, entryNumber: ref('SRET'),
    date: new Date('2026-02-10'),
    description: 'Sales return — defective goods',
    sourceType: 'credit_note', sourceId: 'seed_cn_001', sourceReference: 'CN-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '4100', accountName: 'Sales Returns', description: 'Return from customer', debit: D(80000), credit: D(0) },
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'Credit note adjustment', debit: D(0), credit: D(80000) }
    ],
    totalDebit: D(80000), totalCredit: D(80000), debitTotal: D(80000), creditTotal: D(80000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 2. COST OF SALES (Section 2)
  // ─────────────────────────────────────────────────────────────────

  // COGS — January
  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-01-15'),
    description: 'COGS Recognition — January sales',
    sourceType: 'cogs', sourceId: 'seed_cogs_001', sourceReference: 'COGS-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5000', accountName: 'Cost of Goods Sold', description: 'Cost of goods sold', debit: D(350000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Inventory reduction', debit: D(0), credit: D(350000) }
    ],
    totalDebit: D(350000), totalCredit: D(350000), debitTotal: D(350000), creditTotal: D(350000)
  });

  // COGS — February
  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-02-18'),
    description: 'COGS Recognition — February sales',
    sourceType: 'cogs', sourceId: 'seed_cogs_002', sourceReference: 'COGS-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5000', accountName: 'Cost of Goods Sold', description: 'Cost of goods sold', debit: D(480000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Inventory reduction', debit: D(0), credit: D(480000) }
    ],
    totalDebit: D(480000), totalCredit: D(480000), debitTotal: D(480000), creditTotal: D(480000)
  });

  // COGS — March
  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-03-20'),
    description: 'COGS Recognition — March sales',
    sourceType: 'cogs', sourceId: 'seed_cogs_003', sourceReference: 'COGS-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5000', accountName: 'Cost of Goods Sold', description: 'Cost of goods sold', debit: D(550000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Inventory reduction', debit: D(0), credit: D(550000) }
    ],
    totalDebit: D(550000), totalCredit: D(550000), debitTotal: D(550000), creditTotal: D(550000)
  });

  // Freight In (5110)
  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-01-20'),
    description: 'Freight In — Supplier shipment',
    sourceType: 'cogs', sourceId: 'seed_fr_001', sourceReference: 'FR-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5110', accountName: 'Freight In', description: 'Shipping cost', debit: D(25000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Freight payment', debit: D(0), credit: D(25000) }
    ],
    totalDebit: D(25000), totalCredit: D(25000), debitTotal: D(25000), creditTotal: D(25000)
  });

  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-02-20'),
    description: 'Freight In — Supplier shipment Feb',
    sourceType: 'cogs', sourceId: 'seed_fr_002', sourceReference: 'FR-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5110', accountName: 'Freight In', description: 'Shipping cost', debit: D(30000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Freight payment', debit: D(0), credit: D(30000) }
    ],
    totalDebit: D(30000), totalCredit: D(30000), debitTotal: D(30000), creditTotal: D(30000)
  });

  // Direct Labor (5300)
  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-01-31'),
    description: 'Direct Labor — Warehouse workers January',
    sourceType: 'cogs', sourceId: 'seed_dl_001', sourceReference: 'DL-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5300', accountName: 'Direct Labor', description: 'Warehouse labor', debit: D(80000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Labor payment', debit: D(0), credit: D(80000) }
    ],
    totalDebit: D(80000), totalCredit: D(80000), debitTotal: D(80000), creditTotal: D(80000)
  });

  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-02-28'),
    description: 'Direct Labor — Warehouse workers February',
    sourceType: 'cogs', sourceId: 'seed_dl_002', sourceReference: 'DL-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5300', accountName: 'Direct Labor', description: 'Warehouse labor', debit: D(80000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Labor payment', debit: D(0), credit: D(80000) }
    ],
    totalDebit: D(80000), totalCredit: D(80000), debitTotal: D(80000), creditTotal: D(80000)
  });

  // Purchase Returns (5200) — contra COGS
  entries.push({
    company: companyId, entryNumber: ref('PRET'),
    date: new Date('2026-03-05'),
    description: 'Purchase Return — Supplier',
    sourceType: 'stock_adjustment', sourceId: 'seed_pret_001', sourceReference: 'PR-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Return to supplier', debit: D(35400), credit: D(0) },
      { accountCode: '5200', accountName: 'Purchase Returns', description: 'Purchase return credit', debit: D(0), credit: D(30000) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'VAT reversal', debit: D(0), credit: D(5400) }
    ],
    totalDebit: D(35400), totalCredit: D(35400), debitTotal: D(35400), creditTotal: D(35400)
  });

  // Stock Adjustment Loss (5150)
  entries.push({
    company: companyId, entryNumber: ref('COGS'),
    date: new Date('2026-03-10'),
    description: 'Stock Adjustment Loss — damaged goods',
    sourceType: 'stock_adjustment', sourceId: 'seed_sa_001', sourceReference: 'SA-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5150', accountName: 'Stock Adjustment Loss', description: 'Damaged stock write-off', debit: D(15000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Inventory reduction', debit: D(0), credit: D(15000) }
    ],
    totalDebit: D(15000), totalCredit: D(15000), debitTotal: D(15000), creditTotal: D(15000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 4. OTHER INCOME (Section 4)
  // ─────────────────────────────────────────────────────────────────

  // Other Income (4200) — commission
  entries.push({
    company: companyId, entryNumber: ref('OINC'),
    date: new Date('2026-01-25'),
    description: 'Other Income — Commission received',
    sourceType: 'other_income', sourceId: 'seed_oi_001', sourceReference: 'OI-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Commission received', debit: D(50000), credit: D(0) },
      { accountCode: '4200', accountName: 'Other Income', description: 'Commission income', debit: D(0), credit: D(50000) }
    ],
    totalDebit: D(50000), totalCredit: D(50000), debitTotal: D(50000), creditTotal: D(50000)
  });

  // Interest Income (4300)
  entries.push({
    company: companyId, entryNumber: ref('OINC'),
    date: new Date('2026-02-01'),
    description: 'Interest Income — Bank savings',
    sourceType: 'other_income', sourceId: 'seed_oi_002', sourceReference: 'OI-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Interest credited', debit: D(15000), credit: D(0) },
      { accountCode: '4300', accountName: 'Interest Income', description: 'Bank interest', debit: D(0), credit: D(15000) }
    ],
    totalDebit: D(15000), totalCredit: D(15000), debitTotal: D(15000), creditTotal: D(15000)
  });

  // Gain on Asset Disposal (4250)
  entries.push({
    company: companyId, entryNumber: ref('OINC'),
    date: new Date('2026-02-20'),
    description: 'Gain on disposal — Old vehicle sold',
    sourceType: 'asset_disposal', sourceId: 'seed_gain_001', sourceReference: 'AD-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Sale proceeds', debit: D(800000), credit: D(0) },
      { accountCode: '4250', accountName: 'Gain on Asset Disposal', description: 'Gain on sale of vehicle', debit: D(0), credit: D(150000) },
      { accountCode: '1720', accountName: 'Vehicles', description: 'Asset removal', debit: D(0), credit: D(650000) }
    ],
    totalDebit: D(800000), totalCredit: D(800000), debitTotal: D(800000), creditTotal: D(800000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 5. DISTRIBUTION COSTS (Section 5)
  // ─────────────────────────────────────────────────────────────────

  // Transport & Delivery (5700)
  entries.push({
    company: companyId, entryNumber: ref('DIST'),
    date: new Date('2026-01-20'),
    description: 'Transport & Delivery — January',
    sourceType: 'distribution_cost', sourceId: 'seed_dist_001', sourceReference: 'DIST-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5700', accountName: 'Transport & Delivery', description: 'Customer delivery costs', debit: D(35000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Transport payment', debit: D(0), credit: D(35000) }
    ],
    totalDebit: D(35000), totalCredit: D(35000), debitTotal: D(35000), creditTotal: D(35000)
  });

  entries.push({
    company: companyId, entryNumber: ref('DIST'),
    date: new Date('2026-02-20'),
    description: 'Transport & Delivery — February',
    sourceType: 'distribution_cost', sourceId: 'seed_dist_002', sourceReference: 'DIST-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5700', accountName: 'Transport & Delivery', description: 'Customer delivery costs', debit: D(42000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Transport payment', debit: D(0), credit: D(42000) }
    ],
    totalDebit: D(42000), totalCredit: D(42000), debitTotal: D(42000), creditTotal: D(42000)
  });

  entries.push({
    company: companyId, entryNumber: ref('DIST'),
    date: new Date('2026-03-18'),
    description: 'Transport & Delivery — March',
    sourceType: 'distribution_cost', sourceId: 'seed_dist_003', sourceReference: 'DIST-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5700', accountName: 'Transport & Delivery', description: 'Customer delivery costs', debit: D(38000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Transport payment', debit: D(0), credit: D(38000) }
    ],
    totalDebit: D(38000), totalCredit: D(38000), debitTotal: D(38000), creditTotal: D(38000)
  });

  // Marketing & Advertising (5850)
  entries.push({
    company: companyId, entryNumber: ref('DIST'),
    date: new Date('2026-01-15'),
    description: 'Marketing — Facebook ads campaign',
    sourceType: 'distribution_cost', sourceId: 'seed_mkt_001', sourceReference: 'MKT-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5850', accountName: 'Marketing & Advertising', description: 'Social media ads', debit: D(45000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(45000) }
    ],
    totalDebit: D(45000), totalCredit: D(45000), debitTotal: D(45000), creditTotal: D(45000)
  });

  entries.push({
    company: companyId, entryNumber: ref('DIST'),
    date: new Date('2026-02-15'),
    description: 'Marketing — Google ads campaign',
    sourceType: 'distribution_cost', sourceId: 'seed_mkt_002', sourceReference: 'MKT-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5850', accountName: 'Marketing & Advertising', description: 'Google ads', debit: D(35000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(35000) }
    ],
    totalDebit: D(35000), totalCredit: D(35000), debitTotal: D(35000), creditTotal: D(35000)
  });

  entries.push({
    company: companyId, entryNumber: ref('DIST'),
    date: new Date('2026-03-10'),
    description: 'Marketing — Print media campaign',
    sourceType: 'distribution_cost', sourceId: 'seed_mkt_003', sourceReference: 'MKT-2026-003',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5850', accountName: 'Marketing & Advertising', description: 'Print ads', debit: D(25000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(25000) }
    ],
    totalDebit: D(25000), totalCredit: D(25000), debitTotal: D(25000), creditTotal: D(25000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 6. ADMINISTRATIVE EXPENSES (Section 6)
  // ─────────────────────────────────────────────────────────────────

  // Salaries & Wages (5400) — Jan, Feb, Mar
  for (const month of [
    { label: 'January', date: '2026-01-31', ref: 'SAL-2026-001' },
    { label: 'February', date: '2026-02-28', ref: 'SAL-2026-002' },
    { label: 'March', date: '2026-03-31', ref: 'SAL-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('ADM'),
      date: new Date(month.date),
      description: `Salaries & Wages — ${month.label}`,
      sourceType: 'admin_expense', sourceId: `seed_sal_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5400', accountName: 'Salaries & Wages', description: 'Monthly salaries', debit: D(180000), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Salary payment', debit: D(0), credit: D(180000) }
      ],
      totalDebit: D(180000), totalCredit: D(180000), debitTotal: D(180000), creditTotal: D(180000)
    });
  }

  // Payroll Expenses (5410) — employer contributions
  for (const month of [
    { label: 'January', date: '2026-01-31', ref: 'PAY-2026-001' },
    { label: 'February', date: '2026-02-28', ref: 'PAY-2026-002' },
    { label: 'March', date: '2026-03-31', ref: 'PAY-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('ADM'),
      date: new Date(month.date),
      description: `Payroll Expenses — ${month.label}`,
      sourceType: 'admin_expense', sourceId: `seed_pay_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5410', accountName: 'Payroll Expenses', description: 'Employer contributions', debit: D(20000), credit: D(0) },
        { accountCode: '2240', accountName: 'RSSB Payable', description: 'Employer liability', debit: D(0), credit: D(20000) }
      ],
      totalDebit: D(20000), totalCredit: D(20000), debitTotal: D(20000), creditTotal: D(20000)
    });
  }

  // Rent (5500)
  for (const month of [
    { label: 'January', date: '2026-01-05', ref: 'RENT-2026-001' },
    { label: 'February', date: '2026-02-05', ref: 'RENT-2026-002' },
    { label: 'March', date: '2026-03-05', ref: 'RENT-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('ADM'),
      date: new Date(month.date),
      description: `Rent — ${month.label}`,
      sourceType: 'admin_expense', sourceId: `seed_rent_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5500', accountName: 'Rent', description: 'Office rent', debit: D(60000), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Rent payment', debit: D(0), credit: D(60000) }
      ],
      totalDebit: D(60000), totalCredit: D(60000), debitTotal: D(60000), creditTotal: D(60000)
    });
  }

  // Utilities (5600)
  for (const month of [
    { label: 'January', date: '2026-01-28', ref: 'UTIL-2026-001' },
    { label: 'February', date: '2026-02-28', ref: 'UTIL-2026-002' },
    { label: 'March', date: '2026-03-28', ref: 'UTIL-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('ADM'),
      date: new Date(month.date),
      description: `Utilities — ${month.label}`,
      sourceType: 'admin_expense', sourceId: `seed_util_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5600', accountName: 'Utilities', description: 'Electricity & water', debit: D(18000), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Utility payment', debit: D(0), credit: D(18000) }
      ],
      totalDebit: D(18000), totalCredit: D(18000), debitTotal: D(18000), creditTotal: D(18000)
    });
  }

  // Depreciation (5800)
  for (const month of [
    { label: 'January', date: '2026-01-31', ref: 'DEP-2026-001' },
    { label: 'February', date: '2026-02-28', ref: 'DEP-2026-002' },
    { label: 'March', date: '2026-03-31', ref: 'DEP-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('ADM'),
      date: new Date(month.date),
      description: `Depreciation — ${month.label}`,
      sourceType: 'depreciation', sourceId: `seed_dep_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '5800', accountName: 'Depreciation Expense', description: 'Monthly depreciation', debit: D(42000), credit: D(0) },
        { accountCode: '1810', accountName: 'Accumulated Depreciation - Equipment', description: 'Accum depreciation', debit: D(0), credit: D(42000) }
      ],
      totalDebit: D(42000), totalCredit: D(42000), debitTotal: D(42000), creditTotal: D(42000)
    });
  }

  // RSSB Employer Cost (6150)
  entries.push({
    company: companyId, entryNumber: ref('ADM'),
    date: new Date('2026-01-31'),
    description: 'RSSB Employer Cost — January',
    sourceType: 'admin_expense', sourceId: 'seed_rssb_001', sourceReference: 'RSSB-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'RSSB employer share', debit: D(12000), credit: D(0) },
      { accountCode: '2310', accountName: 'Employer Contribution Payable', description: 'RSSB payable', debit: D(0), credit: D(12000) }
    ],
    totalDebit: D(12000), totalCredit: D(12000), debitTotal: D(12000), creditTotal: D(12000)
  });

  entries.push({
    company: companyId, entryNumber: ref('ADM'),
    date: new Date('2026-02-28'),
    description: 'RSSB Employer Cost — February',
    sourceType: 'admin_expense', sourceId: 'seed_rssb_002', sourceReference: 'RSSB-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6150', accountName: 'RSSB Employer Cost', description: 'RSSB employer share', debit: D(12000), credit: D(0) },
      { accountCode: '2310', accountName: 'Employer Contribution Payable', description: 'RSSB payable', debit: D(0), credit: D(12000) }
    ],
    totalDebit: D(12000), totalCredit: D(12000), debitTotal: D(12000), creditTotal: D(12000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 7. OTHER EXPENSES (Section 7)
  // ─────────────────────────────────────────────────────────────────

  // Bad Debt Expense (5250)
  entries.push({
    company: companyId, entryNumber: ref('OEXP'),
    date: new Date('2026-02-28'),
    description: 'Bad Debt Write-off — Customer defaulted',
    sourceType: 'bad_debt_writeoff', sourceId: 'seed_bd_001', sourceReference: 'BD-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5250', accountName: 'Bad Debt Expense', description: 'Write-off bad debt', debit: D(35000), credit: D(0) },
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'AR written off', debit: D(0), credit: D(35000) }
    ],
    totalDebit: D(35000), totalCredit: D(35000), debitTotal: D(35000), creditTotal: D(35000)
  });

  // Other Expenses (6100)
  entries.push({
    company: companyId, entryNumber: ref('OEXP'),
    date: new Date('2026-03-15'),
    description: 'Other Expenses — Office supplies & miscellaneous',
    sourceType: 'other_expense', sourceId: 'seed_oe_001', sourceReference: 'OE-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6100', accountName: 'Other Expenses', description: 'Office supplies', debit: D(22000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(22000) }
    ],
    totalDebit: D(22000), totalCredit: D(22000), debitTotal: D(22000), creditTotal: D(22000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 9. FINANCE COSTS (Section 9)
  // ─────────────────────────────────────────────────────────────────

  // Interest Expense (6000)
  for (const month of [
    { label: 'January', date: '2026-01-31', ref: 'INT-2026-001' },
    { label: 'February', date: '2026-02-28', ref: 'INT-2026-002' },
    { label: 'March', date: '2026-03-31', ref: 'INT-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('FIN'),
      date: new Date(month.date),
      description: `Interest Expense — Bank loan ${month.label}`,
      sourceType: 'loan_interest', sourceId: `seed_int_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '6000', accountName: 'Interest Expense', description: `Loan interest ${month.label}`, debit: D(75000), credit: D(0) },
        { accountCode: '2600', accountName: 'Accrued Expenses', description: 'Interest payable', debit: D(0), credit: D(75000) }
      ],
      totalDebit: D(75000), totalCredit: D(75000), debitTotal: D(75000), creditTotal: D(75000)
    });
  }

  // Bank Charges (6200)
  for (const month of [
    { label: 'January', date: '2026-01-31', amount: 8500, ref: 'BC-2026-001' },
    { label: 'February', date: '2026-02-28', amount: 9200, ref: 'BC-2026-002' },
    { label: 'March', date: '2026-03-31', amount: 7800, ref: 'BC-2026-003' }
  ]) {
    entries.push({
      company: companyId, entryNumber: ref('FIN'),
      date: new Date(month.date),
      description: `Bank Charges — ${month.label}`,
      sourceType: 'bank_charge', sourceId: `seed_bc_${month.label.toLowerCase()}`, sourceReference: month.ref,
      status: 'posted', isAutoGenerated: true,
      createdBy: userId, postedBy: userId,
      lines: [
        { accountCode: '6200', accountName: 'Bank Charges', description: 'Monthly bank fees', debit: D(month.amount), credit: D(0) },
        { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank fees deducted', debit: D(0), credit: D(month.amount) }
      ],
      totalDebit: D(month.amount), totalCredit: D(month.amount), debitTotal: D(month.amount), creditTotal: D(month.amount)
    });
  }

  // ─────────────────────────────────────────────────────────────────
  // 12. TAX EXPENSE (Section 12)
  // ─────────────────────────────────────────────────────────────────

  // Corporate Tax accrual (6400) — Q1 provision
  entries.push({
    company: companyId, entryNumber: ref('TAX'),
    date: new Date('2026-03-31'),
    description: 'Corporate Tax accrual — Q1 2026',
    sourceType: 'tax_accrual', sourceId: 'seed_tax_001', sourceReference: 'TAX-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6400', accountName: 'Corporate Tax', description: 'Income tax provision Q1', debit: D(280000), credit: D(0) },
      { accountCode: '2400', accountName: 'Income Tax Payable', description: 'Tax liability', debit: D(0), credit: D(280000) }
    ],
    totalDebit: D(280000), totalCredit: D(280000), debitTotal: D(280000), creditTotal: D(280000)
  });

  // ─────────────────────────────────────────────────────────────────
  // 16. OTHER COMPREHENSIVE INCOME (Section 16)
  // ─────────────────────────────────────────────────────────────────

  // Loss on Asset Disposal (6050) — OCI item
  entries.push({
    company: companyId, entryNumber: ref('OCI'),
    date: new Date('2026-03-05'),
    description: 'Loss on disposal — Old equipment scrapped',
    sourceType: 'asset_disposal', sourceId: 'seed_loss_001', sourceReference: 'AD-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Scrap proceeds', debit: D(20000), credit: D(0) },
      { accountCode: '6050', accountName: 'Loss on Asset Disposal', description: 'Loss on scrap sale', debit: D(30000), credit: D(0) },
      { accountCode: '1700', accountName: 'Equipment', description: 'Asset removal', debit: D(0), credit: D(50000) }
    ],
    totalDebit: D(50000), totalCredit: D(50000), debitTotal: D(50000), creditTotal: D(50000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // Insert all entries
  // ═══════════════════════════════════════════════════════════════════
  console.log(`\nInserting ${entries.length} P&L journal entries...`);

  const inserted = await JournalEntry.insertMany(entries, { ordered: false }).catch(err => {
    if (err.insertedDocs && err.insertedDocs.length > 0) {
      console.log(`Inserted ${err.insertedDocs.length} entries (some duplicates skipped)`);
      return err.insertedDocs;
    }
    throw err;
  });

  console.log(`Successfully inserted ${inserted.length} journal entries`);

  // ── Rebuild AccountBalance for affected accounts ─────────────────
  const affectedCodes = new Set();
  inserted.forEach(e => e.lines.forEach(l => affectedCodes.add(l.accountCode)));
  console.log(`\nRebuilding AccountBalance for ${affectedCodes.size} accounts...`);

  for (const code of affectedCodes) {
    await AccountBalance.findOneAndUpdate(
      { company: companyId, accountCode: code },
      { $setOnInsert: { company: companyId, accountCode: code, debit: 0, credit: 0 } },
      { upsert: true, setDefaultsOnInsert: true }
    );
  }

  // Recalculate from ALL posted entries
  const allEntries = await JournalEntry.find({
    company: companyId,
    status: 'posted'
  }).setOptions({ skipTenant: true }).lean();

  // Reset all balances
  await AccountBalance.updateMany(
    { company: companyId },
    { $set: { debit: 0, credit: 0 } }
  ).setOptions({ skipTenant: true });

  // Rebuild
  for (const entry of allEntries) {
    for (const line of entry.lines) {
      const debit = parseFloat(line.debit?.toString() || '0');
      const credit = parseFloat(line.credit?.toString() || '0');
      if (debit > 0 || credit > 0) {
        await AccountBalance.adjust(companyId, line.accountCode, debit, credit);
      }
    }
  }

  console.log('AccountBalance rebuilt');

  // ── Summary ─────────────────────────────────────────────────────
  const summary = {};
  inserted.forEach(e => {
    const type = e.sourceType || 'unknown';
    summary[type] = (summary[type] || 0) + 1;
  });

  console.log('\n=== Entry Summary by Source Type ===');
  Object.entries(summary).sort().forEach(([type, count]) => {
    console.log(`  ${type}: ${count}`);
  });

  // ── Verify P&L Coverage ─────────────────────────────────────────
  console.log('\n=== IAS 1 P&L Coverage Check ===');
  const plAccounts = {
    '1. Revenue': ['4000', '4100'],
    '2. Cost of Sales': ['5000', '5100', '5110', '5150', '5200', '5300'],
    '4. Other Income': ['4200', '4300', '4250'],
    '5. Distribution Costs': ['5700', '5850'],
    '6. Administrative Expenses': ['5400', '5410', '5500', '5600', '5800', '6150'],
    '7. Other Expenses': ['5250', '6100'],
    '9. Finance Costs': ['6000', '6200'],
    '12. Tax': ['6400'],
    '16. OCI': ['6050']
  };

  for (const [section, codes] of Object.entries(plAccounts)) {
    const balances = await AccountBalance.find({
      company: companyId,
      accountCode: { $in: codes },
      $or: [{ debit: { $gt: 0 } }, { credit: { $gt: 0 } }]
    }).setOptions({ skipTenant: true }).lean();

    const hasData = balances.length > 0;
    console.log(`  ${hasData ? 'OK' : 'MISSING'} ${section}: ${balances.length}/${codes.length} accounts with data`);
    if (hasData) {
      balances.forEach(b => {
        console.log(`      ${b.accountCode}: DR ${b.debit} CR ${b.credit}`);
      });
    }
  }

  // ── Expected P&L Calculation ─────────────────────────────────────
  console.log('\n=== Expected P&L Summary ===');
  const totalRev = 1200000 + 1500000 + 1800000 - 80000; // Sales - Returns
  const totalCOGS = 350000 + 480000 + 550000 + 25000 + 30000 + 80000 + 80000 + 15000 - 30000;
  const grossProfit = totalRev - totalCOGS;
  const otherInc = 50000 + 15000 + 150000;
  const distCosts = 35000 + 42000 + 38000 + 45000 + 35000 + 25000;
  const adminExp = 180000 * 3 + 20000 * 3 + 60000 * 3 + 18000 * 3 + 42000 * 3 + 12000 * 2;
  const otherExp = 35000 + 22000;
  const ebit = grossProfit + otherInc - distCosts - adminExp - otherExp;
  const finCosts = 75000 * 3 + 8500 + 9200 + 7800;
  const pbt = ebit - finCosts;
  const tax = 280000;
  const pat = pbt - tax;
  const oci = -30000;
  const tci = pat + oci;

  console.log(`  Revenue:                ${totalRev.toLocaleString()}`);
  console.log(`  COGS:                   ${totalCOGS.toLocaleString()}`);
  console.log(`  Gross Profit:           ${grossProfit.toLocaleString()}`);
  console.log(`  Other Income:           ${otherInc.toLocaleString()}`);
  console.log(`  Distribution Costs:     ${distCosts.toLocaleString()}`);
  console.log(`  Admin Expenses:         ${adminExp.toLocaleString()}`);
  console.log(`  Other Expenses:         ${otherExp.toLocaleString()}`);
  console.log(`  EBIT:                   ${ebit.toLocaleString()}`);
  console.log(`  Finance Costs:          ${finCosts.toLocaleString()}`);
  console.log(`  PBT:                    ${pbt.toLocaleString()}`);
  console.log(`  Tax:                    ${tax.toLocaleString()}`);
  console.log(`  PAT:                    ${pat.toLocaleString()}`);
  console.log(`  OCI:                    ${oci.toLocaleString()}`);
  console.log(`  Total Comprehensive:    ${tci.toLocaleString()}`);

  console.log('\nSeed complete!');
  process.exit(0);
}

seed().catch(e => { console.error('Error:', e.message, e.stack); process.exit(1); });
