/**
 * Seed P&L Data — covers all 10 sections of the Income Statement.
 * Adds missing COGS, Other Income, Finance Costs, and Tax entries.
 *
 * Usage: node scripts/seedPLData.js <companyId> <userId>
 */
const mongoose = require('mongoose');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/stock-management';
const D = (v) => mongoose.Types.Decimal128.fromString(String(v));

async function seed() {
  const args = process.argv.slice(2);
  const companyId = args[0];
  const userId = args[1];

  if (!companyId) {
    console.error('Usage: node seedPLData.js <companyId> <userId>');
    process.exit(1);
  }

  await mongoose.connect(MONGODB_URI);
  console.log('Connected to MongoDB');

  const JournalEntry = require('../models/JournalEntry');
  const AccountBalance = require('../models/AccountBalance');

  // ── Add sourceType enum values if missing ────────────────────────
  try {
    const JournalEntryModel = mongoose.model('JournalEntry');
    const schema = JournalEntryModel.schema;
    const sourceTypePath = schema.path('sourceType');
    if (sourceTypePath && sourceTypePath.enumValues) {
      const needed = ['loan_interest', 'loan_drawdown', 'loan_repayment', 'asset_purchase', 'asset_disposal', 'depreciation', 'stock_adjustment', 'interest_accrual', 'bank_charge', 'other_income', 'tax_accrual'];
      for (const val of needed) {
        if (!sourceTypePath.enumValues.includes(val)) {
          sourceTypePath.enumValues.push(val);
        }
      }
    }
  } catch (e) {
    console.log('Note: Could not extend sourceType enum:', e.message);
  }

  // First, delete any existing P&L seed entries
  const deleted = await JournalEntry.deleteMany({
    company: companyId,
    sourceType: { $in: ['cogs', 'other_income', 'interest_accrual', 'bank_charge', 'tax_accrual', 'loan_interest', 'stock_adjustment'] }
  }).setOptions({ skipTenant: true });
  console.log('Cleared', deleted.deletedCount, 'existing P&L seed entries');

  const entries = [];
  let entryNum = 5000;
  const nextRef = () => { entryNum++; return `JE-PL-${entryNum}`; };

  // ═══════════════════════════════════════════════════════════════════
  // 2. COST OF GOODS SOLD (Account 5000)
  // ═══════════════════════════════════════════════════════════════════

  // COGS — recognized on sales (cost of goods sold to customers)
  // Jan: Sold goods costing 350,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-10'),
    description: 'COGS Recognition - INV-2026-001',
    sourceType: 'cogs', sourceId: 'cogs_001', sourceReference: 'INV-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5000', accountName: 'Cost of Goods Sold', description: 'Cost of goods sold', debit: D(350000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Inventory reduction', debit: D(0), credit: D(350000) }
    ],
    totalDebit: D(350000), totalCredit: D(350000), debitTotal: D(350000), creditTotal: D(350000)
  });

  // Feb: Sold goods costing 480,000
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-08'),
    description: 'COGS Recognition - INV-2026-004',
    sourceType: 'cogs', sourceId: 'cogs_002', sourceReference: 'INV-2026-004',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5000', accountName: 'Cost of Goods Sold', description: 'Cost of goods sold', debit: D(480000), credit: D(0) },
      { accountCode: '1400', accountName: 'Inventory', description: 'Inventory reduction', debit: D(0), credit: D(480000) }
    ],
    totalDebit: D(480000), totalCredit: D(480000), debitTotal: D(480000), creditTotal: D(480000)
  });

  // Freight In (5110) — direct shipping cost
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-15'),
    description: 'Freight In - Supplier ABC Ltd',
    sourceType: 'cogs', sourceId: 'freight_001', sourceReference: 'FR-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5110', accountName: 'Freight In', description: 'Shipping cost for goods', debit: D(25000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Freight payment', debit: D(0), credit: D(25000) }
    ],
    totalDebit: D(25000), totalCredit: D(25000), debitTotal: D(25000), creditTotal: D(25000)
  });

  // Direct Labor (5300)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Direct Labor - Warehouse Workers',
    sourceType: 'cogs', sourceId: 'dlabor_001', sourceReference: 'DL-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5300', accountName: 'Direct Labor', description: 'Warehouse labor', debit: D(80000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Labor payment', debit: D(0), credit: D(80000) }
    ],
    totalDebit: D(80000), totalCredit: D(80000), debitTotal: D(80000), creditTotal: D(80000)
  });

  // Purchase Returns contra (5200) — credit balance reduces COGS
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-15'),
    description: 'Purchase Return - Supplier XYZ',
    sourceType: 'stock_adjustment', sourceId: 'pret_001', sourceReference: 'PR-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '2000', accountName: 'Accounts Payable', description: 'Return to supplier', debit: D(35400), credit: D(0) },
      { accountCode: '5200', accountName: 'Purchase Returns', description: 'Purchase return credit', debit: D(0), credit: D(30000) },
      { accountCode: '2210', accountName: 'VAT Input', description: 'VAT reversal', debit: D(0), credit: D(5400) }
    ],
    totalDebit: D(35400), totalCredit: D(35400), debitTotal: D(35400), creditTotal: D(35400)
  });

  // ═══════════════════════════════════════════════════════════════════
  // 6. OTHER INCOME (Accounts 4200, 4300, 4250)
  // ═══════════════════════════════════════════════════════════════════

  // Other Income (4200) — e.g., rental income, commission received
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-20'),
    description: 'Other Income - Commission received',
    sourceType: 'other_income', sourceId: 'oinc_001', sourceReference: 'OI-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Commission received', debit: D(50000), credit: D(0) },
      { accountCode: '4200', accountName: 'Other Income', description: 'Commission income', debit: D(0), credit: D(50000) }
    ],
    totalDebit: D(50000), totalCredit: D(50000), debitTotal: D(50000), creditTotal: D(50000)
  });

  // Interest Income (4300)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-01'),
    description: 'Interest Income - Bank savings',
    sourceType: 'other_income', sourceId: 'oinc_002', sourceReference: 'OI-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Interest credited', debit: D(15000), credit: D(0) },
      { accountCode: '4300', accountName: 'Interest Income', description: 'Bank interest', debit: D(0), credit: D(15000) }
    ],
    totalDebit: D(15000), totalCredit: D(15000), debitTotal: D(15000), creditTotal: D(15000)
  });

  // Gain on Asset Disposal (4250)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-20'),
    description: 'Gain on disposal - Old vehicle sold',
    sourceType: 'asset_disposal', sourceId: 'gain_001', sourceReference: 'AD-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Sale proceeds', debit: D(800000), credit: D(0) },
      { accountCode: '4250', accountName: 'Gain on Asset Disposal', description: 'Gain on sale of vehicle', debit: D(0), credit: D(150000) },
      { accountCode: '1600', accountName: 'Vehicles', description: 'Asset removal', debit: D(0), credit: D(650000) }
    ],
    totalDebit: D(800000), totalCredit: D(800000), debitTotal: D(800000), creditTotal: D(800000)
  });

  // Loss on Asset Disposal (6050) — non-operating expense, goes to Other Income as negative
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-03-05'),
    description: 'Loss on disposal - Old equipment scrapped',
    sourceType: 'asset_disposal', sourceId: 'loss_001', sourceReference: 'AD-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Scrap proceeds', debit: D(20000), credit: D(0) },
      { accountCode: '6050', accountName: 'Loss on Asset Disposal', description: 'Loss on scrap sale', debit: D(30000), credit: D(0) },
      { accountCode: '1501', accountName: 'Equipment', description: 'Asset removal', debit: D(0), credit: D(50000) }
    ],
    totalDebit: D(50000), totalCredit: D(50000), debitTotal: D(50000), creditTotal: D(50000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // 7. FINANCE COSTS (Accounts 6000, 6200)
  // ═══════════════════════════════════════════════════════════════════

  // Interest Expense (6000) — loan interest charged
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Interest Expense - Bank loan January',
    sourceType: 'loan_interest', sourceId: 'int_001', sourceReference: 'LI-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6000', accountName: 'Interest Expense', description: 'Loan interest Jan', debit: D(75000), credit: D(0) },
      { accountCode: '2600', accountName: 'Accrued Expenses', description: 'Interest payable', debit: D(0), credit: D(75000) }
    ],
    totalDebit: D(75000), totalCredit: D(75000), debitTotal: D(75000), creditTotal: D(75000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Interest Expense - Bank loan February',
    sourceType: 'loan_interest', sourceId: 'int_002', sourceReference: 'LI-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6000', accountName: 'Interest Expense', description: 'Loan interest Feb', debit: D(75000), credit: D(0) },
      { accountCode: '2600', accountName: 'Accrued Expenses', description: 'Interest payable', debit: D(0), credit: D(75000) }
    ],
    totalDebit: D(75000), totalCredit: D(75000), debitTotal: D(75000), creditTotal: D(75000)
  });

  // Bank Charges (6200)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Bank Charges - January',
    sourceType: 'bank_charge', sourceId: 'bc_001', sourceReference: 'BC-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6200', accountName: 'Bank Charges', description: 'Monthly bank fees', debit: D(8500), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank fees deducted', debit: D(0), credit: D(8500) }
    ],
    totalDebit: D(8500), totalCredit: D(8500), debitTotal: D(8500), creditTotal: D(8500)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Bank Charges - February',
    sourceType: 'bank_charge', sourceId: 'bc_002', sourceReference: 'BC-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6200', accountName: 'Bank Charges', description: 'Monthly bank fees', debit: D(9200), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Bank fees deducted', debit: D(0), credit: D(9200) }
    ],
    totalDebit: D(9200), totalCredit: D(9200), debitTotal: D(9200), creditTotal: D(9200)
  });

  // ═══════════════════════════════════════════════════════════════════
  // 9. TAX EXPENSE (Account 6400)
  // ═══════════════════════════════════════════════════════════════════

  // Corporate Tax accrual (6400)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-03-31'),
    description: 'Corporate Tax accrual Q1 2026',
    sourceType: 'tax_accrual', sourceId: 'tax_001', sourceReference: 'TAX-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '6400', accountName: 'Corporate Tax', description: 'Income tax provision Q1', debit: D(180000), credit: D(0) },
      { accountCode: '2400', accountName: 'Income Tax Payable', description: 'Tax liability', debit: D(0), credit: D(180000) }
    ],
    totalDebit: D(180000), totalCredit: D(180000), debitTotal: D(180000), creditTotal: D(180000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // Additional Operating Expenses (to fill out the page)
  // ═══════════════════════════════════════════════════════════════════

  // Marketing (5850)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-15'),
    description: 'Marketing - Facebook ads campaign',
    sourceType: 'expense', sourceId: 'mktg_001', sourceReference: 'EXP-2026-006',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5850', accountName: 'Marketing & Advertising', description: 'Social media ads', debit: D(45000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(45000) }
    ],
    totalDebit: D(45000), totalCredit: D(45000), debitTotal: D(45000), creditTotal: D(45000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-15'),
    description: 'Marketing - Google ads campaign',
    sourceType: 'expense', sourceId: 'mktg_002', sourceReference: 'EXP-2026-007',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5850', accountName: 'Marketing & Advertising', description: 'Google ads', debit: D(35000), credit: D(0) },
      { accountCode: '1100', accountName: 'Cash at Bank', description: 'Payment', debit: D(0), credit: D(35000) }
    ],
    totalDebit: D(35000), totalCredit: D(35000), debitTotal: D(35000), creditTotal: D(35000)
  });

  // Depreciation (5800)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-01-31'),
    description: 'Depreciation - January',
    sourceType: 'depreciation', sourceId: 'dep_001', sourceReference: 'DEP-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5800', accountName: 'Depreciation Expense', description: 'Monthly depreciation', debit: D(42000), credit: D(0) },
      { accountCode: '1510', accountName: 'Accumulated Depreciation', description: 'Accum depreciation', debit: D(0), credit: D(42000) }
    ],
    totalDebit: D(42000), totalCredit: D(42000), debitTotal: D(42000), creditTotal: D(42000)
  });

  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Depreciation - February',
    sourceType: 'depreciation', sourceId: 'dep_002', sourceReference: 'DEP-2026-002',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5800', accountName: 'Depreciation Expense', description: 'Monthly depreciation', debit: D(42000), credit: D(0) },
      { accountCode: '1510', accountName: 'Accumulated Depreciation', description: 'Accum depreciation', debit: D(0), credit: D(42000) }
    ],
    totalDebit: D(42000), totalCredit: D(42000), debitTotal: D(42000), creditTotal: D(42000)
  });

  // Bad Debt (5250)
  entries.push({
    company: companyId, entryNumber: nextRef(),
    date: new Date('2026-02-28'),
    description: 'Bad Debt Write-off - Customer defaulted',
    sourceType: 'expense', sourceId: 'bad_001', sourceReference: 'BD-2026-001',
    status: 'posted', isAutoGenerated: true,
    createdBy: userId, postedBy: userId,
    lines: [
      { accountCode: '5250', accountName: 'Bad Debt Expense', description: 'Write-off bad debt', debit: D(35000), credit: D(0) },
      { accountCode: '1300', accountName: 'Accounts Receivable', description: 'AR written off', debit: D(0), credit: D(35000) }
    ],
    totalDebit: D(35000), totalCredit: D(35000), debitTotal: D(35000), creditTotal: D(35000)
  });

  // ═══════════════════════════════════════════════════════════════════
  // Insert all entries
  // ═══════════════════════════════════════════════════════════════════
  console.log(`\nInserting ${entries.length} P&L journal entries...`);

  const inserted = await JournalEntry.insertMany(entries, { ordered: false }).catch(err => {
    if (err.insertedDocs && err.insertedDocs.length > 0) {
      console.log(`Inserted ${err.insertedDocs.length} entries (some duplicates skipped)`);
      return err.insertedDocs;
    }
    throw err;
  });

  console.log(`Successfully inserted ${inserted.length} journal entries`);

  // ── Rebuild AccountBalance for affected accounts ─────────────────
  const affectedCodes = new Set();
  inserted.forEach(e => e.lines.forEach(l => affectedCodes.add(l.accountCode)));
  console.log(`\nRebuilding AccountBalance for ${affectedCodes.size} accounts...`);

  for (const code of affectedCodes) {
    // First reset
    await AccountBalance.findOneAndUpdate(
      { company: companyId, accountCode: code },
      { $setOnInsert: { company: companyId, accountCode: code, debit: 0, credit: 0 } },
      { upsert: true, setDefaultsOnInsert: true }
    );
  }

  // Recalculate from ALL posted entries
  const allEntries = await JournalEntry.find({
    company: companyId,
    status: 'posted'
  }).setOptions({ skipTenant: true }).lean();

  // Reset all balances
  await AccountBalance.updateMany(
    { company: companyId },
    { $set: { debit: 0, credit: 0 } }
  ).setOptions({ skipTenant: true });

  // Rebuild
  for (const entry of allEntries) {
    for (const line of entry.lines) {
      const debit = parseFloat(line.debit?.toString() || '0');
      const credit = parseFloat(line.credit?.toString() || '0');
      if (debit > 0 || credit > 0) {
        await AccountBalance.adjust(companyId, line.accountCode, debit, credit);
      }
    }
  }

  console.log('AccountBalance rebuilt');

  // Summary
  const summary = {};
  inserted.forEach(e => {
    const type = e.sourceType || 'unknown';
    summary[type] = (summary[type] || 0) + 1;
  });

  console.log('\nSummary by source type:');
  Object.entries(summary).sort().forEach(([type, count]) => {
    console.log(`  ${type}: ${count}`);
  });

  // Verify P&L coverage
  console.log('\n=== P&L Coverage Check ===');
  const plAccounts = {
    'Revenue': ['4000', '4100'],
    'COGS': ['5000', '5100', '5110', '5150', '5200', '5300'],
    'Operating Expenses': ['5250', '5400', '5410', '5500', '5600', '5700', '5800', '5850', '6100', '6150'],
    'Other Income': ['4200', '4300', '4250', '6050'],
    'Finance Costs': ['6000', '6200'],
    'Tax': ['6400']
  };

  for (const [section, codes] of Object.entries(plAccounts)) {
    const balances = await AccountBalance.find({
      company: companyId,
      accountCode: { $in: codes },
      $or: [{ debit: { $gt: 0 } }, { credit: { $gt: 0 } }]
    }).setOptions({ skipTenant: true }).lean();

    const hasData = balances.length > 0;
    console.log(`  ${hasData ? 'OK' : 'MISSING'} ${section}: ${balances.length}/${codes.length} accounts with data`);
    if (hasData) {
      balances.forEach(b => {
        const net = parseFloat(b.debit?.toString() || '0') - parseFloat(b.credit?.toString() || '0');
        console.log(`      ${b.accountCode}: DR ${b.debit} CR ${b.credit}`);
      });
    }
  }

  process.exit(0);
}

seed().catch(e => { console.error('Error:', e.message); process.exit(1); });
