const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri, { useNewUrlParser: true });
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongoServer) await mongoServer.stop();
});

afterEach(async () => {
  const collections = Object.keys(mongoose.connection.collections);
  for (const name of collections) {
    await mongoose.connection.collections[name].deleteMany({});
  }
});

test('createEntriesAtomic creates multiple journal entries and updates account balances', async () => {
  const JournalService = require('../../services/journalService');
  const JournalEntry = require('../../models/JournalEntry');
  const AccountBalance = require('../../models/AccountBalance');

  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  const entry1 = {
    date: new Date(),
    description: 'Test Revenue',
    sourceType: 'invoice',
    sourceId: new mongoose.Types.ObjectId(),
    sourceReference: 'TINV-1',
    lines: [
      { accountCode: 'AR-1', accountName: 'Accounts Receivable', debit: 200, credit: 0 },
      { accountCode: 'REV-1', accountName: 'Revenue', debit: 0, credit: 200 }
    ],
    isAutoGenerated: true
  };

  const entry2 = {
    date: new Date(),
    description: 'Test COGS',
    sourceType: 'cogs',
    sourceId: new mongoose.Types.ObjectId(),
    sourceReference: 'TCOGS-1',
    lines: [
      { accountCode: 'COGS-1', accountName: 'COGS', debit: 120, credit: 0 },
      { accountCode: 'INV-1', accountName: 'Inventory', debit: 0, credit: 120 }
    ],
    isAutoGenerated: true
  };

  const created = await JournalService.createEntriesAtomic(companyId, userId, [entry1, entry2]);

  expect(Array.isArray(created)).toBe(true);
  expect(created.length).toBe(2);

  const docs = await JournalEntry.find({ company: companyId });
  expect(docs.length).toBe(2);

  const abAR = await AccountBalance.findOne({ company: companyId, accountCode: 'AR-1' });
  const abREV = await AccountBalance.findOne({ company: companyId, accountCode: 'REV-1' });
  const abCOGS = await AccountBalance.findOne({ company: companyId, accountCode: 'COGS-1' });
  const abINV = await AccountBalance.findOne({ company: companyId, accountCode: 'INV-1' });

  expect(abAR.debit).toBeCloseTo(200);
  expect(abREV.credit).toBeCloseTo(200);
  expect(abCOGS.debit).toBeCloseTo(120);
  expect(abINV.credit).toBeCloseTo(120);
});
