const express = require('express');
const request = require('supertest');
const mongoose = require('mongoose');
const { MongoMemoryServer } = require('mongodb-memory-server');
const JournalService = require('../../services/journalService');
const JournalEntry = require('../../models/JournalEntry');

let mongoServer;

beforeAll(async () => {
  mongoServer = await MongoMemoryServer.create();
  const uri = mongoServer.getUri();
  await mongoose.connect(uri, { useNewUrlParser: true });
});

afterAll(async () => {
  await mongoose.disconnect();
  if (mongoServer) await mongoServer.stop();
});

afterEach(async () => {
  const collections = Object.keys(mongoose.connection.collections);
  for (const name of collections) {
    await mongoose.connection.collections[name].deleteMany({});
  }
});

test('POST /api/journal-entries/:id/reverse (API) creates reversal and marks original', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  // Create a posted journal entry via service
  const lines = [
    JournalService.createDebitLine('1300', 500, 'API debit'),
    JournalService.createCreditLine('2100', 500, 'API credit')
  ];

  const orig = await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'API original',
    sourceType: 'manual',
    sourceId: new mongoose.Types.ObjectId(),
    sourceReference: 'API-1',
    lines,
    isAutoGenerated: false
  });

  // Build minimal express app that mounts a single route calling the controller directly
  const app = express();
  app.use(express.json());

  // Minimal route that injects a mock user and calls the controller
  const journalController = require('../../controllers/journalController');
  app.post('/api/journal-entries/:id/reverse', (req, res, next) => {
    req.user = { _id: userId, company: { _id: companyId } };
    journalController.reverseJournalEntry(req, res, next);
  });

  const resp = await request(app)
    .post(`/api/journal-entries/${orig._id}/reverse`)
    .send({ reason: 'API test reversal' })
    .expect(200);

  expect(resp.body.success).toBe(true);
  expect(resp.body.data).toBeDefined();

  // Verify DB
  const reloaded = await JournalEntry.findById(orig._id).lean();
  expect(reloaded.status).toBe('reversed');
  expect(reloaded.reversed).toBe(true);
  expect(reloaded.reversalEntryId).toBeDefined();

  const reversal = await JournalEntry.findOne({ sourceType: 'reversal', sourceId: orig._id });
  expect(reversal).toBeDefined();
  expect(reversal.totalDebit).toBeCloseTo(orig.totalCredit, 2);
  expect(reversal.totalCredit).toBeCloseTo(orig.totalDebit, 2);
});

test('POST reversal is idempotent: calling twice returns same reversal', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  const lines = [
    JournalService.createDebitLine('1300', 50, 'Debit'),
    JournalService.createCreditLine('2100', 50, 'Credit')
  ];

  const orig = await JournalService.createEntry(companyId, userId, {
    date: new Date(),
    description: 'API idempotent original',
    sourceType: 'manual',
    sourceId: new mongoose.Types.ObjectId(),
    sourceReference: 'API-2',
    lines,
    isAutoGenerated: false
  });

  const app = express();
  app.use(express.json());
  const journalController = require('../../controllers/journalController');
  app.post('/api/journal-entries/:id/reverse', (req, res, next) => {
    req.user = { _id: userId, company: { _id: companyId } };
    journalController.reverseJournalEntry(req, res, next);
  });

  const r1 = await request(app).post(`/api/journal-entries/${orig._id}/reverse`).send({ reason: 'first' }).expect(200);
  const r2 = await request(app).post(`/api/journal-entries/${orig._id}/reverse`).send({ reason: 'second' }).expect(200);

  expect(r1.body.success).toBe(true);
  expect(r2.body.success).toBe(true);
  expect(r1.body.data._id).toBeDefined();
  expect(r2.body.data._id).toBeDefined();
  expect(r1.body.data._id).toBe(r2.body.data._id);
});

test('Reverse fails when period is closed', async () => {
  const companyId = new mongoose.Types.ObjectId();
  const userId = new mongoose.Types.ObjectId();

  const lines = [
    JournalService.createDebitLine('1300', 80, 'Debit'),
    JournalService.createCreditLine('2100', 80, 'Credit')
  ];

  // Create original
  const orig = await JournalService.createEntry(companyId, userId, {
    date: new Date('2020-01-15'),
    description: 'To be closed period',
    sourceType: 'manual',
    sourceId: new mongoose.Types.ObjectId(),
    sourceReference: 'API-3',
    lines,
    isAutoGenerated: false
  });

  // Create a closed Period that includes the entry date
  const Period = require('../../models/Period');
  await Period.create({ company: companyId, name: 'Jan 2020', startDate: new Date('2020-01-01'), endDate: new Date('2020-01-31'), status: 'closed' });

  const app = express();
  app.use(express.json());
  const journalController = require('../../controllers/journalController');
  app.post('/api/journal-entries/:id/reverse', (req, res, next) => {
    req.user = { _id: userId, company: { _id: companyId } };
    journalController.reverseJournalEntry(req, res, next);
  });

  const r = await request(app).post(`/api/journal-entries/${orig._id}/reverse`).send({ reason: 'closed' }).expect(400);
  expect(r.body.success).toBe(false);
  expect(r.body.message).toMatch(/period/i);
});

