const mongoose = require('mongoose');

// Journal Entry Line Schema (individual debit/credit lines)
const journalLineSchema = new mongoose.Schema({
  accountCode: { type: String, required: true, trim: true },
  accountName: { type: String, required: true, trim: true },
  description: { type: String, trim: true },
  debit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  credit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  reference: { type: String, trim: true }
}, { _id: false });

// Journal Entry Main Schema
const journalEntrySchema = new mongoose.Schema({
  // Company reference
  company: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: true
  },
  
  // Entry details
  entryNumber: {
    type: String,
    required: true,
    unique: true
  },
  date: {
    type: Date,
    required: true,
    default: Date.now
  },
  description: {
    type: String,
    required: true,
    trim: true
  },
  
  // Reference to source document (optional)
  sourceType: {
    type: String,
    enum: ['manual', 'invoice', 'purchase', 'purchase_order', 'credit_note', 'expense', 'asset', 'depreciation', 'loan', 'payment', 'adjustment', 'petty_cash', 'petty_cash_expense', 'petty_cash_replenishment', 'purchase_return', 'stock_adjustment', 'payroll', 'tax_payment', 'bank_transfer', 'opening_balance', 'reversal', 'cogs', 'stock_transfer', 'stock_audit', 'cogs_adjustment', 'cogs_adjustment_reversal', null],
    default: 'manual'
  },
  sourceId: {
    type: mongoose.Schema.Types.ObjectId,
    refPath: 'sourceType'
  },
  sourceReference: {
    type: String,
    trim: true
  },
  
  // Entry lines (debits and credits)
  lines: [journalLineSchema],
  
  // Status
  status: {
    type: String,
    enum: ['draft', 'posted', 'voided', 'reversed'],
    default: 'draft'
  },
  
  // Totals (for validation) - use Decimal128 for monetary precision
  totalDebit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  totalCredit: { type: mongoose.Schema.Types.Decimal128, default: mongoose.Types.Decimal128.fromString('0.00') },
  
  // Metadata
  isAutoGenerated: {
    type: Boolean,
    default: false
  },
  reversalOf: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'JournalEntry',
    default: null
  },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
  postedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  notes: {
    type: String,
    trim: true
  }
  ,
  // Reversal metadata
  reversed: {
    type: Boolean,
    default: false
  },
  reversedAt: {
    type: Date,
    default: null
  },
  reversedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  reversalEntryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'JournalEntry',
    default: null
  }
}, {
  timestamps: true
});

// Plugin for audit fields and soft-delete
const auditPlugin = require('./plugins/auditSoftDeletePlugin');
journalEntrySchema.plugin(auditPlugin);

// Convert Decimal128 results to JS numbers for compatibility with tests and lean queries
const decimalTransform = require('./plugins/decimalTransformPlugin');
journalEntrySchema.plugin(decimalTransform);

// Extra safety: ensure totals and line amounts are plain numbers after queries
function coerceDecimalField(val) {
  if (val == null) return 0;
  if (typeof val === 'number') return val;
  if (typeof val === 'string') return Number(val);
  if (val && typeof val === 'object') {
    if (val.$numberDecimal) return Number(val.$numberDecimal);
    try { return Number(val.toString()); } catch (e) { return 0; }
  }
  return Number(val) || 0;
}

function coerceJournalDoc(doc) {
  if (!doc) return;
  try {
    // Prefer operating on the underlying plain object when present
    const base = (doc._doc && typeof doc._doc === 'object') ? doc._doc : doc;
    if (base.totalDebit !== undefined) base.totalDebit = coerceDecimalField(base.totalDebit);
    if (base.totalCredit !== undefined) base.totalCredit = coerceDecimalField(base.totalCredit);
    if (Array.isArray(base.lines)) {
      base.lines.forEach(l => {
        if (l.debit !== undefined) l.debit = coerceDecimalField(l.debit);
        if (l.credit !== undefined) l.credit = coerceDecimalField(l.credit);
      });
    }
  } catch (e) {
    // swallow; best-effort
  }
}

journalEntrySchema.post('find', function(docs) {
  if (!docs) return;
  for (const d of docs) coerceJournalDoc(d);
});

journalEntrySchema.post('findOne', function(doc) {
  coerceJournalDoc(doc);
});

journalEntrySchema.post('aggregate', function(result) {
  if (!result) return;
  for (const r of result) coerceJournalDoc(r);
});

// Use sequence service for gap-free entry numbers
const { nextSequence } = require('../services/sequenceService');

// Ensure Decimal128 fields serialize as strings with two decimals
journalEntrySchema.set('toJSON', {
  virtuals: true,
  transform: (doc, ret) => {
    const toStr = (val) => {
      if (val == null) return '0.00';
      try { return parseFloat(val.toString()).toFixed(2); } catch (e) { return String(val); }
    };
    if (ret.totalDebit !== undefined) ret.totalDebit = toStr(ret.totalDebit);
    if (ret.totalCredit !== undefined) ret.totalCredit = toStr(ret.totalCredit);
    if (Array.isArray(ret.lines)) {
      ret.lines = ret.lines.map(l => ({
        accountCode: l.accountCode,
        accountName: l.accountName,
        description: l.description,
        debit: toStr(l.debit),
        credit: toStr(l.credit),
        reference: l.reference
      }));
    }
    return ret;
  }
});

// Compound index for company + date
journalEntrySchema.index({ company: 1, date: -1 });
journalEntrySchema.index({ company: 1, entryNumber: 1 });
// Ensure we don't create duplicate journal entries for the same source event
// Enforce only when sourceId is present (manual entries without sourceId are excluded)
journalEntrySchema.index(
  { company: 1, sourceType: 1, sourceId: 1 },
  { unique: true, partialFilterExpression: { sourceId: { $exists: true, $ne: null } } }
);

// Pre-save middleware to calculate totals
journalEntrySchema.pre('save', function(next) {
  // Calculate totals from lines (handle Decimal128 values)
  try {
    const sumDebit = this.lines.reduce((sum, line) => {
      const v = line.debit && line.debit.toString ? parseFloat(line.debit.toString()) : Number(line.debit || 0);
      return sum + (isFinite(v) ? v : 0);
    }, 0);
    const sumCredit = this.lines.reduce((sum, line) => {
      const v = line.credit && line.credit.toString ? parseFloat(line.credit.toString()) : Number(line.credit || 0);
      return sum + (isFinite(v) ? v : 0);
    }, 0);

    // Store as Decimal128 strings to preserve precision
    this.totalDebit = mongoose.Types.Decimal128.fromString(sumDebit.toFixed(2));
    this.totalCredit = mongoose.Types.Decimal128.fromString(sumCredit.toFixed(2));

    // Validate balanced entry - fail fast if not balanced
    if (Math.abs(sumDebit - sumCredit) > 0.01) {
      return next(new Error('Journal entry is not balanced: totalDebit != totalCredit'));
    }
    next();
  } catch (err) {
    return next(err);
  }
});

// Prevent updates to posted entries via findOneAndUpdate / updateOne
journalEntrySchema.pre('findOneAndUpdate', async function(next) {
  try {
    const query = this.getQuery();
    const doc = await this.model.findOne(query).lean();
    if (doc && doc.status === 'posted') {
      return next(new Error('Cannot modify a posted journal entry'));
    }
    next();
  } catch (err) {
    next(err);
  }
});

// Prevent deletions of posted entries via deleteOne / deleteMany
journalEntrySchema.pre('deleteOne', { document: false, query: true }, async function(next) {
  try {
    const query = this.getQuery();
    const doc = await this.model.findOne(query).lean();
    if (doc && doc.status === 'posted') {
      return next(new Error('Cannot delete a posted journal entry'));
    }
    next();
  } catch (err) {
    next(err);
  }
});

// Static method to generate entry number
journalEntrySchema.statics.generateEntryNumber = async function(companyId) {
  const year = new Date().getFullYear();
  const seq = await nextSequence(companyId, 'journal_entry');
  const companyPrefix = String(companyId).slice(-4).toUpperCase();
  return `JE-${companyPrefix}-${year}-${seq}`;
};

// Method to validate debits equal credits
journalEntrySchema.methods.isBalanced = function() {
  const td = this.totalDebit && this.totalDebit.toString ? parseFloat(this.totalDebit.toString()) : Number(this.totalDebit || 0);
  const tc = this.totalCredit && this.totalCredit.toString ? parseFloat(this.totalCredit.toString()) : Number(this.totalCredit || 0);
  return Math.abs(td - tc) < 0.01;
};

// Static method to get trial balance
journalEntrySchema.statics.getTrialBalance = async function(companyId, startDate, endDate) {
  const query = { 
    company: companyId, 
    status: 'posted',
    date: { $gte: startDate, $lte: endDate }
  };
  
  const entries = await this.find(query);
  
  const accountBalances = {};
  
  entries.forEach(entry => {
    entry.lines.forEach(line => {
      const code = line.accountCode;
      if (!accountBalances[code]) {
        accountBalances[code] = {
          code,
          name: line.accountName,
          debit: 0,
          credit: 0,
          balance: 0
        };
      }
      
      accountBalances[code].debit += line.debit || 0;
      accountBalances[code].credit += line.credit || 0;
    });
  });
  
  // Calculate balances based on normal balance
  Object.values(accountBalances).forEach(account => {
    // This will be adjusted based on account type in the report
    account.balance = account.debit - account.credit;
  });
  
  return accountBalances;
};

const JournalEntry = mongoose.model('JournalEntry', journalEntrySchema);

module.exports = JournalEntry;
