const mongoose = require('mongoose');

// Liability Transaction Schema - for tracking drawdowns, repayments, interest charges
const liabilityTransactionSchema = new mongoose.Schema({
  transactionDate: {
    type: Date,
    required: true
  },
  type: {
    type: String,
    enum: ['drawdown', 'repayment', 'interest_charge'],
    required: true
  },
  amount: {
    type: Number,
    required: true,
    min: 0.01
  },
  principalPortion: {
    type: Number,
    default: 0
  },
  interestPortion: {
    type: Number,
    default: 0
  },
  bankAccountId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'BankAccount',
    default: null
  },
  journalEntryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'JournalEntry',
    default: null
  },
  notes: {
    type: String,
    default: null
  }
}, {
  timestamps: true
});

const liabilitySchema = new mongoose.Schema({
  // Multi-tenancy: company reference (using company_id as per spec)
  company_id: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Company',
    required: [true, 'Liability must belong to a company'],
    index: true
  },
  
  // Reference number - unique per company
  reference_no: {
    type: String,
    default: function() { return null; } // Generated by pre-save hook
  },
  
  // Liability name
  name: {
    type: String,
    required: [true, 'Please provide liability name'],
    trim: true
  },
  
  // Liability type
  type: {
    type: String,
    enum: ['loan', 'hire_purchase', 'accrual', 'other'],
    required: true
  },
  
  // Lender info
  lenderName: {
    type: String,
    trim: true,
    default: null
  },
  
  // Financial amounts
  principalAmount: {
    type: Number,
    required: true,
    min: 0.01
  },
  
  // Outstanding balance
  outstandingBalance: {
    type: Number,
    required: true,
    default: function() { return this.principalAmount; }
  },
  
  // Interest
  interestRatePct: {
    type: Number,
    default: null
  },
  
  // Interest calculation method
  interestMethod: {
    type: String,
    enum: ['simple', 'compound'],
    default: 'simple'
  },
  
  // Duration in months
  durationMonths: {
    type: Number,
    min: 1
  },
  
  // Account references for journal entries
  liabilityAccountId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ChartOfAccount',
    required: [true, 'Liability account is required']
  },
  interestExpenseAccountId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ChartOfAccount',
    default: null
  },
  
  // Dates
  startDate: {
    type: Date,
    required: true
  },
  endDate: {
    type: Date,
    default: null
  },
  
  // Status
  status: {
    type: String,
    enum: ['active', 'fully_repaid', 'cancelled'],
    default: 'active'
  },
  
  // Transaction tracking
  transactions: [liabilityTransactionSchema],
  
  // Journal entry for initial drawdown
  journalEntryId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'JournalEntry',
    default: null
  },
  
  // Notes
  notes: {
    type: String,
    default: null
  },
  
  // User tracking
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  }
}, {
  timestamps: true
});

// Compound index for company_id + unique reference_no
liabilitySchema.index({ company_id: 1, reference_no: 1 }, { unique: true });
liabilitySchema.index({ company_id: 1 });
liabilitySchema.index({ company_id: 1, status: 1 });

// Pre-save middleware to auto-generate reference number
liabilitySchema.pre('save', async function(next) {
  if (this.isNew && !this.reference_no) {
    const count = await mongoose.model('Liability').countDocuments({ company_id: this.company_id });
    this.reference_no = `LIB-${String(count + 1).padStart(5, '0')}`;
  }
  // Set outstandingBalance to principalAmount if not set
  if (this.isNew && !this.outstandingBalance) {
    this.outstandingBalance = this.principalAmount;
  }
  next();
});

liabilitySchema.set('toJSON', { virtuals: true });
liabilitySchema.set('toObject', { virtuals: true });

module.exports = mongoose.model('Liability', liabilitySchema);
